# -*- coding: utf-8 -*-
# Invelis (topbar, meniu, subsol), prima pagina, elemente comune tuturor paginilor.
T = {
# ---- invelis --------------------------------------------------------------
"Apartamente noi în Iași, zona Păcurari — Emerald City": "New apartments in Iași, Păcurari area — Emerald City",
"Apartamente Iași, zona Păcurari —": "Apartments in Iași, Păcurari area —",
"DIRECT DEZVOLTATOR": "DIRECT FROM THE DEVELOPER",
"vanzari@emerald-city.ro": "vanzari@emerald-city.ro",
"Despre noi": "About us",
"Proiectul": "The project",
"Proiect": "Project",
"{n} blocuri P+{n}E, indicatori urbanistici": "{n} buildings GF+{n}, planning indicators",
"Amplasament": "Location",
"Iași, zona Păcurari — distanțe și acces": "Iași, Păcurari area — distances and access",
"Jurnal de șantier": "Site diary",
"Stadiul lucrărilor, actualizat lunar": "Construction progress, updated monthly",
"Compania": "The company",
"Finisaje, garanții, documente și proces": "Finishes, warranties, documents and process",
"Dezvoltator": "Developer",
"Tala Sapphire S.R.L., avize și echipă": "Tala Sapphire S.R.L., permits and team",
"Apariții în presă": "Press coverage",
"Materiale și date pentru jurnaliști": "Materials and facts for journalists",
"Finisaje": "Finishes",
"Dotări incluse la cheie": "Turnkey features included",
"Stadiul lucrărilor": "Construction progress",
"Publicăm lunar progresul real, cu fotografii datate din teren": "Real progress published monthly, with dated site photos",
"Apartamente": "Apartments",
"După numărul de camere": "By number of rooms",
"Apartament {n} cameră": "{n}-room apartment",
"{n} libere · {n} m² · de la {n} €": "{n} available · {n} m² · from €{n}",
"Apartamente {n} camere": "{n}-room apartments",
"Compartimentări": "Layouts",
"{n}A": "{n}A",
"{n}B": "{n}B",
"{n} m²": "{n} m²",
"{n} libere": "{n} available",
"Disponibilitate și prețuri": "Availability and prices",
"Toate cele {n} cu filtre": "All {n}, with filters",
"Investiție și randament": "Investment and yield",
"Calculator de chirie și amortizare": "Rent and payback calculator",
"{n} apartamente disponibile": "{n} apartments available",
"Preț și disponibilitate actualizate din tabelul de vânzări": "Price and availability updated from the sales ledger",
"Disponibilitate": "Availability",
"Investiție": "Investment",
"Contact": "Contact",
"Programare vizionare": "Book a viewing",
"Emerald City — acasă": "Emerald City — home",
"Emerald City": "Emerald City",
"Acasă": "Home",
"Facebook": "Facebook", "Instagram": "Instagram", "TikTok": "TikTok", "YouTube": "YouTube",
"Română": "Romanian", "English": "English", "Limba / Language": "Language",
"RO": "RO", "EN": "EN",
# subsol
"{n} de apartamente în nordul Iașului, pe cinci hectare din care aproape o treime rămâne verde.":
    "{n} apartments in the north of Iași, on five hectares of which almost a third stays green.",
"Sună direct": "Call us directly",
"Contact WhatsApp": "WhatsApp",
"Răspundem azi": "We reply today",
"Email": "Email",
"Cumperi ca investiție?": "Buying as an investment?",
"Calculator de randament": "Yield calculator",
"Blocuri {n}D+P+{n}E": "Buildings {n}B+GF+{n}",
"Spațiu verde": "Green space",
"Locuri de parcare": "Parking spaces",
"Comparator de apartamente": "Apartment comparison",
"Tipologii": "Layouts",
"Apartament Tip {n}A": "Type {n}A apartment",
"Apartament Tip {n}B": "Type {n}B apartment",
"Util": "Useful",
"Informații legale": "Legal information",
"Termeni și condiții": "Terms and conditions",
"Politica de confidențialitate": "Privacy policy",
"Politica de cookies": "Cookie policy",
"Informare GDPR": "GDPR notice",
"ANPC — SAL": "ANPC — ADR",
"ANPC — SOL": "ANPC — ODR",
"© {n} Emerald City · Tala Sapphire S.R.L. · Str. Ion Nistor, Iași": "© {n} Emerald City · Tala Sapphire S.R.L. · Str. Ion Nistor, Iași",
"Designed by Dianys Holding": "Designed by Dianys Holding",
"Discută pe WhatsApp": "Chat on WhatsApp",
"Scrie-ne pe WhatsApp": "Message us on WhatsApp",
"Apartament 1 cameră": "1-room apartment",
"Apartamente 2 camere": "2-room apartments",
"Apartamente 3 camere": "3-room apartments",
"Apartament 1 cameră": "1-room apartment",
"Apartamente 1 cameră": "1-room apartments",
"Apartament Tip 1A": "Type 1A apartment",
"Apartament Tip 2A": "Type 2A apartment",
"Apartament Tip 2B": "Type 2B apartment",
"Apartament Tip 3A": "Type 3A apartment",
"Apartament Tip 3B": "Type 3B apartment",
"Firimituri": "Breadcrumbs",
# ---- prima pagina ---------------------------------------------------------
"Direct dezvoltator · Tala Sapphire": "Direct from the developer · Tala Sapphire",
"Apartamente noi în Iași": "New apartments in Iași",
"zona Păcurari": "Păcurari area",
"Locuințe proiectate pentru confort zilnic: lumină naturală în toate camerele, compartimentări eficiente și spații verzi amenajate la câțiva pași de intrare.":
    "Homes designed for everyday comfort: natural light in every room, efficient layouts and landscaped green spaces a few steps from the entrance.",
"Contact telefonic": "Call us",
"WhatsApp": "WhatsApp",
"Lista apartamentelor": "Apartment list",
"Finisaje premium incluse": "Premium finishes included",
"Parcare subterană": "Underground parking",
"Parc și loc de joacă": "Park and playground",
"Conceptul": "The concept",
"Un nou standard de": "A new standard of",
"confort urban": "urban comfort",
"prinde contur în Iași.": "is taking shape in Iași.",
"Emerald City redefinește experiența locuirii urbane prin atenția la detalii și calitatea execuției. Fiecare spațiu este conceput pentru confort, lumină și funcționalitate.":
    "Emerald City redefines urban living through attention to detail and quality of execution. Every space is designed for comfort, light and functionality.",
"Materiale premium și standarde ridicate de construcție creează un mediu sigur, elegant și durabil — un loc în care te întorci cu plăcere.":
    "Premium materials and high construction standards create a safe, elegant and durable environment — a place you are glad to come home to.",
"Cum e gândit ansamblul": "How the development is designed",
"Blocuri P+{n}E": "Buildings GF+{n}",
"Spațiu verde amenajat": "Landscaped green space",
"{n} {n} și {n} camere": "{n}, {n} and {n} rooms",
"Compartimentări eficiente, fără suprafețe pierdute pe holuri. Fiecare apartament are balcon, lumină naturală în toate camerele și acces direct din zona de zi spre exterior. Suprafețele utile pornesc de la {n} m² pentru o cameră și ajung la {n} m² pentru trei camere, iar apartamentele de la parter au curte proprie. Boxa de la demisol și locul de parcare subteran se pot achiziționa separat.":
    "Efficient layouts, with no space wasted on corridors. Every apartment has a balcony, natural light in every room and direct access outdoors from the living area. Usable areas start at {n} m² for one room and reach {n} m² for three rooms, while ground-floor apartments have a private garden. The basement storage room and the underground parking space can be purchased separately.",
"Premium, incluse în preț": "Premium, included in the price",
"Apartamentul se predă finisat complet. Paletă caldă în tonuri nisip, stejar deschis pe pardoseală și piatră naturală în băi — materiale alese pentru durabilitate, nu doar pentru prezentare. Tâmplăria are geam termoizolant, băile au încălzire în pardoseală, iar iluminatul ambiental este integrat din proiect. Nu urmează o etapă suplimentară de amenajare și nici costuri neprevăzute după recepție.":
    "The apartment is handed over fully finished. A warm palette in sand tones, light oak flooring and natural stone in the bathrooms — materials chosen for durability, not just for show. Windows are thermally insulated, bathrooms have underfloor heating and ambient lighting is built into the design. There is no additional fit-out stage and no unexpected costs after handover.",
"Zona de zi": "Living area",
"Living, dining și bucătărie, deschise": "Open-plan living, dining and kitchen",
"Bucătăria este deschisă spre living, iar zona de masă primește lumină directă. Balconul prelungește spațiul de zi, în loc să îl închidă — util mai ales când ai invitați. Distanțele generoase dintre blocuri și regimul P+{n}E înseamnă că lumina ajunge în cameră pe tot parcursul zilei, nu doar câteva ore dimineața.":
    "The kitchen opens onto the living room and the dining area receives direct light. The balcony extends the living space instead of closing it off — especially useful when you have guests. Generous distances between buildings and the GF+{n} height mean light reaches the room all day long, not just for a few hours in the morning.",
"{n} de locuri la subsol și {n} supraterane.": "{n} underground spaces and {n} at surface level.",
"Spații verzi": "Green spaces",
"{n} m² amenajați, parc dendrologic și loc de joacă.": "{n} m² landscaped, with an arboretum park and a playground.",
"Intrare și depozitare": "Entrance and storage",
"Hol generos, boxă inclusă": "Generous hallway, storage room included",
"Hol cu spațiu pentru dulap pe toată înălțimea și boxă proprie la demisol. Obiectele sezoniere au unde sta, iar locuința rămâne degajată. Accesul în bloc se face cu interfon, fiecare scară are lift, iar mașina rămâne la subsol — nu în fața ferestrei.":
    "A hallway with room for a full-height wardrobe and a private storage room in the basement. Seasonal items have their place and the home stays uncluttered. Building access is by intercom, every staircase has a lift, and the car stays in the basement — not in front of your window.",
"{n} — Disponibilitate": "{n} — Availability",
"Trei etape,": "Three phases,",
"{n} de locuințe": "{n} homes",
"Prețurile includ TVA, cu avans de {n}% la antecontract și diferența la predare. Disponibilitatea se actualizează pe măsură ce se semnează contractele.":
    "Prices include VAT, with a {n}% deposit at the pre-sale agreement and the balance on handover. Availability is updated as contracts are signed.",
"Apartamente disponibile acum": "Apartments available now",
"Actualizat din tabelul de vânzări. Prețurile includ TVA.": "Updated from the sales ledger. Prices include VAT.",
"{n} — Caută": "{n} — Search",
"Caută": "Find",
"apartamentul potrivit": "the right apartment",
"Filtrează după camere, buget și etaj. Rezultatele se actualizează instant, fără reîncărcare.":
    "Filter by rooms, budget and floor. Results update instantly, without reloading.",
"Camere": "Rooms",
"{n} cameră": "{n} room",
"{n} camere": "{n} rooms",
"Buget maxim": "Maximum budget",
"Etaj": "Floor",
"Parter": "Ground floor",
"Resetează": "Reset",
"Se încarcă…": "Loading…",
"Toate cele {n} de apartamente": "All {n} apartments",
"{n} — Tipologii": "{n} — Layouts",
"{n} tipuri de": "{n} types of",
"compartimentări": "layouts",
"De la garsonieră la trei camere, fiecare cu plan propriu și listă de unități disponibile.":
    "From studio to three rooms, each with its own floor plan and list of available units.",
"Modele de apartamente": "Apartment models",
"{n} — Finisaje": "{n} — Finishes",
"Finisat complet,": "Fully finished,",
"predat la cheie": "handed over turnkey",
"Apartamentul se predă finisat complet, fără luni suplimentare de amenajare și fără costuri neprevăzute.":
    "The apartment is handed over fully finished, with no extra months of fit-out and no unexpected costs.",
"Living și bucătărie": "Living room and kitchen",
"Zonă de zi deschisă, cu bucătărie integrată și acces direct la balcon.": "Open living area with an integrated kitchen and direct access to the balcony.",
"Dormitoare": "Bedrooms",
"Tâmplărie cu geam termoizolant și iluminat ambiental reglabil.": "Thermally insulated windows and adjustable ambient lighting.",
"Grupuri sanitare": "Bathrooms",
"Piatră naturală, baterii încastrate și corpuri suspendate, ușor de întreținut.": "Natural stone, recessed taps and wall-hung fixtures, easy to maintain.",
"Imaginile au caracter orientativ. Amenajarea nu este inclusă în prețul de vânzare.": "Images are indicative. Furnishing is not included in the sale price.",
"{n} — Facilități": "{n} — Amenities",
"Dotări în": "Amenities in",
"cartier": "the neighbourhood",
"Dotări prevăzute în proiectul ansamblului, gândite pentru utilizare zilnică.": "Amenities included in the development's design, planned for daily use.",
"{n} dotări, toate prevăzute în proiect": "{n} amenities, all included in the design",
"De la parcarea subterană și panourile fotovoltaice, până la pistele de biciclete și colectarea îngropată a deșeurilor.":
    "From underground parking and photovoltaic panels to cycle lanes and underground waste collection.",
"Piste de biciclete": "Cycle lanes",
"Zone de fitness": "Fitness areas",
"Locuri de joacă": "Playgrounds",
"Încălzire în pardoseală": "Underfloor heating",
"Parcări private": "Private parking",
"Preechipare stații de încărcare": "Pre-wiring for EV chargers",
"Lifturi performante": "High-performance lifts",
"Panouri fotovoltaice": "Photovoltaic panels",
"Spații verzi și parc": "Green spaces and park",
"Colectare îngropată a deșeurilor": "Underground waste collection",
"Compartimentare specială": "Special layout",
"Apartamentele de la parter, cu curte proprie": "Ground-floor apartments with a private garden",
"Grădină proprie la nivelul locuinței, cu acces direct din zona de zi, păstrând avantajele unui apartament nou: lift, parcare la subsol, boxă și costuri de întreținere reduse.":
    "A private garden at home level, with direct access from the living area, keeping the advantages of a new apartment: lift, basement parking, storage room and low running costs.",
"Curte proprie, delimitată, între {n} m² și {n} m²": "Private, enclosed garden between {n} m² and {n} m²",
"Suprafețe utile de la {n} m² până la {n} m²": "Usable areas from {n} m² to {n} m²",
"Compartimentări de la {n} la {n} camere": "Layouts from {n} to {n} rooms",
"Ieșire directă din zona de zi, fără scări comune": "Direct exit from the living area, no communal stairs",
"Cele {n} de apartamente cu curte": "The {n} apartments with a garden",
"{n} de apartamente cu curte · de la {n} €": "{n} apartments with a garden · from €{n}",
"{n} — Condiții": "{n} — Terms",
"Condiții": "Purchase",
"de achiziție": "terms",
"Plată structurată simplu: avans la antecontract, iar diferența la predare. Fără costuri ascunse și fără comision de intermediere.":
    "Simply structured payment: a deposit at the pre-sale agreement and the balance on handover. No hidden costs and no agency commission.",
"Avans la antecontract": "Deposit at the pre-sale agreement",
"La semnarea antecontractului se achită un avans de {n}% din valoarea apartamentului.": "A {n}% deposit of the apartment price is paid when the pre-sale agreement is signed.",
"Plăți intermediare": "Interim payments",
"Pe parcursul construcției se pot efectua plăți suplimentare, conform graficului agreat.": "Additional payments can be made during construction, according to the agreed schedule.",
"Opțional": "Optional",
"Diferența la predare": "Balance on handover",
"Restul de plată se achită la finalizare, din surse proprii sau prin credit bancar.": "The remaining balance is paid on completion, from own funds or through a bank loan.",
"Prețuri apartamente": "Apartment prices",
"Calculator de rată și randament": "Mortgage and yield calculator",
"{n} — Proximitate": "{n} — Proximity",
"Tot orașul, la îndemână": "The whole city, within reach",
"din Păcurari": "from Păcurari",
"Hypermarket la un kilometru, universitățile și Copoul la sub cinci, centrul la nici zece minute. Locul de joacă și zona de fitness se află în incinta ansamblului.":
    "A hypermarket one kilometre away, the universities and Copou under five, the city centre in less than ten minutes. The playground and fitness area are inside the development.",
"min": "min",
"Stație de autobuz": "Bus stop",
"Șoseaua Păcurari": "Șoseaua Păcurari",
"pe jos": "on foot",
"Ieșire DN{n} spre Botoșani": "DN{n} exit towards Botoșani",
"{n} km": "{n} km",
"cu mașina": "by car",
"Grădina Botanică": "Botanical Garden",
"Paradis International College": "Paradis International College",
"{n} m · pe jos": "{n} m · on foot",
"În incinta ansamblului": "Inside the development",
"Zonă de fitness": "Fitness area",
"Kaufland Păcurari": "Kaufland Păcurari",
"Hypermarket, la {n} km": "Hypermarket, {n} km away",
"Mall Moldova": "Mall Moldova",
"Universitatea „Alexandru Ioan Cuza”": "“Alexandru Ioan Cuza” University",
"Parcul Copou": "Copou Park",
"Centrul orașului": "City centre",
"Piața Unirii, {n} km": "Piața Unirii, {n} km",
"Palas Mall": "Palas Mall",
"Puncte de interes": "Points of interest",
"Selectează un reper pentru afișarea traseului.": "Select a landmark to display the route.",
"Revenire la ansamblu": "Back to the development",
"Distanțe și timpi calculați pe traseu rutier, fără trafic (OpenStreetMap). Reper: Strada Dealul Zorilor.":
    "Distances and times calculated on the road route, without traffic (OpenStreetMap). Reference point: Strada Dealul Zorilor.",
"{n} — Amplasament": "{n} — Location",
"Apartamente Iași,": "Apartments in Iași,",
"zona": "the",
"Păcurari": "Păcurari area",
"La {n} km de centru și {n} km de Copou, într-una dintre cele mai căutate zone ale orașului.":
    "{n} km from the city centre and {n} km from Copou, in one of the most sought-after areas of the city.",
"{n} m": "{n} m",
"Aeroportul Iași": "Iași Airport",
"Distanțe rutiere calculate din Strada Dealul Zorilor (OpenStreetMap).": "Road distances calculated from Strada Dealul Zorilor (OpenStreetMap).",
"Căi de acces": "Access routes",
"Cu mașina": "By car",
"Din centru pe Șoseaua Păcurari, aproximativ {n} minute fără trafic. Acces final din Strada Ion Nistor.":
    "From the centre along Șoseaua Păcurari, about {n} minutes without traffic. Final access from Strada Ion Nistor.",
"Cu transportul public": "By public transport",
"Stații pe Șoseaua Păcurari, la câteva minute de mers pe jos.": "Stops on Șoseaua Păcurari, a few minutes' walk away.",
"Dinspre DN{n}": "From the DN{n}",
"Ieșirea spre Botoșani este la aproximativ {n} km, utilă pentru drumurile în afara orașului.": "The exit towards Botoșani is about {n} km away, convenient for trips out of town.",
"Ghidul zonei Păcurari": "Păcurari area guide",
"{n} — Întrebări": "{n} — Questions",
"Ce se întreabă": "Frequently asked",
"cel mai des": "questions",
"Pentru întrebări suplimentare, echipa de vânzări răspunde în aceeași zi lucrătoare.": "For further questions, the sales team replies on the same working day.",
"Unde este Emerald City?": "Where is Emerald City?",
"În Iași, zona Păcurari, cu acces din Strada Ion Nistor. Aproximativ {n} km până în centrul orașului și {n} km până în Copou.":
    "In Iași, Păcurari area, with access from Strada Ion Nistor. About {n} km to the city centre and {n} km to Copou.",
"Câte apartamente are ansamblul?": "How many apartments does the development have?",
"{n} de apartamente cu {n} {n} și {n} camere, în {n} blocuri, construite în trei etape: {n} în Etapa I, {n} în Etapa II și {n} în Etapa III.":
    "{n} apartments with {n}, {n} and {n} rooms, in {n} buildings, built in three phases: {n} in Phase I, {n} in Phase II and {n} in Phase III.",
"Ce suprafețe au apartamentele?": "What sizes are the apartments?",
"Între {n} și {n} m² suprafață utilă, cu balcon la fiecare apartament. Cele de la parter au curte proprie, între {n} și {n} m².":
    "Between {n} and {n} m² of usable area, with a balcony in every apartment. Ground-floor units have a private garden, between {n} and {n} m².",
"Ce înseamnă regim P+{n}E?": "What does GF+{n} mean?",
"Parter plus trei etaje. Toate cele {n} blocuri au același regim, cu înălțimea maximă de {n} metri. Sub ele se află două demisoluri, cu parcare și boxe.":
    "Ground floor plus three storeys. All {n} buildings have the same height, with a maximum of {n} metres. Below them are two basement levels, with parking and storage rooms.",
"Câte locuri de parcare sunt?": "How many parking spaces are there?",
"{n} în total: {n} subterane și {n} supraterane. Locul subteran se achiziționează separat.": "{n} in total: {n} underground and {n} at surface level. The underground space is purchased separately.",
"Finisajele sunt incluse în preț?": "Are the finishes included in the price?",
"Da. Apartamentul se predă finisat complet, cu materiale alese de un birou de design. Nu urmează o etapă suplimentară de amenajare.":
    "Yes. The apartment is handed over fully finished, with materials selected by a design studio. There is no additional fit-out stage.",
"Cum se face plata?": "How is payment made?",
"Avans de {n}% la semnarea antecontractului, diferența la predare, din surse proprii sau prin credit bancar. Plățile intermediare sunt opționale.":
    "A {n}% deposit when the pre-sale agreement is signed and the balance on handover, from own funds or through a bank loan. Interim payments are optional.",
"Se poate cumpăra cu credit ipotecar?": "Can I buy with a mortgage?",
"Da. Pe fiecare pagină de apartament există un calculator orientativ de rată. Documentația necesară băncii se pune la dispoziție de dezvoltator.":
    "Yes. Every apartment page has an indicative mortgage calculator. The documentation required by the bank is provided by the developer.",
"Există comision de intermediere?": "Is there an agency commission?",
"Nu. Vânzarea se face direct de la dezvoltator, Tala Sapphire S.R.L.": "No. Sales are made directly by the developer, Tala Sapphire S.R.L.",
"Pot vizita șantierul?": "Can I visit the construction site?",
"Da, cu programare. Publicăm lunar și stadiul lucrărilor, cu fotografii datate, în secțiunea Jurnal de șantier.":
    "Yes, by appointment. We also publish the construction progress monthly, with dated photos, in the Site diary section.",
"Următorul pas": "Next step",
"Vizionare la fața locului,": "A viewing on site,",
"înainte de decizie.": "before you decide.",
"Un consultant prezintă apartamentele disponibile, stadiul lucrărilor și condițiile de plată. Fără obligații contractuale și fără comision.":
    "A consultant presents the available apartments, the construction progress and the payment terms. No contractual obligations and no commission.",
"Răspundem în aceeași zi lucrătoare": "We reply on the same working day",
"Vizionare la fața locului sau online": "Viewing on site or online",
"Ofertă scrisă, cu preț final": "Written offer, with the final price",
"Telefon": "Phone",
"Scrie-ne acum": "Message us now",
"Data și ora, la alegere": "Date and time of your choice",
"Apartamente noi cu {n} {n} și {n} camere în Iași, zona Păcurari. {n} de locuințe, finisaje incluse, parc și parcare subterană. Direct de la dezvoltator.":
    "New apartments with {n}, {n} and {n} rooms in Iași, Păcurari area. {n} homes, finishes included, park and underground parking. Direct from the developer.",
"Living dintr-un apartament Emerald City": "Living room in an Emerald City apartment",
"Living cu perete de marmură și măslin în ghiveci": "Living room with a marble wall and a potted olive tree",
"Bucătărie cu blat și splash-back din marmură": "Kitchen with a marble worktop and splashback",
"Zonă de dining cu vedere spre grădină": "Dining area overlooking the garden",
"Hol de intrare cu consolă suspendată": "Entrance hall with a floating console",
"Living deschis spre zona de zi": "Living room opening onto the day area",
"Baie finisată cu marmură și alamă": "Bathroom finished in marble and brass",
"Dormitor cu tâmplărie până în tavan": "Bedroom with floor-to-ceiling windows",
"Spațiu comun în Emerald City": "Communal space at Emerald City",
"Zonă de zi cu acces spre curte": "Living area with access to the garden",
# ---- comune (showroom, formular, indemnuri, alerta) -----------------------
"{n} — Showroom": "{n} — Showroom",
"Vă așteptăm": "Visit us",
"în showroom": "at the showroom",
"Vizionarea apartamentului-model se face cu programare. O întâlnire durează aproximativ {n} de minute și include prezentarea planurilor și a disponibilității.":
    "The show apartment is viewed by appointment. A meeting takes about {n} minutes and includes a presentation of the floor plans and availability.",
"Indicații rutiere": "Directions",
"Adresă": "Address",
"Str. Dealul Zorilor {n} zona Păcurari, Iași": "Str. Dealul Zorilor {n}, Păcurari area, Iași",
"Program": "Opening hours",
"Luni–vineri {n} · Sâmbătă {n}": "Mon–Fri {n} · Sat {n}",
"E-mail": "E-mail",
"Aveți întrebări? Trimiteți-ne un mesaj": "Any questions? Send us a message",
"Un consultant analizează solicitarea și revine cu un răspuns în aceeași zi lucrătoare. Pentru o vizionare, menționați în mesaj intervalul orar care vă convine, iar programarea se confirmă telefonic.":
    "A consultant reviews your request and replies on the same working day. For a viewing, mention the time slot that suits you and the appointment will be confirmed by phone.",
"Nume": "Name",
"Mesaj": "Message",
"Trimite solicitarea": "Send request",
"Machetă de lucru — formularul nu trimite date.": "Working mock-up — the form does not send data.",
"Harta biroului de vânzări — Str. Dealul Zorilor {n} Iași": "Map of the sales office — Str. Dealul Zorilor {n}, Iași",
"Programați o vizionare": "Book a viewing",
"Apartamentul-model, planurile pe masă și lista de disponibilitate, într-o întâlnire de aproximativ {n} de minute. Programarea se confirmă telefonic, în aceeași zi lucrătoare.":
    "The show apartment, the floor plans on the table and the availability list, in a meeting of about {n} minutes. The appointment is confirmed by phone on the same working day.",
"Aveți nevoie de informații suplimentare?": "Need more information?",
"Un consultant transmite lista completă de disponibilitate, planurile detaliate ale fiecărei compartimentări și condițiile de plată, pe e-mail sau pe WhatsApp.":
    "A consultant sends the full availability list, the detailed floor plans of each layout and the payment terms, by e-mail or WhatsApp.",
"Cerere pe e-mail": "Request by e-mail",
"Adresă de e-mail": "E-mail address",
"Anunță-mă": "Notify me",
"adresa@exemplu.ro": "name@example.com",
"Etapa I": "Phase I", "Etapa II": "Phase II", "Etapa III": "Phase III",
"I": "I", "II": "II", "III": "III",
"Disponibil": "Available", "Rezervat": "Reserved", "Vândut": "Sold", "În curând": "Coming soon",
"Disponibilă": "Available", "Indisponibilă": "Not available",
"Da": "Yes", "Nu": "No",
"N": "N", "NE": "NE", "E": "E", "SE": "SE", "S": "S", "SV": "SW", "V": "W", "NV": "NW",
"Nord": "North", "Nord-est": "North-east", "Est": "East", "Sud-est": "South-east",
"Sud": "South", "Sud-vest": "South-west", "Vest": "West", "Nord-vest": "North-west",
"Cod": "Code", "Bloc": "Building", "Tip": "Type", "Suprafață": "Area", "Orientare": "Orientation",
"Preț": "Price", "Preț/m²": "Price/m²", "Stare": "Status",
"Etaj {n}": "Floor {n}",
"Living": "Living room", "Dormitor": "Bedroom", "Bucătărie": "Kitchen", "Baie": "Bathroom",
"Hol": "Hallway", "Debara": "Storage", "Birou": "Study", "Dining": "Dining", "Balcon": "Balcony",
"Curte": "Garden", "Boxă": "Storage room", "Vestibul": "Vestibule", "Dormitor {n}": "Bedroom {n}",
"Baie {n}": "Bathroom {n}", "Hol de intrare": "Entrance hall",
"de la {n} €": "from €{n}",
"{n} €": "€{n}",
"{n} €/m²": "€{n}/m²",
"{n} ani": "{n} years",
"{n} an": "{n} year",
"{n} luni": "{n} months",
"{n} de luni": "{n} months",
"{n} zile": "{n} days",
"{n} min": "{n} min",
"{n} ha": "{n} ha",
"{n}%": "{n}%",
"{n}D+P+{n}E": "{n}B+GF+{n}",
"Vezi lista": "See the list",
"Vezi": "View",
"Salvează": "Save",
"Salvat": "Saved",
"Cere detalii": "Ask for details",
"Sună": "Call",
"Duminica biroul este închis.": "The office is closed on Sundays.",
}
