# -*- coding: utf-8 -*-
# Despre noi, Proiect, Stadiul lucrarilor, Amplasament (zona).
T = {
# ---- despre noi -----------------------------------------------------------
"Despre Emerald City — finisaje și garanții | Iași": "About Emerald City — finishes and warranties | Iași",
"Un cartier construit ca să rămână": "A neighbourhood built to last",
"{n} de apartamente pe cinci hectare în Iași, zona Păcurari, ridicate în blocuri de patru niveluri, cu aproape o treime din teren lăsată spațiu verde. Se predau complet finisate, direct de la dezvoltator.":
    "{n} apartments on five hectares in Iași, Păcurari area, built in four-storey buildings, with almost a third of the land kept as green space. Handed over fully finished, direct from the developer.",
"Dotări incluse": "Included features",
"Viziune": "Vision", "Garanții": "Warranties", "Documente": "Documents", "Proces": "Process",
"Comparație": "Comparison", "Experiență": "Track record", "Dotări": "Features", "Întrebări": "Questions", "Birou": "Showroom",
"{n} — Viziunea": "{n} — The vision",
"Densitate mică,": "Low density,",
"spațiu de trăit": "room to live",
"Regimul de înălțime și densitatea determină calitatea locuirii pe termen lung.": "Building height and density determine the quality of living in the long run.",
"Ansamblul este dezvoltat pe orizontală, nu pe verticală. Cele {n} blocuri au parter și trei etaje, cu înălțimea maximă de {n} metri. Consecințele sunt măsurabile: iluminare naturală inclusiv la parter, număr redus de apartamente pe scară, încărcare mică a lifturilor și distanțe generoase între clădiri.":
    "The development spreads horizontally, not vertically. The {n} buildings have a ground floor and three storeys, with a maximum height of {n} metres. The consequences are measurable: natural light even on the ground floor, few apartments per staircase, light lift usage and generous distances between buildings.",
"Din cele {n} m² de teren, {n} m² sunt spațiu verde amenajat, adică {n}%. Suprafața cuprinde alei, parc, locuri de joacă și piste de biciclete, prevăzute din planul de ansamblu. Parcarea este asigurată cu {n} de locuri, dintre care {n} subterane, astfel încât circulația auto să nu ocupe spațiile pietonale.":
    "Of the {n} m² of land, {n} m² is landscaped green space, i.e. {n}%. It includes paths, a park, playgrounds and cycle lanes, all part of the master plan. Parking is provided with {n} spaces, {n} of them underground, so that cars do not take over the pedestrian areas.",
"Apartamentele se predau complet finisate, cu încălzire în pardoseală și tâmplărie performantă. Cele de la parter au curte proprie, iar toate au balcon. Vânzarea se face direct, fără comision de intermediere.":
    "Apartments are handed over fully finished, with underfloor heating and high-performance windows. Ground-floor units have a private garden and all have a balcony. Sales are direct, with no agency commission.",
"Ce înseamnă": "What",
"predare la cheie": "turnkey handover means",
"{n} poziții incluse în preț, montate și garantate. Specificațiile complete sunt pe pagina de finisaje.": "{n} items included in the price, installed and guaranteed. Full specifications are on the finishes page.",
"Centrală în condensație": "Condensing boiler",
"Termosistem de fațadă": "External wall insulation",
"Tâmplărie PVC cu {n} camere": "{n}-chamber PVC windows",
"Parchet laminat de {n} mm": "{n} mm laminate flooring",
"Grupuri sanitare complet finisate": "Fully finished bathrooms",
"Instalație electrică completă": "Complete electrical installation",
"Pereți finisați": "Finished walls",
"Uși interioare montate": "Interior doors fitted",
"Videointerfon": "Video intercom",
"Fișa tehnică completă": "Full technical sheet",
"{n} — Garanții": "{n} — Warranties",
"Ce garantăm și": "What we guarantee",
"pe ce temei": "and on what basis",
"Garanțiile sunt obligații legale. Termenele și temeiul normativ, în tabelul de mai jos.": "Warranties are legal obligations. Terms and legal basis in the table below.",
"Ce este garantat": "What is covered", "Cât timp": "For how long", "Temei": "Basis",
"Structura de rezistență": "Load-bearing structure",
"Toată durata de existență a clădirii": "For the whole life of the building",
"Legea {n}/{n} privind calitatea în construcții": "Law {n}/{n} on quality in construction",
"Vicii ascunse ale construcției": "Hidden construction defects",
"{n} ani de la recepția finală": "{n} years from final acceptance",
"Legea {n}/{n} și Codul civil": "Law {n}/{n} and the Civil Code",
"Vicii aparente": "Apparent defects",
"{n} an de la predare": "{n} year from handover",
"Codul civil": "Civil Code",
"Instalații și echipamente": "Installations and equipment",
"Conform garanției fiecărui producător": "According to each manufacturer's warranty",
"Certificatele predate la recepție": "Certificates handed over at acceptance",
"Finisaje și dotări": "Finishes and fittings",
"Conform anexei tehnice a contractului": "According to the technical annex of the contract",
"Contractul de vânzare": "Sale contract",
"{n} — Documente": "{n} — Documents",
"Documente predate": "Documents handed over",
"odată cu cheile": "with the keys",
"Documentele predate odată cu apartamentul, la recepție și la intabulare.": "The documents handed over with the apartment, at acceptance and at land registration.",
"Autorizația de construire": "Building permit",
"Emisă de autoritatea locală, împreună cu certificatul de urbanism care a stat la baza proiectului.": "Issued by the local authority, together with the urban planning certificate on which the project was based.",
"Cartea tehnică a construcției": "Building technical book",
"Dosarul complet al clădirii: proiectul, avizele, procesele-verbale și instrucțiunile de exploatare.": "The building's complete file: the design, permits, acceptance reports and operating instructions.",
"Procesul-verbal de recepție": "Acceptance report",
"Documentul care consemnează predarea clădirii, semnat de comisia de recepție.": "The document recording the building's handover, signed by the acceptance committee.",
"Documentația cadastrală": "Cadastral documentation",
"Măsurătorile și planurile apartamentului, depuse pentru înscrierea în cartea funciară.": "The apartment's measurements and plans, filed for registration in the land book.",
"Extrasul de carte funciară": "Land book extract",
"Dovada intabulării pe numele cumpărătorului, cu suprafețele și cotele indivize.": "Proof of registration in the buyer's name, with areas and undivided shares.",
"Certificatul de performanță energetică": "Energy performance certificate",
"Clasa energetică a apartamentului și consumul estimat, calculate de un auditor autorizat.": "The apartment's energy class and estimated consumption, calculated by a certified auditor.",
"{n} — Proces": "{n} — Process",
"De la vizionare": "From viewing",
"la chei": "to keys",
"{n} pași, cu operațiunile și documentele aferente fiecăruia.": "{n} steps, with the operations and documents for each.",
"Vizionare": "Viewing",
"Prezentarea amplasamentului și a apartamentului-model, împreună cu lista de disponibilitate, cu prețuri și suprafețe.": "Presentation of the site and the show apartment, together with the availability list, prices and areas.",
"Aceeași zi": "Same day",
"Rezervare": "Reservation",
"Apartamentul ales se blochează pe numele cumpărătorului, iar prețul se menține pe perioada rezervării.": "The chosen apartment is held in the buyer's name and the price is maintained for the reservation period.",
"Antecontract": "Pre-sale agreement",
"Antecontractul se semnează la notar, cu un avans de {n}%. Suprafețele, prețul și termenul de predare se fixează în contract.": "The pre-sale agreement is signed before a notary, with a {n}% deposit. Areas, price and handover date are fixed in the contract.",
"La notar": "At the notary",
"Construcție": "Construction",
"Progresul poate fi urmărit în jurnalul de șantier, actualizat lunar cu fotografii datate din teren.": "Progress can be followed in the site diary, updated monthly with dated site photos.",
"Conform etapei": "Per phase",
"Recepție și chei": "Acceptance and keys",
"Apartamentul se verifică împreună cu un reprezentant, se semnează contractul final, se efectuează intabularea și se predau cheile.": "The apartment is inspected with a representative, the final contract is signed, the land registration is completed and the keys are handed over.",
"La finalizare": "On completion",
"{n} — Comparație": "{n} — Comparison",
"Apartament nou": "New apartment",
"sau bloc vechi": "or old building",
"Diferența de preț pe metru pătrat se compensează prin costurile de exploatare și prin lucrările care nu mai sunt necesare.": "The price difference per square metre is offset by running costs and by the works that are no longer needed.",
"Criteriu": "Criterion",
"Apartament vechi": "Old apartment",
"Costul lunar cu încălzirea": "Monthly heating cost",
"Redus — termosistem continuu, centrală în condensație, încălzire în pardoseală": "Low — continuous insulation, condensing boiler, underfloor heating",
"Ridicat — izolație parțială, distribuție veche": "High — partial insulation, old distribution",
"Starea instalațiilor": "Condition of installations",
"Noi, cu garanție și carte tehnică": "New, with warranty and technical book",
"Vechi de {n} de ani, adesea de înlocuit": "{n} years old, often needing replacement",
"Finisajele": "Finishes",
"Incluse în preț, montate și garantate": "Included in the price, installed and guaranteed",
"De refăcut integral, cost separat": "To be fully redone, at extra cost",
"Parcarea": "Parking",
"Loc propriu, subteran sau la suprafață": "Own space, underground or at surface level",
"Nealocată, ocupată în ordinea sosirii": "Unallocated, first come first served",
"Structura": "Structure",
"Proiectată la normele antiseismice actuale": "Designed to current seismic standards",
"Conform normelor din anul construcției": "To the standards of the year it was built",
"Spațiul verde": "Green space",
"{n} m² amenajați, {n}% din teren": "{n} m² landscaped, {n}% of the land",
"Variabil, de regulă neamenajat": "Variable, usually not landscaped",
"Actele": "Paperwork",
"Intabulare directă de la dezvoltator, fără istoric": "Direct registration from the developer, no history",
"Verificări de istoric, posibile litigii sau moșteniri": "History checks, possible disputes or inheritances",
"Comisionul": "Commission",
"Zero — vânzare directă de la dezvoltator": "Zero — direct sale by the developer",
"De regulă {n}% pentru agenție": "Usually {n}% for the agency",
"{n} — Direct dezvoltator": "{n} — Direct from the developer",
"Avantajele": "The advantages",
"achiziției directe": "of buying direct",
"Patru diferențe verificabile.": "Four verifiable differences.",
"Zero comision": "Zero commission",
"Fără comision de agenție de {n}%. Prețul afișat este prețul din actul notarial.": "No {n}% agency commission. The listed price is the price in the notarial deed.",
"Lista completă": "The full list",
"Toate cele {n} de apartamente sunt afișate, cu preț, suprafață, etaj și orientare.": "All {n} apartments are listed, with price, area, floor and orientation.",
"Contract direct": "Direct contract",
"Termenele și etapele de plată se stabilesc direct cu dezvoltatorul, fără intermediar.": "Deadlines and payment stages are agreed directly with the developer, without an intermediary.",
"Progres verificabil": "Verifiable progress",
"Publicăm lunar stadiul lucrărilor, cu fotografii datate din teren.": "We publish the construction progress monthly, with dated site photos.",
"{n} — Experiență": "{n} — Track record",
"Proiecte": "Projects",
"livrate anterior": "delivered before",
"Emerald City este dezvoltat de Tala Sapphire S.R.L., companie din Green Stone Group. În Iași, grupul dezvoltă și ansamblurile de mai jos.": "Emerald City is developed by Tala Sapphire S.R.L., a Green Stone Group company. In Iași, the group is also developing the projects below.",
"Iași": "Iași",
"Lapis Residence": "Lapis Residence",
"Ansamblu al Green Stone Group, cu piste de biciclete în tot cartierul, panouri fotovoltaice și finisaje premium. Proiectul a început la finalul lui {n}": "A Green Stone Group development with cycle lanes throughout the neighbourhood, photovoltaic panels and premium finishes. The project started at the end of {n}.",
"Oraș": "City", "Predare": "Handover", "La cheie": "Turnkey",
"Onyx Residence": "Onyx Residence",
"Prelungirea ansamblului Lapis: {n} de apartamente în {n} blocuri, cu spații comerciale la parter. Împreună, cele două ajung la {n} de locuințe.": "The extension of Lapis: {n} apartments in {n} buildings, with commercial units on the ground floor. Together, the two reach {n} homes.",
"Portofoliul complet al grupului": "The group's full portfolio",
"{n} — Verifică": "{n} — Check",
"Criterii de verificare a unui dezvoltator": "How to check a developer",
"Criteriile de mai jos permit verificarea oricărui proiect rezidențial înainte de semnarea unui antecontract.": "The criteria below allow any residential project to be checked before signing a pre-sale agreement.",
"Autorizația de construire, cu numărul și data emiterii": "The building permit, with its number and issue date",
"Certificatul de urbanism și indicatorii aprobați: POT și CUT": "The urban planning certificate and the approved indicators: site coverage and floor area ratio",
"Situația juridică a terenului și extrasul de carte funciară": "The legal status of the land and the land book extract",
"Anexa tehnică de finisaje, poziție cu poziție": "The technical annex of finishes, item by item",
"Termenul de predare scris în antecontract, nu spus verbal": "The handover date written in the pre-sale agreement, not promised verbally",
"Proiecte livrate anterior, care pot fi vizitate": "Previously delivered projects that can be visited",
"Cine execută structura și cine verifică proiectul": "Who builds the structure and who checks the design",
"Datele proiectului": "Project data",
"{n} — Dotări": "{n} — Features",
"și facilități": "and amenities",
"Dotările locuinței și facilitățile de folosință comună.": "The home's features and the shared amenities.",
"În apartament": "In the apartment",
"Incluse în preț": "Included in the price",
"Încălzire în pardoseală în toate camerele": "Underfloor heating in every room",
"Centrală proprie în condensație": "Own condensing boiler",
"Tâmplărie PVC cu {n} camere și geam tripan": "{n}-chamber PVC windows with triple glazing",
"Parchet laminat de {n} mm, trafic intens": "{n} mm laminate flooring, heavy-traffic grade",
"Grup sanitar complet finisat și echipat": "Fully finished and equipped bathroom",
"Instalație electrică cu aparataj montat": "Electrical installation with fittings installed",
"Uși interioare montate, ușă metalică la intrare": "Interior doors fitted, metal entrance door",
"Balcon la fiecare apartament": "A balcony in every apartment",
"Curte proprie la parter, între {n} și {n} m²": "Private garden on the ground floor, between {n} and {n} m²",
"În cartier": "In the neighbourhood",
"Folosință comună": "Shared use",
"Parc și spații verzi pe {n} m²": "Park and green spaces over {n} m²",
"{n} de locuri de parcare, {n} subterane": "{n} parking spaces, {n} underground",
"Preechipare pentru stații de încărcare auto": "Pre-wiring for EV charging stations",
"Lifturi în fiecare bloc": "Lifts in every building",
"Spații comerciale la parter": "Commercial units on the ground floor",
"Despre dezvoltator,": "About the developer,",
"calitate și garanții": "quality and warranties",
"{n} întrebări la care răspundem cel mai des, cu cifre și termene concrete.": "The {n} questions we answer most often, with concrete figures and deadlines.",
"Cine dezvoltă Emerald City?": "Who is developing Emerald City?",
"Tala Sapphire S.R.L., companie din Green Stone Group. Vânzarea se face direct de la dezvoltator, fără comision de intermediere.": "Tala Sapphire S.R.L., a Green Stone Group company. Sales are made directly by the developer, with no agency commission.",
"Ce experiență are dezvoltatorul?": "What experience does the developer have?",
"Emerald City este dezvoltat de Tala Sapphire S.R.L., companie din Green Stone Group — un grup cu proiecte în Marea Britanie, Israel și România. În Iași, grupul dezvoltă și ansamblurile Lapis și Onyx Residence, iar în Sibiu a livrat faza I de la Magnolia Residence, cu {n} de apartamente.":
    "Emerald City is developed by Tala Sapphire S.R.L., a Green Stone Group company — a group with projects in the United Kingdom, Israel and Romania. In Iași the group is also developing Lapis and Onyx Residence, and in Sibiu it delivered phase I of Magnolia Residence, with {n} apartments.",
"Ce garanție am pentru structura clădirii?": "What warranty do I have for the building's structure?",
"Structura de rezistență este garantată pe toată durata de existență a clădirii, conform Legii {n}/{n} privind calitatea în construcții.": "The load-bearing structure is guaranteed for the whole life of the building, under Law {n}/{n} on quality in construction.",
"Cât timp răspunde dezvoltatorul pentru vicii ascunse?": "How long is the developer liable for hidden defects?",
"{n} ani de la recepția finală, conform Legii {n}/{n} și Codului civil. Viciile aparente se semnalează în primul an de la predare.": "{n} years from final acceptance, under Law {n}/{n} and the Civil Code. Apparent defects are reported within the first year after handover.",
"Ce documente primesc la predare?": "What documents do I receive at handover?",
"Procesul-verbal de recepție, cartea tehnică a construcției, documentația cadastrală, extrasul de carte funciară cu intabularea pe numele cumpărătorului și certificatul de performanță energetică.": "The acceptance report, the building technical book, the cadastral documentation, the land book extract with registration in the buyer's name and the energy performance certificate.",
"Apartamentele se predau finisate?": "Are the apartments handed over finished?",
"Da, complet finisate. Parchet, gresie și faianță montate, grupuri sanitare echipate, pereți gletuiți și vopsiți, uși montate, instalație electrică cu aparataj, încălzire în pardoseală. Apartamentul este gata de mobilat la data recepției.":
    "Yes, fully finished. Flooring and tiles laid, bathrooms equipped, walls skimmed and painted, doors fitted, electrical installation with fittings, underfloor heating. The apartment is ready to furnish on the acceptance date.",
"Ce înseamnă centrală în condensație?": "What is a condensing boiler?",
"Recuperează căldura din gazele de ardere în loc să o evacueze pe horn. La același confort, consumă până la {n}% mai puțin gaz decât o centrală clasică.": "It recovers heat from the flue gases instead of venting it through the chimney. For the same comfort, it uses up to {n}% less gas than a conventional boiler.",
"Ce avantaj are încălzirea în pardoseală?": "What is the advantage of underfloor heating?",
"Căldura se distribuie uniform de la sol în sus, fără calorifere pe pereți, și funcționează la temperatură joasă, deci consumă mai puțin. În plus, pereții rămân liberi pentru mobilier.": "Heat spreads evenly from the floor up, with no radiators on the walls, and runs at low temperature, so it uses less energy. Walls also stay free for furniture.",
"De ce să cumpăr direct de la dezvoltator?": "Why buy directly from the developer?",
"Nu se percepe comision de intermediere, prețul și termenele se stabilesc direct cu dezvoltatorul, lista de disponibilitate este publică, iar stadiul lucrărilor poate fi urmărit lunar.": "No agency commission is charged, price and deadlines are agreed directly with the developer, the availability list is public and construction progress can be followed monthly.",
"Ce avans se cere la antecontract?": "What deposit is required at the pre-sale agreement?",
"{n}% din preț la semnarea antecontractului la notar, iar diferența la predare. Etapele de plată se stabilesc în contract.": "{n}% of the price when the pre-sale agreement is signed before the notary, and the balance on handover. Payment stages are set in the contract.",
"Pot cumpăra cu credit ipotecar?": "Can I buy with a mortgage?",
"Da. Apartamentele se pot achiziționa cu credit ipotecar standard, iar cele care se încadrează în plafonul programului pot fi cumpărate și prin Noua Casă. Echipa de vânzări prezintă varianta potrivită fiecărui buget.":
    "Yes. Apartments can be bought with a standard mortgage, and those within the programme's ceiling can also be bought through the Noua Casă scheme. The sales team presents the option suited to each budget.",
"Prețurile includ TVA?": "Do prices include VAT?",
"Da, prețurile afișate includ TVA.": "Yes, the listed prices include VAT.",
"Ce dotări are cartierul?": "What amenities does the neighbourhood have?",
"Piste de biciclete, zone de fitness, locuri de joacă, parcări private, preechipare pentru stații de încărcare auto, lifturi, panouri fotovoltaice, spații verzi și parc, colectare îngropată a deșeurilor.":
    "Cycle lanes, fitness areas, playgrounds, private parking, pre-wiring for EV charging stations, lifts, photovoltaic panels, green spaces and a park, underground waste collection.",
"Cât spațiu verde are ansamblul?": "How much green space does the development have?",
"{n} m² de spațiu verde amenajat, adică {n}% din suprafața terenului de {n} m². Procentul de ocupare a terenului este {n}%, iar coeficientul de utilizare {n}": "{n} m² of landscaped green space, i.e. {n}% of the {n} m² plot. Site coverage is {n}% and the floor area ratio is {n}.",
"Când se finalizează ansamblul?": "When will the development be completed?",
"Construcția este împărțită în trei etape: {n} de apartamente în Etapa I, {n} în Etapa II și {n} în Etapa III. Termenul fiecărei etape se confirmă în contract.": "Construction is split into three phases: {n} apartments in Phase I, {n} in Phase II and {n} in Phase III. Each phase's deadline is confirmed in the contract.",
"Unde este biroul de vânzări?": "Where is the sales office?",
"Str. Dealul Zorilor {n} zona Păcurari, Iași. Program: luni–vineri {n} și sâmbătă {n} Telefon {n} {n} {n} {n}": "Str. Dealul Zorilor {n}, Păcurari area, Iași. Opening hours: Mon–Fri {n} and Sat {n}. Phone {n} {n} {n} {n}.",
"Ce include predarea la cheie, ce garanții și ce documente se predau. {n} de apartamente în Iași, zona Păcurari, direct de la dezvoltator.": "What turnkey handover includes, which warranties apply and which documents are handed over. {n} apartments in Iași, Păcurari area, direct from the developer.",
"Interior de apartament finisat la Emerald City": "Finished apartment interior at Emerald City",
"Hol de acces într-un bloc Emerald City": "Entrance hall in an Emerald City building",
# ---- proiect --------------------------------------------------------------
"Proiectul Emerald City — {n} de apartamente în {n} blocuri | Iași": "The Emerald City project — {n} apartments in {n} buildings | Iași",
"{n} blocuri, nu {n} turnuri": "{n} buildings, not {n} towers",
"Aceeași suprafață construită se poate obține din câteva turnuri sau din {n} blocuri de patru niveluri. A doua variantă consumă mai mult teren, dar modifică decisiv iluminarea naturală, nivelul de zgomot și distanțele dintre fațade.":
    "The same built area could come from a few towers or from {n} four-storey buildings. The second option uses more land, but decisively changes natural light, noise levels and the distances between façades.",
"Regimul de înălțime": "Building height",
"Suprafață teren": "Plot area",
"Etape de construcție": "Construction phases",
"{n} — Concept": "{n} — Concept",
"De ce": "Why",
"patru niveluri": "four storeys",
"Regimul de înălțime se stabilește o singură dată, la autorizare, și determină calitatea locuirii pe toată durata de exploatare.": "Building height is set once, at permitting, and determines the quality of living for the whole life of the development.",
"Un ansamblu de {n} de apartamente poate fi dezvoltat în patru turnuri sau în {n} blocuri cu regim {n}D+P+{n}E. Prima variantă consumă mai puțin teren și are costuri mai mici. A fost aleasă a doua.":
    "A development of {n} apartments can be built as four towers or as {n} buildings of {n}B+GF+{n}. The first option uses less land and costs less. The second was chosen.",
"Consecințele sunt măsurabile. Numărul redus de apartamente pe scară limitează încărcarea lifturilor și a spațiilor comune. Înălțimea mică a clădirilor reduce umbrirea reciprocă, astfel încât iluminarea naturală ajunge inclusiv la parter. Distanțele dintre blocuri depășesc minimul impus de normativ.":
    "The consequences are measurable. Few apartments per staircase limit the load on lifts and common areas. The low building height reduces mutual shading, so natural light reaches even the ground floor. Distances between buildings exceed the regulatory minimum.",
"Cele două demisoluri preiau parcarea și depozitarea, astfel încât spațiul dintre blocuri rămâne destinat aleilor, parcului și locurilor de joacă. {n} dintre apartamentele de la parter au curte proprie, între {n} și {n} m².":
    "The two basement levels take the parking and storage, so the space between buildings is kept for paths, the park and playgrounds. {n} of the ground-floor apartments have a private garden, between {n} and {n} m².",
"{n} — Regim de înălțime": "{n} — Building height",
"Distribuția": "Distribution",
"pe niveluri": "by level",
"{n}D+P+{n}E, cu aticul la {n} m. Același regim la toate cele {n} blocuri, fără excepții și fără etaje retrase.": "{n}B+GF+{n}, with the parapet at {n} m. The same height for all {n} buildings, with no exceptions and no set-back floors.",
"Secțiune schematică · cotele sunt orientative": "Schematic section · dimensions are indicative",
"Terasă tehnică": "Technical roof",
"Atic la cota maximă aprobată. Panourile fotovoltaice și echipamentele de instalații stau aici, nu pe fațadă.": "Parapet at the maximum approved height. Photovoltaic panels and building services equipment sit here, not on the façade.",
"Etajul {n}": "Floor {n}",
"Ultimul nivel locuibil, fără apartament deasupra.": "The top residential level, with no apartment above.",
"Nivel curent, cu apartamente de {n} {n} și {n} camere pe același palier.": "Standard level, with {n}, {n} and {n}-room apartments on the same landing.",
"Nivel curent. Distanțele dintre blocuri permit iluminare naturală pe două laturi.": "Standard level. Distances between buildings allow natural light from two sides.",
"Parterul": "Ground floor",
"Apartamentele de aici au curte proprie, între {n} și {n} m². La blocurile {n} și {n} parterul găzduiește spațiile comerciale.": "Apartments here have a private garden, between {n} and {n} m². In buildings {n} and {n} the ground floor houses the commercial units.",
"±{n} m": "±{n} m",
"Demisolul {n}": "Basement {n}",
"Parcare subterană și accesul cu liftul direct din parcaj în scară.": "Underground parking, with lift access straight from the car park to the staircase.",
"−{n} m": "−{n} m",
"Boxe de depozitare și spațiile tehnice ale blocului.": "Storage rooms and the building's technical spaces.",
"{n} — Bilanțul terenului": "{n} — Land balance",
"Cum se împart": "How the",
"cele {n} hectare": "{n} hectares are divided",
"{n} m² în total. Spațiul verde amenajat depășește amprenta construită la sol — raport pe care puține ansambluri noi din Iași îl au.": "{n} m² in total. Landscaped green space exceeds the built footprint — a ratio few new developments in Iași can claim.",
"{n}% din teren": "{n}% of the land",
"Construit la sol — Amprenta celor {n} blocuri. Procentul de ocupare a terenului aprobat este de {n}%.": "Built footprint — The footprint of the {n} buildings. The approved site coverage is {n}%.",
"Spațiu verde amenajat — Parc, alei, locuri de joacă și zonele verzi dintre blocuri. Nu este teren rămas liber, ci suprafață proiectată.": "Landscaped green space — Park, paths, playgrounds and the green areas between buildings. Not leftover land, but designed space.",
"Circulații și parcaje — Drumurile de incintă, cele {n} de locuri de parcare la suprafață și platformele tehnice.": "Roads and parking — Internal roads, the {n} surface parking spaces and technical platforms.",
"POT aprobat": "Approved site coverage",
"CUT aprobat": "Approved floor area ratio",
"Înălțime maximă": "Maximum height",
"{n} — Etape": "{n} — Phases",
"Ansamblul se ridică": "The development rises",
"în trei etape": "in three phases",
"Fiecare etapă se finalizează și se predă independent, cu spațiile verzi aferente amenajate, nu lăsate pentru final.": "Each phase is completed and handed over independently, with its green spaces landscaped, not left for the end.",
"Blocurile {n}": "Buildings {n}",
"Blocuri": "Buildings",
"Din ansamblu": "Of the development",
"Include spațiul comercial de la parterul blocului {n}": "Includes the commercial unit on the ground floor of building {n}",
"Cea mai mare etapă, cu acces direct la parcul central.": "The largest phase, with direct access to the central park.",
"Blocurile cu perspectiva cea mai deschisă spre oraș.": "The buildings with the most open views towards the city.",
"{n} — Apartamente": "{n} — Apartments",
"cele {n} de locuințe": "the {n} homes",
"{n} compartimentări, de la garsonieră la {n} camere cu două grupuri sanitare. Fiecare apartament are balcon.": "{n} layouts, from studio to {n} rooms with two bathrooms. Every apartment has a balcony.",
"{n}% din total": "{n}% of the total",
"{n} — Parcare și depozitare": "{n} — Parking and storage",
"{n} de locuri,": "{n} spaces,",
"{n} sub clădiri": "{n} under the buildings",
"Parcarea subterană este prevăzută din proiect, cu acces direct cu liftul din parcaj în scară.": "Underground parking is part of the design, with lift access straight from the car park to the staircase.",
"{n} locuri subterane": "{n} underground spaces",
"În primul demisol al fiecărui bloc, cu acces cu liftul direct în scară.": "On the first basement level of every building, with lift access straight to the staircase.",
"{n} locuri la suprafață": "{n} surface spaces",
"În incintă, de-a lungul drumurilor interioare, separate de zonele de joacă.": "Within the development, along the internal roads, separated from the play areas.",
"Boxe de depozitare": "Storage rooms",
"În al doilea demisol, pentru bagaje, biciclete și lucrurile de sezon.": "On the second basement level, for luggage, bicycles and seasonal items.",
"Preechipare pentru încărcare": "Pre-wiring for charging",
"Traseele electrice sunt pregătite din construcție pentru stații de încărcare auto.": "Electrical routes are prepared during construction for EV charging stations.",
"{n} — Spații comerciale": "{n} — Commercial units",
"la parter": "on the ground floor",
"Două spații comerciale în incintă, destinate serviciilor de proximitate.": "Two commercial units within the development, intended for local services.",
"Blocul {n}": "Building {n}",
"Total comercial": "Total commercial",
"Amplasare": "Position",
"La parter, cu acces din incintă": "On the ground floor, accessed from within the development",
"{n} — Documentație": "{n} — Documentation",
"și echipa": "and team",
"Datele de autorizare. Documentele pot fi consultate la biroul de vânzări.": "Permitting data. The documents can be consulted at the sales office.",
"Fază": "Phase", "D.T.A.C.": "Building permit design", "Data": "Date",
"Certificat de urbanism": "Urban planning certificate",
"Proiectant": "Designer",
"S.C. C.A.D. S.R.L., Iași": "S.C. C.A.D. S.R.L., Iași",
"Șef de proiect": "Lead architect",
"arh. Ovidiu M. Murgu": "arch. Ovidiu M. Murgu",
"Beneficiar": "Client",
"Tala Sapphire S.R.L.": "Tala Sapphire S.R.L.",
"Regim de înălțime": "Building height",
"Garanții și documente predate": "Warranties and documents handed over",
"Despre proiect": "About the project",
"și indicatori": "and indicators",
"{n} întrebări despre cum este gândit ansamblul, cu cifrele din documentație.": "{n} questions about how the development is designed, with figures from the documentation.",
"Ce regim de înălțime au blocurile?": "How tall are the buildings?",
"{n}D+P+{n}E: două demisoluri, parter și trei etaje. Înălțimea maximă la atic este de {n} metri, aceeași pentru toate cele {n} blocuri.": "{n}B+GF+{n}: two basement levels, ground floor and three storeys. The maximum parapet height is {n} metres, the same for all {n} buildings.",
"Ce se află în cele două demisoluri?": "What is on the two basement levels?",
"Primul demisol găzduiește parcarea subterană, cu {n} de locuri și acces cu liftul direct în scară. Al doilea demisol cuprinde boxele de depozitare și spațiile tehnice.": "The first basement level houses the underground car park, with {n} spaces and lift access straight to the staircase. The second holds the storage rooms and technical spaces.",
"Ce înseamnă POT {n}% și CUT {n}?": "What do site coverage {n}% and floor area ratio {n} mean?",
"POT este procentul din teren pe care se poate construi la sol: {n}% din cele {n} m², adică aproximativ {n} m². CUT este raportul dintre suprafața desfășurată și suprafața terenului; {n} este valoarea aprobată pentru acest amplasament.":
    "Site coverage is the share of the plot that can be built on at ground level: {n}% of the {n} m², i.e. about {n} m². The floor area ratio is the total floor area divided by the plot area; {n} is the value approved for this site.",
"{n} m², adică {n}% din suprafața terenului — mai mult decât amprenta construită la sol.": "{n} m², i.e. {n}% of the plot — more than the built footprint.",
"În câte etape se construiește?": "In how many phases is it built?",
"În trei: {n} blocuri și {n} de apartamente în Etapa I, {n} blocuri și {n} de apartamente în Etapa II, {n} blocuri și {n} de apartamente în Etapa III.": "Three: {n} buildings and {n} apartments in Phase I, {n} buildings and {n} apartments in Phase II, {n} buildings and {n} apartments in Phase III.",
"{n} în total: {n} subterane, în primul demisol, și {n} la suprafață, în incintă.": "{n} in total: {n} underground, on the first basement level, and {n} at surface level within the development.",
"Ce spații comerciale sunt prevăzute?": "What commercial units are planned?",
"Două, la parterul blocurilor {n} și {n}: {n} m² și {n} m², în total {n} m².": "Two, on the ground floor of buildings {n} and {n}: {n} m² and {n} m², {n} m² in total.",
"Cine a proiectat ansamblul?": "Who designed the development?",
"Proiectul {n}/{n} faza D.T.A.C., a fost întocmit de S.C. C.A.D. S.R.L. din Iași, cu arh. Ovidiu M. Murgu ca șef de proiect, pentru beneficiarul Tala Sapphire S.R.L.": "Design {n}/{n}, building permit stage, was prepared by S.C. C.A.D. S.R.L. of Iași, with arch. Ovidiu M. Murgu as lead architect, for the client Tala Sapphire S.R.L.",
"Pot vedea documentația de autorizare?": "Can I see the permitting documentation?",
"Da. Autorizația de construire, certificatul de urbanism și planșele pot fi consultate la biroul de vânzări, la cerere.": "Yes. The building permit, the urban planning certificate and the drawings can be consulted at the sales office, on request.",
"Fiecare bloc are lift?": "Does every building have a lift?",
"Da. Toate cele {n} blocuri au lift, care coboară până în primul demisol, unde se află parcarea subterană, astfel încât accesul din parcaj în scară se face direct.": "Yes. All {n} buildings have a lift that goes down to the first basement level, where the underground car park is, so access from the car park to the staircase is direct.",
"Ansamblul Emerald City din Iași: {n} blocuri cu regim {n}D+P+{n}E, {n} de apartamente, {n} hectare, indicatori urbanistici și etape.": "The Emerald City development in Iași: {n} buildings of {n}B+GF+{n}, {n} apartments, {n} hectares, planning indicators and phases.",
"Apartament finisat în ansamblul Emerald City": "Finished apartment in the Emerald City development",
# ---- stadiu lucrari -------------------------------------------------------
"Stadiul lucrărilor — jurnal de șantier | Emerald City Iași": "Construction progress — site diary | Emerald City Iași",
"Unde s-a ajuns, lună de lună": "Where we are, month by month",
"Publicăm stadiul fiecărei etape, faza cu faza, împreună cu fotografii datate din teren, astfel încât progresul să poată fi verificat independent.": "We publish the status of each phase, stage by stage, together with dated site photos, so progress can be verified independently.",
"Stadiul pe etape": "Status by phase",
"Programare vizită": "Book a visit",
"Stadiu general": "Overall status",
"Etapa în execuție": "Phase under construction",
"Septembrie": "September",
"Ultima actualizare": "Last update",
"{n} — Stadiu pe etape": "{n} — Status by phase",
"Fiecare etapă,": "Each phase,",
"faza cu faza": "stage by stage",
"{n} faze de execuție, de la terasamente la amenajări exterioare. Procentul general este media ponderată a fazelor, cu ponderile uzuale pentru locuințe colective.": "{n} construction stages, from earthworks to external landscaping. The overall percentage is the weighted average of the stages, using the usual weights for apartment buildings.",
"Stadiu": "Status",
"{n} apartamente": "{n} apartments",
"Trimestrul IV {n}": "Q4 {n}",
"Trimestrul II {n}": "Q2 {n}",
"Terasamente și organizare": "Earthworks and site set-up",
"Fundații și demisoluri": "Foundations and basements",
"Structură de rezistență": "Load-bearing structure",
"Închideri și compartimentări": "Envelope and partitions",
"Instalații": "Building services",
"Amenajări exterioare": "External landscaping",
"Stadiul reflectă raportul de șantier din Septembrie {n} Termenele afișate sunt estimative; cel contractual este cel din antecontract.": "Status reflects the site report of September {n}. The dates shown are estimates; the binding date is the one in the pre-sale agreement.",
"{n} — Jurnal": "{n} — Diary",
"Ce s-a lucrat": "What was done",
"în ultimele luni": "in recent months",
"Un raport pe lună, cu ce s-a executat efectiv și cu fotografii datate din teren.": "One report per month, with what was actually built and dated site photos.",
"Septembrie {n}": "September {n}",
"August {n}": "August {n}",
"Iulie {n}": "July {n}",
"Cea mai recentă": "Most recent",
"Etapa I — structură la nivelul etajului {n}": "Phase I — structure at floor {n} level",
"Turnarea planșeului peste etajul {n} s-a încheiat la blocurile {n} La blocurile {n} și {n} se lucrează la cofraje. A început săpătura pentru demisolurile blocurilor {n} și {n} primele din Etapa II.":
    "The slab over floor {n} has been poured at buildings {n}. Formwork is under way at buildings {n} and {n}. Excavation has started for the basements of buildings {n} and {n}, the first in Phase II.",
"Fotografie de șantier": "Site photo",
"de furnizat": "to be supplied",
"Arhivă": "Archive",
"Etapa I — fundații finalizate": "Phase I — foundations completed",
"Fundațiile pentru blocurile {n} sunt turnate și recepționate, cu procesele-verbale de fază determinantă semnate. A început ridicarea structurii la blocurile {n} și {n}": "The foundations of buildings {n} have been poured and accepted, with the key-stage inspection reports signed. Structural work has started at buildings {n} and {n}.",
"Organizare de șantier și terasamente": "Site set-up and earthworks",
"Platforma de organizare a fost amenajată, drumurile de acces provizorii sunt funcționale, iar terasamentele pentru prima etapă sunt finalizate. Racordurile provizorii de utilități au fost puse în funcțiune.": "The site compound has been set up, the temporary access roads are in use and the earthworks for the first phase are complete. Temporary utility connections have been commissioned.",
"{n} — Vizite pe șantier": "{n} — Site visits",
"Vizite": "Visits",
"pe șantier": "to the site",
"Vizitele se organizează cu programare, însoțite. Echipamentul de protecție este pus la dispoziție.": "Visits are organised by appointment and accompanied. Protective equipment is provided.",
"Cu programare": "By appointment",
"Data și ora se stabilesc telefonic sau prin e-mail. Vizitele se desfășoară în zilele lucrătoare.": "Date and time are agreed by phone or e-mail. Visits take place on working days.",
"Însoțit": "Accompanied",
"Un reprezentant însoțește vizita pe traseul autorizat și prezintă lucrările în execuție.": "A representative accompanies the visit along the authorised route and presents the works in progress.",
"Echipament inclus": "Equipment included",
"Cască și vestă reflectorizantă, furnizate la intrarea în incintă.": "Helmet and high-visibility vest, provided at the site entrance.",
"Fotografiere permisă": "Photography allowed",
"Fotografierea lucrărilor este permisă, fără restricții.": "Photographing the works is allowed, without restrictions.",
"Primește raportul lunar de șantier": "Receive the monthly site report",
"Un e-mail pe lună, cu stadiul fiecărei etape și fotografii datate din teren. Se poate opri oricând.": "One e-mail per month, with the status of each phase and dated site photos. Unsubscribe at any time.",
"Despre execuție": "About construction",
"și termene": "and deadlines",
"{n} întrebări despre urmărirea progresului și garanțiile contractuale.": "{n} questions about following progress and contractual guarantees.",
"Cât de des se actualizează pagina?": "How often is the page updated?",
"Lunar. Se publică stadiul fiecărei etape, faza cu faza, împreună cu fotografii datate din teren. Ultima actualizare: Septembrie {n}": "Monthly. The status of each phase is published stage by stage, together with dated site photos. Last update: September {n}.",
"Ce înseamnă procentele afișate?": "What do the percentages mean?",
"Fiecare etapă este împărțită în {n} faze de execuție, de la terasamente la amenajări exterioare. Procentul general al unei etape este media ponderată a fazelor, cu ponderile uzuale pentru clădiri de locuințe colective.": "Each phase is split into {n} construction stages, from earthworks to external landscaping. A phase's overall percentage is the weighted average of its stages, using the usual weights for apartment buildings.",
"Se poate vizita șantierul?": "Can the site be visited?",
"Da, cu programare și însoțit de un reprezentant, în echipament de protecție pus la dispoziție. Accesul neînsoțit nu este permis, din motive de securitate.": "Yes, by appointment and accompanied by a representative, wearing the protective equipment provided. Unaccompanied access is not allowed, for safety reasons.",
"Termenele de predare sunt garantate?": "Are the handover dates guaranteed?",
"Termenul fiecărei etape se înscrie în antecontractul semnat la notar. Datele afișate aici sunt cele estimate la data ultimei actualizări; termenul contractual este cel care obligă.": "Each phase's deadline is written into the pre-sale agreement signed before the notary. The dates shown here are estimates as of the last update; the contractual deadline is the binding one.",
"Ce se întâmplă dacă lucrările întârzie?": "What happens if the works are delayed?",
"Antecontractul prevede termenul de predare și consecințele depășirii acestuia. Orice modificare de calendar se comunică din timp.": "The pre-sale agreement sets the handover deadline and the consequences of exceeding it. Any change to the schedule is communicated in advance.",
"Raportul lunar poate fi primit pe e-mail?": "Can the monthly report be received by e-mail?",
"Da. La solicitare, raportul lunar cu fotografii se transmite pe e-mail imediat după publicare.": "Yes. On request, the monthly report with photos is sent by e-mail as soon as it is published.",
"Stadiul construcției Emerald City, Iași zona Păcurari: progresul fiecărei etape, jurnal lunar cu fotografii datate și vizite pe șantier.": "Construction progress at Emerald City, Iași Păcurari area: the progress of each phase, a monthly diary with dated photos and site visits.",
# ---- amplasament (zona) ---------------------------------------------------
"Apartamente Iași, zona Păcurari — amplasament | Emerald City": "Apartments in Iași, Păcurari area — location | Emerald City",
"Zona Păcurari": "Păcurari area",
"Păcurari, la {n} minute de Copou": "Păcurari, {n} minutes from Copou",
"Una dintre puținele zone din Iași care mai dispune de teren pentru ansambluri cu densitate redusă, la distanță mică de centrul universitar. Emerald City se află la limita de nord-vest a orașului, cu acces din Strada Ion Nistor.":
    "One of the few areas of Iași that still has land for low-density developments, a short distance from the university district. Emerald City lies on the north-western edge of the city, with access from Strada Ion Nistor.",
"Harta interactivă": "Interactive map",
"Universitatea „A.I. Cuza”": "“A.I. Cuza” University",
"Centrul Iașului": "Iași city centre",
"{n} — Poziția": "{n} — Position",
"Aproape de tot ce": "Close to everything",
"folosești zilnic": "you use every day",
"Școală, cumpărături, universitate și centru, la câteva minute pe artera Păcurari.": "School, shopping, university and city centre, a few minutes along the Păcurari road.",
"Păcurari este una dintre cele mai căutate zone rezidențiale din Iași: se află la câteva minute de Copou și de centrul universitar, dar suficient de aproape de limita orașului cât să permită ansambluri cu densitate redusă.":
    "Păcurari is one of the most sought-after residential areas of Iași: a few minutes from Copou and the university district, yet close enough to the city's edge to allow low-density developments.",
"Emerald City se află la limita de nord-vest a orașului, în spatele ansamblului Contemporan Homes de pe Strada Dealul Zorilor. Accesul se face din Strada Ion Nistor. Centrul Iașului este la {n} km, Copoul la {n} km, iar ieșirea spre Botoșani, pe DN{n} la câteva minute.":
    "Emerald City lies on the north-western edge of the city, behind the Contemporan Homes development on Strada Dealul Zorilor. Access is from Strada Ion Nistor. The city centre is {n} km away, Copou {n} km, and the DN{n} exit towards Botoșani a few minutes away.",
"Ansamblul are {n} de apartamente în {n} blocuri cu regim {n}D+P+{n}E, pe un teren de cinci hectare din care {n}% rămâne spațiu verde amenajat. Este unul dintre cele mai mari proiecte rezidențiale din zonă.":
    "The development has {n} apartments in {n} buildings of {n}B+GF+{n}, on a five-hectare plot of which {n}% stays landscaped green space. It is one of the largest residential projects in the area.",
"{n} — Distanțe": "{n} — Distances",
"Cât face": "How far",
"până unde contează": "to the places that matter",
"Distanțe și timpi măsurați pe traseu rutier real, fără trafic, de la amplasament.": "Distances and times measured on the actual road route from the site, without traffic.",
"Distanțe de la Emerald City": "Distances from Emerald City",
"Destinație": "Destination", "Distanță": "Distance", "Timp": "Time", "Mod": "Mode",
"Pe jos": "On foot",
"Calculate pe traseu rutier (OpenStreetMap), fără trafic. Distanța până la Paradis International College este cea indicată de dezvoltator.": "Calculated on the road route (OpenStreetMap), without traffic. The distance to Paradis International College is the one stated by the developer.",
"{n} — Harta": "{n} — Map",
"Trasee": "Routes",
"către fiecare reper": "to every landmark",
"Selectarea unui reper afișează traseul rutier. Reperele pot fi filtrate pe categorii, iar fundalul poate fi comutat pe imagine din satelit.": "Selecting a landmark shows the road route. Landmarks can be filtered by category and the background switched to satellite imagery.",
"{n} — În jur": "{n} — Nearby",
"de proximitate": "nearby",
"Serviciile accesibile pe jos și cele aflate la câteva minute cu mașina.": "Services within walking distance and those a few minutes away by car.",
"Cumpărături zilnice": "Daily shopping",
"Kaufland Păcurari la {n} km, plus magazinele de proximitate de pe artera Păcurari.": "Kaufland Păcurari {n} km away, plus the local shops along the Păcurari road.",
"Școli și grădinițe": "Schools and kindergartens",
"Paradis International College la {n} m, la {n} minute de mers pe jos.": "Paradis International College {n} m away, a {n}-minute walk.",
"Centrul universitar": "University district",
"Universitatea „Alexandru Ioan Cuza” la {n} km, în Copou.": "“Alexandru Ioan Cuza” University {n} km away, in Copou.",
"Parcul Copou la {n} km, plus cele {n} m² amenajate în interiorul ansamblului.": "Copou Park {n} km away, plus the {n} m² landscaped inside the development.",
"Transport public": "Public transport",
"Linii constante pe artera Păcurari, spre centru și spre Copou.": "Regular lines along the Păcurari road, towards the centre and Copou.",
"Ieșire din oraș": "Out of town",
"DN{n} spre Botoșani, pentru drumurile în afara Iașului.": "The DN{n} towards Botoșani, for trips outside Iași.",
"Servicii medicale": "Medical services",
"Spitalul „Sf. Spiridon” și rețeaua privată din zona centrală.": "“Sf. Spiridon” Hospital and the private network in the central area.",
"Mall-uri": "Shopping malls",
"Mall Moldova la {n} km și Palas la {n} km.": "Mall Moldova {n} km away and Palas {n} km.",
"{n} — Pentru cine": "{n} — Who it suits",
"Cui i se potrivește": "Who the area suits",
"Profilurile de cumpărător cărora zona li se potrivește.": "The buyer profiles the area suits.",
"Familii tinere": "Young families",
"Spațiu verde, locuri de joacă și parcare proprie, fără să ieși din oraș. Apartamentele de la parter au curte, între {n} și {n} m².": "Green space, playgrounds and your own parking, without leaving the city. Ground-floor apartments have a garden, between {n} and {n} m².",
"Investitori": "Investors",
"Cererea de chirii e susținută de apropierea de centrul universitar. Garsonierele pornesc de la {n} €, cu estimare de randament disponibilă pe site.": "Rental demand is supported by the proximity to the university district. Studios start at €{n}, with a yield estimate available on the site.",
"Cei care lucrează în nord-vest": "Those working in the north-west",
"Acces direct la artera Păcurari și la DN{n} fără traversarea centrului.": "Direct access to the Păcurari road and the DN{n}, without crossing the centre.",
"La prima locuință": "First-time buyers",
"Garsonierele pornesc de la {n} €, cu TVA inclus. Se pot cumpăra cu credit ipotecar sau, în plafon, prin Noua Casă.": "Studios start at €{n}, VAT included. They can be bought with a mortgage or, within the ceiling, through the Noua Casă scheme.",
"Despre zonă": "About the area",
"și acces": "and access",
"{n} întrebări despre poziție, distanțe și transport.": "{n} questions about position, distances and transport.",
"Unde se află mai exact Emerald City?": "Where exactly is Emerald City?",
"În Iași, zona Păcurari, cu acces din Strada Ion Nistor. Ansamblul este la limita de nord-vest a orașului, în spatele ansamblului Contemporan Homes de pe Strada Dealul Zorilor.": "In Iași, Păcurari area, with access from Strada Ion Nistor. The development is on the north-western edge of the city, behind the Contemporan Homes development on Strada Dealul Zorilor.",
"Cât face până în centrul Iașului?": "How far is the city centre?",
"Aproximativ {n} km, adică în jur de {n} minute cu mașina fără trafic.": "About {n} km, around {n} minutes by car without traffic.",
"Cât face până la universitate?": "How far is the university?",
"{n} km până la Universitatea „Alexandru Ioan Cuza”, aproximativ {n} minute cu mașina.": "{n} km to “Alexandru Ioan Cuza” University, about {n} minutes by car.",
"Există școli în apropiere?": "Are there schools nearby?",
"Paradis International College se află la aproximativ {n} de metri, la {n} minute de mers pe jos.": "Paradis International College is about {n} metres away, a {n}-minute walk.",
"Cum stă zona cu cumpărăturile?": "What about shopping?",
"Kaufland Păcurari este la {n} km, adică {n} minute cu mașina. Mall Moldova la {n} km și Palas la {n} km.": "Kaufland Păcurari is {n} km away, {n} minutes by car. Mall Moldova {n} km and Palas {n} km.",
"Cum se ajunge cu transportul public?": "How do I get there by public transport?",
"Artera Păcurari are linii constante spre centru și spre Copou. Stația cea mai apropiată se află pe drumul de acces în ansamblu.": "The Păcurari road has regular lines towards the centre and Copou. The nearest stop is on the access road to the development.",
"Cât face până la aeroport?": "How far is the airport?",
"{n} km, aproximativ {n} minute cu mașina.": "{n} km, about {n} minutes by car.",
"De ce zona Păcurari și nu altă zonă din Iași?": "Why Păcurari and not another area of Iași?",
"Este una dintre puținele zone din Iași care mai are teren pentru ansambluri cu spațiu între clădiri, la distanță mică de Copou și de centrul universitar.": "It is one of the few areas of Iași that still has land for developments with space between buildings, a short distance from Copou and the university district.",
"Unde se află Emerald City în Iași, zona Păcurari: distanțe reale până la Copou, centru, universitate și școli, hartă interactivă cu traseu și ghid de zonă.": "Where Emerald City is in Iași, Păcurari area: real distances to Copou, the centre, the university and schools, an interactive map with routes and an area guide.",
"Apartament în ansamblul Emerald City, zona Păcurari": "Apartment in the Emerald City development, Păcurari area",
}
