# -*- coding: utf-8 -*-
# Dezvoltator, Aparitii in presa, Finisaje.
T = {
# ---- dezvoltator ----------------------------------------------------------
"Dezvoltator — Green Stone Group | Emerald City Iași": "Developer — Green Stone Group | Emerald City Iași",
"Cine construiește Emerald City": "Who is building Emerald City",
"Tala Sapphire S.R.L., companie din Green Stone Group — un grup care dezvoltă proiecte rezidențiale și de regenerare urbană în Marea Britanie, Israel și România. Emerald City este al treilea ansamblu al grupului în Iași.":
    "Tala Sapphire S.R.L., a Green Stone Group company — a group developing residential and urban regeneration projects in the United Kingdom, Israel and Romania. Emerald City is the group's third development in Iași.",
"Portofoliu": "Portfolio", "Țări": "Countries", "Locuințe în România": "Homes in Romania", "Primul proiect livrat": "First project delivered",
"{n} — Grupul": "{n} — The group",
"Green Stone Group,": "Green Stone Group,",
"„Delivering Home”": "“Delivering Home”",
"Un grup de firme dedicat dezvoltării imobiliare și regenerării urbane, activ pe trei piețe.": "A group of companies dedicated to real estate development and urban regeneration, active in three markets.",
"Green Stone Group dezvoltă proiecte care îmbină designul contemporan cu soluții ecologice. Portofoliul acoperă locuințe, facilități comerciale și spații publice, cu accent pe revitalizarea zonelor urbane degradate sau subutilizate — în loc de extinderea orașului pe teren liber.":
    "Green Stone Group develops projects that combine contemporary design with ecological solutions. The portfolio covers housing, commercial facilities and public spaces, with a focus on revitalising degraded or under-used urban areas — instead of expanding the city onto open land.",
"Grupul activează în Marea Britanie, Israel și România, ceea ce înseamnă că standardele de execuție și de finisaj vin din piețe mai exigente decât cea locală. În România a livrat faza I de la Magnolia Residence, în Sibiu, cu {n} de apartamente, și dezvoltă în Iași ansamblurile Lapis și Onyx Residence.":
    "The group operates in the United Kingdom, Israel and Romania, which means construction and finishing standards come from more demanding markets than the local one. In Romania it delivered phase I of Magnolia Residence in Sibiu, with {n} apartments, and is developing Lapis and Onyx Residence in Iași.",
"Emerald City este al treilea proiect al grupului în Iași și cel mai mare: {n} de apartamente pe cinci hectare, dezvoltat prin compania Tala Sapphire S.R.L.": "Emerald City is the group's third project in Iași and its largest: {n} apartments on five hectares, developed through Tala Sapphire S.R.L.",
"{n} — Principii": "{n} — Principles",
"Cum lucrează": "How the group",
"grupul": "works",
"Patru constante ale proiectelor grupului.": "Four constants of the group's projects.",
"Regenerare urbană": "Urban regeneration",
"Grupul transformă zone degradate sau subutilizate în cartiere locuibile, nu doar în clădiri noi pe teren liber.": "The group turns degraded or under-used areas into liveable neighbourhoods, not just new buildings on open land.",
"Soluții ecologice": "Ecological solutions",
"Panouri fotovoltaice, piste de biciclete și spații verzi proiectate de la început, nu adăugate la final.": "Photovoltaic panels, cycle lanes and green spaces designed from the start, not added at the end.",
"Experiență internațională": "International experience",
"Proiecte în Marea Britanie, Israel și România — expertiză locală cu standarde aduse din piețe mai exigente.": "Projects in the United Kingdom, Israel and Romania — local expertise with standards brought from more demanding markets.",
"Vânzare directă": "Direct sales",
"Discuți prețul și termenele cu cel care construiește, fără comision de intermediere.": "You discuss price and deadlines with the builder itself, with no agency commission.",
"{n} — Galerie": "{n} — Gallery",
"Din proiectele": "From the group's",
"grupului": "projects",
"Imagini din ansamblurile Green Stone Group, publicate de grup.": "Images from Green Stone Group developments, published by the group.",
"Complex de apartamente": "Apartment complex",
"Marea Britanie": "United Kingdom",
"Ansamblu rezidențial": "Residential development",
"Israel": "Israel",
"Spații de birouri": "Office space",
"Portofoliu comercial": "Commercial portfolio",
"{n} — România": "{n} — Romania",
"Proiectele": "Projects",
"din țară": "in Romania",
"{n} de locuințe în Iași și Sibiu, livrate sau în dezvoltare.": "{n} homes in Iași and Sibiu, delivered or under development.",
"Iași · în dezvoltare": "Iași · under development",
"{n} de apartamente în {n} blocuri cu regim {n}D+P+{n}E, pe cinci hectare din care {n}% rămâne spațiu verde amenajat. Predare la cheie, vânzare directă de la dezvoltator.": "{n} apartments in {n} buildings of {n}B+GF+{n}, on five hectares of which {n}% stays landscaped green space. Turnkey handover, direct sales by the developer.",
"Etape": "Phases",
"Vezi proiectul": "See the project",
"Iași · din {n}": "Iași · since {n}",
"Ansamblu cu piste de biciclete în tot cartierul, panouri fotovoltaice și finisaje premium. Proiectul a început la finalul lui {n} și este în curs de dezvoltare.": "A development with cycle lanes throughout the neighbourhood, photovoltaic panels and premium finishes. The project started at the end of {n} and is under development.",
"Început": "Started",
"În dezvoltare": "Under development",
"lapis-residence.ro": "lapis-residence.ro",
"Prelungirea ansamblului Lapis: {n} de apartamente în {n} blocuri similare ca structură și dotări, cu spații comerciale la parter. Împreună, cele două ajung la {n} de locuințe.": "The extension of Lapis: {n} apartments in {n} buildings similar in structure and features, with commercial units on the ground floor. Together, the two reach {n} homes.",
"onyx-residence.ro": "onyx-residence.ro",
"Sibiu": "Sibiu",
"Magnolia Residence": "Magnolia Residence",
"Faza I, finalizată: {n} de apartamente în vile P+{n}E+M și imobile P+{n}E și P+{n}E+R, plus o clădire comercială. Faza a II-a cuprinde {n} imobile, până la P+{n}E+ER.": "Phase I, completed: {n} apartments in GF+{n}+attic villas and GF+{n} and GF+{n}+set-back buildings, plus a commercial building. Phase II comprises {n} buildings, up to GF+{n}+set-back.",
"Faza I": "Phase I", "Finalizată": "Completed", "Faza a II-a": "Phase II", "În lucru": "In progress",
"greenstone-group.ro": "greenstone-group.ro",
"{n} — Internațional": "{n} — International",
"din Marea Britanie și Israel": "from the United Kingdom and Israel",
"Șase ansambluri rezidențiale și de birouri, finalizate sau în construcție.": "Six residential and office developments, completed or under construction.",
"Marea Britanie · {n}": "United Kingdom · {n}",
"Apartamente de lux": "Luxury apartments",
"Complex cu {n} de apartamente pe cinci etaje — studio, o cameră și două camere, unele cu birou sau spațiu suplimentar de depozitare.": "A complex of {n} apartments over five floors — studios, one- and two-bedroom units, some with a study or extra storage.",
"Valoare estimată": "Estimated value",
"{n} mil. £": "£{n}m",
"Apartamente moderne": "Modern apartments",
"Complex cu {n} de apartamente de înaltă calitate, cu specificații superioare în toate unitățile.": "A complex of {n} high-quality apartments, with superior specifications in every unit.",
"Israel · finalizat": "Israel · completed",
"Proiect de referință": "Landmark project",
"{n} clădiri cu regim P+{n} și {n} m² construiți, la care se adaugă {n} m² de spații comerciale pentru serviciile din incintă.": "{n} buildings of GF+{n} and {n} m² built, plus {n} m² of commercial space for on-site services.",
"Construit": "Built",
"Preț mediu": "Average price",
"Israel · finalizat în {n}": "Israel · completed in {n}",
"{n} clădiri cu {n} de apartamente de lux și {n} m² construiți, într-unul dintre cele mai importante orașe din Israel.": "{n} buildings with {n} luxury apartments and {n} m² built, in one of Israel's major cities.",
"Israel · faza I în {n}": "Israel · phase I in {n}",
"{n} clădiri cu {n} de apartamente și {n} m² construiți, plus {n} m² de spații comerciale în incintă.": "{n} buildings with {n} apartments and {n} m² built, plus {n} m² of on-site commercial space.",
"Comercial": "Commercial",
"Israel · în construcție": "Israel · under construction",
"Turn de birouri": "Office tower",
"Turn de birouri cu aproximativ {n} m² de spații comerciale, cu fațadă proiectată în detaliu și planificare adaptată mediului construit.": "An office tower with about {n} m² of commercial space, with a carefully detailed façade and planning adapted to the built environment.",
"Spații": "Space",
"≈{n} m²": "≈{n} m²",
"În construcție": "Under construction",
"{n} — Emerald City": "{n} — Emerald City",
"Elemente": "Elements you can",
"verificabile independent": "verify independently",
"Elementele care pot fi verificate independent, înainte de semnare.": "The elements that can be checked independently, before signing.",
"Proiecte care pot fi vizitate": "Projects that can be visited",
"Lapis și Onyx Residence se află în Iași și pot fi vizitate.": "Lapis and Onyx Residence are in Iași and can be visited.",
"Documentație completă": "Complete documentation",
"Autorizația de construire, certificatul de urbanism și planșele, la cerere.": "The building permit, the urban planning certificate and the drawings, on request.",
"Garanții scrise": "Written warranties",
"Structura pe toată durata clădirii, viciile ascunse {n} ani, conform legii.": "The structure for the life of the building, hidden defects for {n} years, as required by law.",
"Stadiul publicat lunar": "Progress published monthly",
"Jurnal de șantier cu fotografii datate, pentru fiecare etapă.": "A site diary with dated photos, for every phase.",
"Prețuri afișate": "Listed prices",
"Toate cele {n} de apartamente, cu preț, suprafață și disponibilitate.": "All {n} apartments, with price, area and availability.",
"Fără intermediari": "No intermediaries",
"Contract direct cu dezvoltatorul, fără comision de agenție.": "A direct contract with the developer, with no agency commission.",
"{n} — Date": "{n} — Data",
"Datele": "Project",
"proiectului": "data",
"Cine semnează, cine proiectează și în baza cărei documentații se construiește.": "Who signs, who designs and on what documentation construction is based.",
"Grup": "Group",
"Green Stone Group": "Green Stone Group",
"Str. Ion Nistor, Iași": "Str. Ion Nistor, Iași",
"Despre grup": "About the group",
"și portofoliu": "and portfolio",
"{n} întrebări despre cine construiește și ce a livrat până acum.": "{n} questions about who is building and what has been delivered so far.",
"Emerald City este dezvoltat de Tala Sapphire S.R.L., companie din Green Stone Group. Vânzarea se face direct, fără comision de intermediere.": "Emerald City is developed by Tala Sapphire S.R.L., a Green Stone Group company. Sales are direct, with no agency commission.",
"Ce este Green Stone Group?": "What is Green Stone Group?",
"Un grup de firme dedicat dezvoltării de proiecte imobiliare și regenerării urbane la nivel internațional, cu proiecte în Marea Britanie, Israel și România.": "A group of companies dedicated to real estate development and urban regeneration internationally, with projects in the United Kingdom, Israel and Romania.",
"Ce alte proiecte are grupul în Iași?": "What other projects does the group have in Iași?",
"Lapis Residence, început la finalul lui {n} și Onyx Residence, prelungirea acestuia, începută în {n} Împreună, cele două ansambluri însumează {n} de apartamente.": "Lapis Residence, started at the end of {n}, and Onyx Residence, its extension, started in {n}. Together, the two developments total {n} apartments.",
"Grupul a livrat proiecte finalizate?": "Has the group delivered completed projects?",
"Da. Faza I de la Magnolia Residence, în Sibiu, cu {n} de apartamente, două complexuri în Marea Britanie și mai multe ansambluri în Israel, dintre care unul finalizat în {n}": "Yes. Phase I of Magnolia Residence in Sibiu, with {n} apartments, two complexes in the United Kingdom and several developments in Israel, one of them completed in {n}.",
"Ce înseamnă regenerare urbană?": "What does urban regeneration mean?",
"Transformarea zonelor degradate sau subutilizate ale orașului în spații locuibile, cu locuințe, facilități comerciale și spații publice — în loc de extinderea orașului pe teren agricol.": "Turning degraded or under-used parts of the city into liveable places, with housing, commercial facilities and public spaces — instead of expanding the city onto farmland.",
"De ce contează cine este dezvoltatorul?": "Why does it matter who the developer is?",
"Garanțiile, termenele și calitatea execuției depind de societatea care semnează contractul și de proiectele livrate anterior. Un dezvoltator cu ansambluri finalizate, care pot fi vizitate, poate fi verificat.": "Warranties, deadlines and build quality depend on the company signing the contract and on the projects it has delivered before. A developer with completed developments that can be visited can be verified.",
"Pot vizita proiectele anterioare?": "Can I visit the previous projects?",
"Da. Ansamblurile din Iași pot fi vizitate; adresele și modul de acces se comunică la biroul de vânzări.": "Yes. The Iași developments can be visited; addresses and access details are provided by the sales office.",
"Ce garanții primesc la Emerald City?": "What warranties do I get at Emerald City?",
"Structura de rezistență este garantată pe toată durata de existență a clădirii, iar viciile ascunse {n} ani de la recepție, conform Legii {n}/{n} și Codului civil. Detaliile complete sunt pe pagina „Despre noi”.": "The load-bearing structure is guaranteed for the whole life of the building and hidden defects for {n} years from acceptance, under Law {n}/{n} and the Civil Code. Full details are on the “About us” page.",
"Tala Sapphire S.R.L., companie din Green Stone Group, cu proiecte în Marea Britanie, Israel și România. Portofoliu și datele proiectului.": "Tala Sapphire S.R.L., a Green Stone Group company with projects in the United Kingdom, Israel and Romania. Portfolio and project data.",
"Ansamblu rezidențial Green Stone Group în Israel": "Green Stone Group residential development in Israel",
"Ansamblul Onyx Residence din Iași": "The Onyx Residence development in Iași",
"Complex de apartamente dezvoltat în Marea Britanie": "Apartment complex developed in the United Kingdom",
"Ansamblu rezidențial dezvoltat în Israel": "Residential development built in Israel",
"Clădire de birouri dezvoltată de Green Stone Group": "Office building developed by Green Stone Group",
# ---- presa ----------------------------------------------------------------
"Apariții în presă — Emerald City Iași": "Press coverage — Emerald City Iași",
"Presă": "Press",
"Ce s-a scris despre Emerald City": "What the press has written about Emerald City",
"Articole apărute în publicații locale și naționale, cu link către sursa originală. Mai jos sunt datele verificate ale proiectului, puse la dispoziția jurnaliștilor.": "Articles published in local and national media, with links to the original source. Below are the verified project facts made available to journalists.",
"Aparițiile în presă": "Press coverage",
"Contact presă": "Press contact",
"{n} — Apariții": "{n} — Coverage",
"Articole": "Articles",
"despre proiect": "about the project",
"Fiecare intrare conține publicația, data și link către articolul original.": "Each entry shows the publication, the date and a link to the original article.",
"Ziarul de Iași": "Ziarul de Iași",
"Machetă": "Mock-up",
"Emerald City: {n} de apartamente pe cinci hectare în zona Păcurari": "Emerald City: {n} apartments on five hectares in the Păcurari area",
"Cel mai mare ansamblu rezidențial din nord-vestul Iașului intră în etapa a doua de construcție. Proiectul mizează pe densitate mică — {n} blocuri cu regim {n}D+P+{n}E — și pe {n}% spațiu verde amenajat.": "The largest residential development in north-western Iași enters its second construction phase. The project relies on low density — {n} buildings of {n}B+GF+{n} — and {n}% landscaped green space.",
"{n} septembrie {n}": "{n} September {n}",
"{n} august {n}": "{n} August {n}",
"{n} iulie {n}": "{n} July {n}",
"{n} iunie {n}": "{n} June {n}",
"Citește pe Ziarul de Iași": "Read on Ziarul de Iași",
"BZI": "BZI",
"Cum arată un cartier în care spațiul verde depășește suprafața construită": "What a neighbourhood looks like when green space exceeds the built area",
"La Emerald City, cele {n} m² de spațiu verde amenajat sunt mai mult decât amprenta la sol a celor {n} blocuri. Parcarea se rezolvă cu {n} de locuri, dintre care {n} subterane.": "At Emerald City, the {n} m² of landscaped green space exceed the footprint of the {n} buildings. Parking is solved with {n} spaces, {n} of them underground.",
"Citește pe BZI": "Read on BZI",
"APIX": "APIX",
"Piața rezidențială din Iași: cererea se mută spre ansamblurile cu dotări": "The Iași residential market: demand shifts towards developments with amenities",
"Cumpărătorii ieșeni aleg tot mai des proiectele care includ finisaje, parcare și spații comune. Emerald City, din zona Păcurari, predă apartamentele complet finisate, cu încălzire în pardoseală.": "Buyers in Iași increasingly choose projects that include finishes, parking and shared spaces. Emerald City, in the Păcurari area, hands over apartments fully finished, with underfloor heating.",
"Citește pe APIX": "Read on APIX",
"{n}Iași": "{n}Iași",
"Investiție în Păcurari: {n} blocuri și {n} de locuri de parcare": "Investment in Păcurari: {n} buildings and {n} parking spaces",
"Ansamblul dezvoltat de Tala Sapphire, companie din Green Stone Group, se construiește în trei etape, pe un teren de {n} m² la limita de nord-vest a Iașului.": "The development by Tala Sapphire, a Green Stone Group company, is being built in three phases on a {n} m² plot on the north-western edge of Iași.",
"Citește pe {n}Iași": "Read on {n}Iași",
"{n} — Date pentru presă": "{n} — Press facts",
"Cifrele": "Verified",
"verificate": "figures",
"Datele din documentația de autorizare, disponibile pentru preluare ca atare.": "Facts from the permitting documentation, available for use as they are.",
"Denumire": "Name",
"{n} în {n} blocuri": "{n} in {n} buildings",
"{n}D+P+{n}E · Hmax {n} m": "{n}B+GF+{n} · max. height {n} m",
"{n} m² · {n}%": "{n} m² · {n}%",
"Parcare": "Parking",
"{n} locuri · {n} subterane": "{n} spaces · {n} underground",
"{n} · {n} / {n} / {n} apartamente": "{n} · {n} / {n} / {n} apartments",
"presa@emerald-city.ro": "presa@emerald-city.ro",
"{n} — Materiale": "{n} — Materials",
"Ce punem": "What we",
"la dispoziție": "provide",
"Materiale de rezoluție mare, transmise la cerere în aceeași zi lucrătoare.": "High-resolution materials, sent on request on the same working day.",
"Randări de interior": "Interior renders",
"Imagini de rezoluție mare din apartamentele-model, pentru print și online.": "High-resolution images of the show apartments, for print and online.",
"Planuri și secțiuni": "Plans and sections",
"Planurile celor {n} compartimentări și secțiunea verticală prin bloc.": "The plans of the {n} layouts and the vertical section through a building.",
"Fișa de proiect": "Project fact sheet",
"Un document cu toate cifrele verificate: suprafețe, indicatori, etape, termene.": "A document with all the verified figures: areas, indicators, phases, deadlines.",
"Elemente de identitate": "Brand assets",
"Logo în variantele pe fond deschis și închis, plus paleta de culori.": "The logo in light- and dark-background versions, plus the colour palette.",
"Solicitare materiale": "Request materials",
"Articole despre ansamblul Emerald City din Iași, zona Păcurari, apărute în publicații locale și naționale. Date de proiect și materiale pentru jurnaliști.": "Articles about the Emerald City development in Iași, Păcurari area, published in local and national media. Project facts and materials for journalists.",
# ---- finisaje -------------------------------------------------------------
"Finisaje incluse în preț — predare la cheie | Emerald City": "Finishes included in the price — turnkey handover | Emerald City",
"{n} poziții de finisaj incluse în preț, montate și garantate. Apartamentul se predă complet finisat, gata de mobilat.": "{n} finishing items included in the price, installed and guaranteed. The apartment is handed over fully finished, ready to furnish.",
"Lista completă a dotărilor": "The full list of features",
"Prețuri și disponibilitate": "Prices and availability",
"Poziții incluse": "Items included",
"{n} mm": "{n} mm",
"Parchet laminat": "Laminate flooring",
"Tâmplărie PVC": "PVC windows",
"Economie la gaz": "Gas savings",
"{n} — Incluse în preț": "{n} — Included in the price",
"{n} avantaje,": "{n} advantages,",
"fără cost suplimentar": "at no extra cost",
"Fiecare dotare, cu specificația tehnică alături și cu avantajul concret la utilizare.": "Each feature, with its technical specification and the concrete benefit in use.",
"În toate camerele, distribuitor individual": "In every room, with an individual manifold",
"Căldura se distribuie uniform de la sol, fără calorifere pe pereți. Peretele rămâne liber pentru mobilier, iar consumul scade, instalația lucrând la temperatură joasă.": "Heat spreads evenly from the floor, with no radiators on the walls. Walls stay free for furniture and consumption drops, as the system runs at low temperature.",
"Randament ridicat, reglaj pe cameră": "High efficiency, room-by-room control",
"Recuperează căldura din gazele de ardere, așa că scoate mai multă energie din același metru cub de gaz. Diferența la factură ajunge până la {n}% față de o centrală clasică.": "It recovers heat from the flue gases, extracting more energy from the same cubic metre of gas. The difference on the bill reaches up to {n}% compared with a conventional boiler.",
"Izolație continuă, fără punți termice": "Continuous insulation, no thermal bridges",
"Fațada este izolată pe tot conturul, inclusiv la planșee și buiandrugi, ceea ce reduce pierderile de căldură iarna, aportul termic vara și zgomotul din exterior.": "The façade is insulated along its whole perimeter, including slabs and lintels, which reduces heat loss in winter, heat gain in summer and outside noise.",
"Geam tripan, sticlă Low-E": "Triple glazing, Low-E glass",
"Profilul cu șapte camere și geamul cu trei foi izolează termic și fonic la nivelul cerut clădirilor noi. Stratul Low-E reflectă căldura înapoi în încăpere.": "The seven-chamber profile and triple glazing insulate against heat and noise to the standard required of new buildings. The Low-E coating reflects heat back into the room.",
"Clasă de trafic intens": "Heavy-traffic grade",
"Grosime de {n} mm, dimensionată pentru trafic intens. Montajul pe strat fonoabsorbant reduce transmiterea zgomotului de impact către nivelul inferior.": "{n} mm thick, rated for heavy traffic. Laid on a sound-absorbing underlay, it reduces impact noise transmitted to the floor below.",
"Gresie, faianță, obiecte sanitare, baterii": "Floor and wall tiles, sanitary ware, taps",
"Placările, vasul de toaletă, lavoarul, bateriile și racordurile sunt montate. Nu sunt necesare lucrări suplimentare după predare.": "Tiling, toilet, washbasin, taps and connections are installed. No further work is needed after handover.",
"Aparataj montat, tablou cu siguranțe": "Fittings installed, consumer unit with breakers",
"Prizele și întrerupătoarele sunt montate, tabloul este echipat și etichetat, iar circuitele sunt dimensionate separat pentru bucătărie, grup sanitar și camere.": "Sockets and switches are installed, the consumer unit is equipped and labelled, and circuits are sized separately for the kitchen, bathroom and rooms.",
"Glet fin și vopsea lavabilă": "Fine skim coat and washable paint",
"Pereții și tavanele sunt gletuite și vopsite. Suprafața este pregătită pentru mobilare imediată sau pentru aplicarea altei culori, fără pregătiri suplimentare.": "Walls and ceilings are skimmed and painted. The surface is ready for immediate furnishing or for another colour, with no extra preparation.",
"Finisaj mat, feronerie inclusă": "Matt finish, hardware included",
"Toate ușile interioare sunt montate, cu tocuri, pervazuri și feronerie. Ușa de intrare este metalică, cu izolație și închidere în mai multe puncte.": "All interior doors are fitted, with frames, architraves and hardware. The entrance door is metal, insulated, with multi-point locking.",
"Post interior în fiecare apartament": "An indoor station in every apartment",
"Permite identificarea vizitatorilor înainte de deschiderea accesului. Intrarea în bloc și în parcarea subterană se face controlat, cu cartelă sau cod.": "Lets you identify visitors before opening. Access to the building and the underground car park is controlled, by card or code.",
"Specificațiile tehnice și mărcile exacte se confirmă în anexa tehnică a contractului de vânzare.": "Exact technical specifications and brands are confirmed in the technical annex of the sale contract.",
"{n} — Cameră cu cameră": "{n} — Room by room",
"pe fiecare încăpere": "for every room",
"Aceleași dotări, defalcate pe încăperi.": "The same features, broken down by room.",
"Living și dining": "Living and dining",
"Parchet laminat de {n} mm, clasă de trafic intens": "{n} mm laminate flooring, heavy-traffic grade",
"Încălzire în pardoseală, fără calorifere pe pereți": "Underfloor heating, no radiators on the walls",
"Pereți gletuiți și vopsiți lavabil": "Walls skimmed and painted with washable paint",
"Tâmplărie PVC cu {n} camere, geam tripan": "{n}-chamber PVC windows, triple glazing",
"Prize și întrerupătoare montate": "Sockets and switches installed",
"Gresie montată pe toată suprafața": "Floor tiles laid over the whole area",
"Racorduri pregătite pentru chiuvetă și mașina de spălat vase": "Connections ready for the sink and dishwasher",
"Circuit electric dedicat, cu siguranță proprie": "Dedicated electrical circuit with its own breaker",
"Priză pentru plită și cuptor": "Socket for hob and oven",
"Preechipare pentru hotă": "Pre-wiring for a cooker hood",
"Încălzire în pardoseală, cu reglaj pe cameră": "Underfloor heating with room-by-room control",
"Ușă interioară montată, cu toc și feronerie": "Interior door fitted, with frame and hardware",
"Pereți finisați, gata de mobilat": "Finished walls, ready to furnish",
"Tâmplărie cu geam tripan și sticlă Low-E": "Windows with triple glazing and Low-E glass",
"Grup sanitar": "Bathroom",
"Gresie și faianță montate": "Floor and wall tiles laid",
"Vas de toaletă și rezervor": "Toilet and cistern",
"Lavoar cu baterie": "Washbasin with tap",
"Baterie și racorduri pentru duș sau cadă": "Tap and connections for shower or bath",
"Ventilație și priză cu protecție": "Ventilation and protected socket",
"Hol și intrare": "Hallway and entrance",
"Ușă metalică de intrare, izolată, cu închidere în mai multe puncte": "Insulated metal entrance door with multi-point locking",
"Videointerfon cu post interior": "Video intercom with indoor station",
"Tablou electric echipat și etichetat": "Consumer unit equipped and labelled",
"Parchet sau gresie, după compartimentare": "Laminate or tiles, depending on the layout",
"Spațiu de depozitare la compartimentările care îl includ": "Storage space in the layouts that include it",
"Balcon și curte": "Balcony and garden",
"Pardoseală exterioară antiderapantă": "Non-slip outdoor flooring",
"Balustradă montată": "Railing fitted",
"Priză exterioară la apartamentele cu curte": "Outdoor socket in apartments with a garden",
"Diferența": "The difference",
"față de un apartament la gri": "from a shell apartment",
"Aceleași finisaje, executate separat, la un apartament semifinisat sau la gri.": "The same finishes, done separately, in a semi-finished or shell apartment.",
"Ce include fiecare tip de predare": "What each type of handover includes",
"Element": "Item",
"La cheie, Emerald City": "Turnkey, Emerald City",
"Semifinisat": "Semi-finished",
"La gri": "Shell",
"Pardoseli": "Floors",
"Montate": "Installed",
"De cumpărat și montat": "To buy and install",
"Șapă brută": "Bare screed",
"Gresie și faianță": "Floor and wall tiles",
"Nimic": "None",
"Obiecte sanitare": "Sanitary ware",
"Pereți": "Walls",
"Gletuiți și vopsiți": "Skimmed and painted",
"Tencuiți, de gletuit": "Plastered, to be skimmed",
"Zidărie brută": "Bare masonry",
"Uși interioare": "Interior doors",
"Goluri": "Openings only",
"Instalație electrică": "Electrical installation",
"Cu aparataj montat": "With fittings installed",
"Trasă, fără aparataj": "Wired, no fittings",
"Doar tuburi": "Conduits only",
"Încălzire": "Heating",
"În pardoseală, funcțională": "Underfloor, working",
"Distribuție, fără centrală": "Distribution only, no boiler",
"Timp până te muți": "Time until you move in",
"Imediat după recepție": "Right after acceptance",
"{n} luni de lucrări": "{n} months of works",
"Despre finisaje": "About finishes",
"și garanții": "and warranties",
"{n} întrebări despre ce este inclus, ce nu și ce se poate schimba.": "{n} questions about what is included, what is not and what can be changed.",
"Ce înseamnă predare la cheie?": "What does turnkey handover mean?",
"Apartamentul se predă complet finisat: pardoseli montate, pereți gletuiți și vopsiți, grup sanitar echipat, uși montate, instalație electrică cu aparataj și încălzire în pardoseală funcțională. Este gata de mobilat la recepție.": "The apartment is handed over fully finished: floors laid, walls skimmed and painted, bathroom equipped, doors fitted, electrical installation with fittings and working underfloor heating. It is ready to furnish at acceptance.",
"Da. Prețul afișat include TVA și toate cele {n} poziții de finisaj. Nu există costuri suplimentare pentru execuția lor.": "Yes. The listed price includes VAT and all {n} finishing items. There are no extra costs for their installation.",
"Ce nu este inclus?": "What is not included?",
"Mobilierul, electrocasnicele, corpurile de iluminat decorative și amenajarea curții. Racordurile și circuitele pentru ele sunt însă pregătite.": "Furniture, appliances, decorative light fittings and garden landscaping. The connections and circuits for them are, however, prepared.",
"Pot schimba finisajele?": "Can I change the finishes?",
"Modificările se analizează la biroul de vânzări, în funcție de faza de execuție a blocului. Numărul de opțiuni disponibile scade pe măsură ce lucrările avansează.": "Changes are reviewed at the sales office, depending on the building's construction stage. The number of available options decreases as works progress.",
"Ce garanție am pentru finisaje?": "What warranty do I have for the finishes?",
"Finisajele sunt garantate conform anexei tehnice a contractului, iar instalațiile și echipamentele conform garanției fiecărui producător. Structura și viciile ascunse sunt acoperite separat, prin lege.": "Finishes are guaranteed under the technical annex of the contract, and installations and equipment under each manufacturer's warranty. The structure and hidden defects are covered separately, by law.",
"De ce încălzire în pardoseală și nu calorifere?": "Why underfloor heating and not radiators?",
"Căldura se distribuie uniform de la sol în sus și funcționează la temperatură joasă, deci consumă mai puțin. În plus, peretele rămâne liber pentru mobilier.": "Heat spreads evenly from the floor up and runs at low temperature, so it uses less energy. Walls also stay free for furniture.",
"Ce înseamnă tâmplărie cu {n} camere?": "What are {n}-chamber windows?",
"Numărul de camere de aer din profilul ferestrei. Șapte camere, combinate cu geam tripan și sticlă Low-E, izolează termic și fonic la nivelul cerut clădirilor noi.": "The number of air chambers in the window profile. Seven chambers, combined with triple glazing and Low-E glass, insulate against heat and noise to the standard required of new buildings.",
"Cât economisesc cu centrala în condensație?": "How much do I save with the condensing boiler?",
"Până la {n}% la consumul de gaz față de o centrală clasică, pentru că recuperează căldura din gazele de ardere în loc să o evacueze pe horn.": "Up to {n}% on gas consumption compared with a conventional boiler, because it recovers heat from the flue gases instead of venting it through the chimney.",
"Lista de prețuri": "Price list",
"Toate prețurile,": "All prices,",
"într-un singur document": "in a single document",
"Lista completă de disponibilitate, cu suprafețe, etaje, orientări și prețuri, actualizată la zi. Se transmite pe e-mail în aceeași zi lucrătoare.": "The full availability list, with areas, floors, orientations and prices, fully up to date. Sent by e-mail on the same working day.",
"Toate apartamentele disponibile": "All available apartments",
"Prețuri cu TVA inclus": "Prices with VAT included",
"Condiții de plată și etape": "Payment terms and phases",
"Primește lista": "Get the list",
"Trimite lista": "Send the list",
"Cele {n} poziții de finisaj incluse în preț: încălzire în pardoseală, tâmplărie cu {n} camere, parchet de {n} mm, grupuri sanitare echipate.": "The {n} finishing items included in the price: underfloor heating, {n}-chamber windows, {n} mm flooring, equipped bathrooms.",
"Finisaje living și dining la Emerald City": "Living and dining finishes at Emerald City",
"Finisaje bucătărie la Emerald City": "Kitchen finishes at Emerald City",
"Finisaje dormitor la Emerald City": "Bedroom finishes at Emerald City",
"Finisaje grup sanitar la Emerald City": "Bathroom finishes at Emerald City",
"Finisaje hol și intrare la Emerald City": "Hallway and entrance finishes at Emerald City",
"Finisaje balcon și curte la Emerald City": "Balcony and garden finishes at Emerald City",
}
