# -*- coding: utf-8 -*-
# Hub /apartamente-iasi/, categorii (1/2/3 camere), compartimentari (tip), disponibilitate.
T = {
# ---- hub ------------------------------------------------------------------
"Apartamente noi în Iași, zona Păcurari | Emerald City": "New apartments in Iași, Păcurari area | Emerald City",
"Apartamente noi în Iași, zona Păcurari": "New apartments in Iași, Păcurari area",
"{n} apartamente disponibile acum, cu {n} {n} și {n} camere, între {n} și {n} m². Toate se predau complet finisate, cu prețuri afișate și vânzare directă de la dezvoltator.":
    "{n} apartments available now, with {n}, {n} and {n} rooms, between {n} and {n} m². All are handed over fully finished, with listed prices and direct sales by the developer.",
"Selecție după buget": "Selection by budget",
"Apartamente în ansamblu": "Apartments in the development",
"Disponibile acum": "Available now",
"Preț de pornire": "Starting price",
"Suprafață utilă": "Usable area",
"{n} — După camere": "{n} — By rooms",
"după numărul de camere": "by number of rooms",
"Trei categorii, cu disponibilitatea și prețul de pornire actualizate din tabelul de vânzări.": "Three categories, with availability and starting price updated from the sales ledger.",
"{n} disponibile": "{n} available",
"Apartamente {n} cameră": "{n}-room apartments",
"{n} m² – {n} m²": "{n} m² – {n} m²",
"Total unități": "Total units",
"preț de pornire": "starting price",
"{n}A, {n}B": "{n}A, {n}B",
"{n} — După buget": "{n} — By budget",
"după buget": "by budget",
"Patru praguri de preț, cu numărul de apartamente din fiecare. Fiecare prag deschide lista filtrată corespunzător.": "Four price bands, with the number of apartments in each. Each band opens the correspondingly filtered list.",
"Sub {n} €": "Under €{n}",
"apartamente": "apartments",
"Garsoniere și {n} camere la etajele inferioare": "Studios and {n}-room units on the lower floors",
"Cele mai multe apartamente de {n} camere": "Most of the {n}-room apartments",
"{n} camere generoase și {n} camere": "Generous {n}-room units and {n}-room units",
"Peste {n} €": "Over €{n}",
"{n} camere cu două grupuri sanitare și curte": "{n}-room units with two bathrooms and a garden",
"{n} — Compartimentări": "{n} — Layouts",
"{n} planuri": "{n} floor",
"de apartament": "plans",
"De la garsonieră la {n} camere cu două grupuri sanitare. Fiecare cu planul, suprafețele și disponibilitatea proprie.": "From studio to {n} rooms with two bathrooms. Each with its own plan, areas and availability.",
"Disponibile": "Available",
"Cât a mai": "What is left",
"rămas din fiecare etapă": "in each phase",
"Ansamblul se construiește în trei etape. Procentul contractat se actualizează din tabelul de vânzări.": "The development is built in three phases. The contracted percentage is updated from the sales ledger.",
"de la": "from",
"din {n} încă disponibile": "of {n} still available",
"{n}% contractate": "{n}% contracted",
"{n} apartamente, în curând în vânzare": "{n} apartments, on sale soon",
"Nu a intrat în vânzare": "Not yet on sale",
"{n} — Curte proprie": "{n} — Private garden",
"cu curte la parter": "with a garden on the ground floor",
"Între {n} și {n} m² de curte, în folosință exclusivă. Configurație rar întâlnită într-un ansamblu de această dimensiune.": "Between {n} and {n} m² of garden, for exclusive use. A configuration rarely found in a development of this size.",
"În ansamblu": "In the development",
"Suprafață curte": "Garden area",
"Apartamentele cu curte": "Apartments with a garden",
"{n} — Cel mai bun raport": "{n} — Best value",
"Cele mai bune": "The best",
"prețuri pe metru pătrat": "prices per square metre",
"Șase apartamente disponibile, selectate automat după cel mai mic preț pe metru pătrat din ansamblu.": "Six available apartments, selected automatically by the lowest price per square metre in the development.",
"C{n}-P-{n}": "C{n}-P-{n}",
"C{n}-E{n}": "C{n}-E{n}",
"{n} camere · {n} m²": "{n} rooms · {n} m²",
"{n} cameră · {n} m²": "{n} room · {n} m²",
"Toate cele {n} apartamente disponibile": "All {n} available apartments",
"{n} — Avantaje": "{n} — Advantages",
"un apartament nou aici": "a new apartment here",
"Patru argumente verificabile, nu promisiuni.": "Four verifiable arguments, not promises.",
"Apartamentul nu se predă la gri, ci finisat, cu materiale alese de un birou de design.": "The apartment is not handed over as a shell but finished, with materials selected by a design studio.",
"Parcare la subsol": "Basement parking",
"{n} de locuri subterane din {n} în total. Mașina nu stă între blocuri, iar spațiul dintre clădiri rămâne verde.": "{n} underground spaces out of {n} in total. Cars do not sit between buildings, and the space between them stays green.",
"Direct de la dezvoltator": "Direct from the developer",
"Fără comision de intermediere. Discuți cu cine construiește, nu cu un agent care revinde.": "No agency commission. You talk to the builder, not to an agent reselling.",
"Aproape o treime verde": "Almost a third green",
"{n} m² de spațiu verde amenajat, parc dendrologic și loc de joacă, pe cinci hectare.": "{n} m² of landscaped green space, an arboretum park and a playground, on five hectares.",
"Dotările incluse în fiecare locuință și facilitățile de folosință comună.": "The features included in every home and the shared amenities.",
"Dotări apartament": "Apartment features",
"Finisaje premium incluse în preț": "Premium finishes included in the price",
"Boxă de depozitare la demisol": "Storage room in the basement",
"Videointerfon și acces controlat": "Video intercom and controlled access",
"Lift în fiecare bloc": "A lift in every building",
"Contorizare individuală a consumurilor": "Individual metering of utilities",
"Facilități ansamblu": "Development amenities",
"Parc dendrologic amenajat": "Landscaped arboretum park",
"Loc de joacă pentru copii": "Children's playground",
"Alei pietonale între blocuri": "Footpaths between buildings",
"Iluminat exterior integrat": "Integrated outdoor lighting",
"Acces din Strada Ion Nistor": "Access from Strada Ion Nistor",
"{n} km până în centrul Iașului": "{n} km to Iași city centre",
"Lista completă a dotărilor în preț": "The full list of features in the price",
"Despre apartamente": "About the apartments",
"și achiziție": "and buying",
"{n} întrebări despre suprafețe, prețuri și modul de cumpărare.": "{n} questions about areas, prices and how to buy.",
"Câte apartamente sunt disponibile acum?": "How many apartments are available now?",
"Numărul afișat pe această pagină se actualizează din tabelul de vânzări. Lista completă, cu filtre după camere, buget, etaj și bloc, este la secțiunea de disponibilitate.": "The number shown on this page is updated from the sales ledger. The full list, with filters by rooms, budget, floor and building, is in the availability section.",
"Între {n} și {n} m² suprafață utilă. Fiecare apartament are balcon, iar cele de la parter au curte proprie, între {n} și {n} m².": "Between {n} and {n} m² of usable area. Every apartment has a balcony, and ground-floor units have a private garden, between {n} and {n} m².",
"Prețurile afișate includ TVA?": "Do the listed prices include VAT?",
"Da. Prețurile de pe site includ TVA și toate finisajele. Nu există costuri suplimentare pentru execuția lor.": "Yes. Prices on the site include VAT and all finishes. There are no extra costs for their installation.",
"Ce înseamnă preț de pornire?": "What does starting price mean?",
"Cel mai mic preț dintre apartamentele disponibile din categoria respectivă, la data actualizării. Prețul fiecărei unități este afișat individual în listă.": "The lowest price among the available apartments in that category, as of the last update. Each unit's price is shown individually in the list.",
"Da. Apartamentele se pot achiziționa cu credit ipotecar standard, iar cele care se încadrează în plafon pot fi cumpărate și prin Noua Casă.": "Yes. Apartments can be bought with a standard mortgage, and those within the ceiling can also be bought through the Noua Casă scheme.",
"Ce avans se cere?": "What deposit is required?",
"Nu. Vânzarea se face direct de la dezvoltator, fără comision de agenție.": "No. Sales are made directly by the developer, with no agency commission.",
"Pot rezerva un apartament?": "Can I reserve an apartment?",
"Da. Apartamentul se blochează pe numele cumpărătorului, iar prețul se menține pe perioada rezervării. Termenul se stabilește la biroul de vânzări.": "Yes. The apartment is held in the buyer's name and the price is maintained for the reservation period. The term is agreed at the sales office.",
"Ce apartamente se predau primele?": "Which apartments are handed over first?",
"Cele din Etapa I, blocurile {n} Termenul fiecărei etape se înscrie în antecontract.": "Those in Phase I, buildings {n}. Each phase's deadline is written into the pre-sale agreement.",
"Pot vedea un apartament înainte de a cumpăra?": "Can I see an apartment before buying?",
"Da. La biroul de vânzări se poate vizita apartamentul-model și se pot consulta planurile fiecărei compartimentări.": "Yes. The show apartment can be visited at the sales office and the plans of each layout can be consulted.",
"{n} apartamente noi în Iași, zona Păcurari: {n} {n} și {n} camere, {n} m², de la {n} €. Predare la cheie, direct de la dezvoltator.": "{n} new apartments in Iași, Păcurari area: {n}, {n} and {n} rooms, {n} m², from €{n}. Turnkey handover, direct from the developer.",
"Apartamente {n} cameră în Emerald City": "{n}-room apartments at Emerald City",
"Apartamente {n} camere în Emerald City": "{n}-room apartments at Emerald City",
# ---- categorii ------------------------------------------------------------
"Apartamente {n} cameră în Iași — {n} libere | Emerald City": "{n}-room apartments in Iași — {n} available | Emerald City",
"Apartamente {n} camere în Iași — {n} libere | Emerald City": "{n}-room apartments in Iași — {n} available | Emerald City",
"Apartamente {n} cameră în Iași, zona Păcurari": "{n}-room apartments in Iași, Păcurari area",
"Apartamente {n} camere în Iași, zona Păcurari": "{n}-room apartments in Iași, Păcurari area",
"Garsoniere compacte, cu zona de zi deschisă și bucătărie integrată. Potrivite pentru prima locuință sau pentru investiție — cel mai cerut format pe piața de închirieri din Iași.":
    "Compact studios with an open living area and integrated kitchen. Suited to a first home or an investment — the most sought-after format on the Iași rental market.",
"Living deschis spre bucătărie și dormitor separat. Formatul cel mai echilibrat între spațiu și preț, potrivit pentru cupluri și familii tinere.": "An open-plan living room and kitchen with a separate bedroom. The most balanced format between space and price, suited to couples and young families.",
"Două dormitoare, două băi și zonă de zi generoasă. Pentru familii care au nevoie de o cameră în plus, de birou sau de spațiu pentru copii.": "Two bedrooms, two bathrooms and a generous living area. For families that need an extra room, a study or space for children.",
"Cele {n} apartamente disponibile": "The {n} available apartments",
"De la": "From",
"{n} tip de apartament": "{n} apartment type",
"{n} tipuri de apartament": "{n} apartment types",
"disponibil": "available",
"disponibile": "available",
"Suprafețele, disponibilitatea și prețul de pornire pentru fiecare compartimentare.": "Areas, availability and starting price for each layout.",
"Compartimentare": "Layout",
"Tip {n}A": "Type {n}A",
"Tip {n}B": "Type {n}B",
"Garsonieră compactă, cu zona de zi deschisă și bucătărie integrată.": "A compact studio with an open living area and integrated kitchen.",
"Două camere, cu living deschis spre bucătărie și dormitor separat.": "Two rooms, with an open-plan living room and kitchen and a separate bedroom.",
"Două camere, cu dormitor mai generos și spațiu suplimentar de depozitare.": "Two rooms, with a larger bedroom and extra storage space.",
"Trei camere, cu bucătărie închisă, două dormitoare și două grupuri sanitare.": "Three rooms, with a closed kitchen, two bedrooms and two bathrooms.",
"Trei camere, cu living deschis, dormitor și o a treia cameră pentru birou.": "Three rooms, with an open-plan living room, a bedroom and a third room for a study.",
"{n} din {n}": "{n} of {n}",
"Planul complet": "Full floor plan",
"Unitățile de tip {n}A": "Type {n}A units",
"Unitățile de tip {n}B": "Type {n}B units",
"Apartamentul-model,": "The show apartment,",
"în imagini": "in pictures",
"Randări din apartamentele-model, cu finisajele incluse în preț.": "Renders of the show apartments, with the finishes included in the price.",
"{n} — Selecție rapidă": "{n} — Quick selection",
"Selecție": "Selection",
"după etaj și dotări": "by floor and features",
"Fiecare rând deschide lista filtrată. Numărul reprezintă apartamentele disponibile la data actualizării.": "Each row opens the filtered list. The number is the apartments available as of the last update.",
"După etaj": "By floor",
"Nivelul apartamentului": "Apartment level",
"După dotări": "By features",
"Curte, boxă, parcare": "Garden, storage room, parking",
"Curte proprie": "Private garden",
"Boxă de depozitare": "Storage room",
"{n} — Unități": "{n} — Units",
"Toate apartamentele": "All apartments",
"de {n} cameră": "with {n} room",
"de {n} camere": "with {n} rooms",
"Primele {n} de unități, ordonate după preț. Lista completă, cu filtre, este în secțiunea de disponibilitate.": "The first {n} units, sorted by price. The full list, with filters, is in the availability section.",
"Apartamente de {n} cameră": "{n}-room apartments",
"Apartamente de {n} camere": "{n}-room apartments",
"Lista completă, cu filtre": "The full list, with filters",
"Cele {n} cu curte proprie": "The {n} with a private garden",
"{n} apartamente cu curte, la parter": "{n} apartments with a garden, on the ground floor",
"Curte în folosință exclusivă, între {n} și {n} m², cu pardoseală exterioară executată și priză proprie. Configurație rar întâlnită la această suprafață.": "A garden for exclusive use, between {n} and {n} m², with outdoor flooring laid and its own socket. A configuration rarely found at this size.",
"Acces direct din living, fără scări": "Direct access from the living room, no stairs",
"Pardoseală exterioară antiderapantă, montată": "Non-slip outdoor flooring, laid",
"Balustradă și priză exterioară incluse": "Railing and outdoor socket included",
"Preț de pornire {n} €": "Starting price €{n}",
"Cele {n} apartamente": "The {n} apartments",
"apartamente {n} cameră": "{n}-room apartments",
"apartamente {n} camere": "{n}-room apartments",
"Patru criterii pentru care această compartimentare este cea potrivită.": "Four reasons this layout is the right one.",
"Cea mai cerută la închiriere": "Most in demand for renting",
"Garsonierele au cel mai scurt timp de ocupare pe piața de închirieri din Iași, susținută de apropierea de centrul universitar.": "Studios have the shortest time to let on the Iași rental market, supported by the proximity to the university district.",
"Prag de intrare redus": "Low entry price",
"Cel mai mic preț de achiziție din ansamblu, cu aceleași finisaje și aceleași dotări comune ca la celelalte compartimentări.": "The lowest purchase price in the development, with the same finishes and the same shared amenities as the other layouts.",
"Zonă de zi deschisă": "Open living area",
"Bucătăria integrată în living folosește eficient suprafața și lasă senzația de spațiu mai amplu decât o compartimentare închisă.": "The kitchen integrated into the living room uses the area efficiently and feels more spacious than a closed layout.",
"Prima locuință": "First home",
"Se încadrează în plafonul programului Noua Casă și poate fi achiziționată și prin credit ipotecar standard.": "It falls within the Noua Casă scheme's ceiling and can also be bought with a standard mortgage.",
"Despre": "About",
"{n} întrebări despre suprafețe, compartimentări, dotări și condiții.": "{n} questions about areas, layouts, features and terms.",
"Ce suprafață are o garsonieră?": "How big is a studio?",
"Între {n} și {n} m² suprafață utilă, cu balcon. Cele de la parter au și curte proprie.": "Between {n} and {n} m² of usable area, with a balcony. Ground-floor units also have a private garden.",
"Sunt potrivite pentru investiție?": "Are they suitable as an investment?",
"Da. Garsonierele au cel mai scurt timp de ocupare pe piața de închirieri din Iași, iar pagina de investiție include un calculator de randament și de amortizare.": "Yes. Studios have the shortest time to let on the Iași rental market, and the investment page includes a yield and payback calculator.",
"Se încadrează în programul Noua Casă?": "Do they qualify for the Noua Casă scheme?",
"Prețurile de pornire se situează sub plafonul programului. Încadrarea exactă se verifică la data achiziției, împreună cu banca.": "Starting prices are below the scheme's ceiling. Exact eligibility is checked at the time of purchase, together with the bank.",
"Ce compartimentare au?": "What layout do they have?",
"Tipul {n}A: zonă de zi deschisă, cu bucătăria integrată în living, grup sanitar și spațiu de depozitare.": "Type {n}A: an open living area with the kitchen integrated into the living room, a bathroom and storage space.",
"Există garsoniere cu curte proprie?": "Are there studios with a private garden?",
"Da, cele de la parter. Curtea este în folosință exclusivă, cu pardoseală exterioară executată și priză proprie.": "Yes, those on the ground floor. The garden is for exclusive use, with outdoor flooring laid and its own socket.",
"Se poate cumpăra prin credit ipotecar?": "Can it be bought with a mortgage?",
"Da, cu credit ipotecar standard sau, în limita plafonului, prin programul Noua Casă. Avansul minim la antecontract este de {n}%.": "Yes, with a standard mortgage or, within the ceiling, through the Noua Casă scheme. The minimum deposit at the pre-sale agreement is {n}%.",
"Ce cheltuieli de întreținere are o garsonieră?": "What are the running costs of a studio?",
"Consumurile sunt contorizate individual, iar încălzirea în pardoseală cu centrală în condensație menține costurile reduse. Cheltuielile comune se stabilesc prin asociația de proprietari.": "Utilities are metered individually, and underfloor heating with a condensing boiler keeps costs low. Service charges are set by the owners' association.",
"Ce chirie se poate obține?": "What rent can be achieved?",
"Estimarea depinde de etaj, de dotările contractate și de momentul închirierii. Pagina de investiție include un calculator care pornește de la prețul fiecărei unități și de la chiriile practicate în zonă.": "The estimate depends on the floor, the contracted features and the time of letting. The investment page includes a calculator based on each unit's price and the rents observed in the area.",
"{n} apartamente {n} cameră disponibile în Iași, zona Păcurari, între {n} și {n} m², de la {n} €. Predare la cheie, vânzare directă de la dezvoltator.": "{n} {n}-room apartments available in Iași, Păcurari area, between {n} and {n} m², from €{n}. Turnkey handover, direct sales by the developer.",
"{n} apartamente {n} camere disponibile în Iași, zona Păcurari, între {n} și {n} m², de la {n} €. Predare la cheie, vânzare directă de la dezvoltator.": "{n} {n}-room apartments available in Iași, Păcurari area, between {n} and {n} m², from €{n}. Turnkey handover, direct sales by the developer.",
"Apartament tip {n}A la Emerald City": "Type {n}A apartment at Emerald City",
"Apartament tip {n}B la Emerald City": "Type {n}B apartment at Emerald City",
"Living — Apartamente {n} cameră în Iași, zona Păcurari, Emerald City": "Living room — {n}-room apartments in Iași, Păcurari area, Emerald City",
"Bucătărie — Apartamente {n} cameră în Iași, zona Păcurari, Emerald City": "Kitchen — {n}-room apartments in Iași, Păcurari area, Emerald City",
"Grup sanitar — Apartamente {n} cameră în Iași, zona Păcurari, Emerald City": "Bathroom — {n}-room apartments in Iași, Păcurari area, Emerald City",
"Living — Apartamente {n} camere în Iași, zona Păcurari, Emerald City": "Living room — {n}-room apartments in Iași, Păcurari area, Emerald City",
"Dormitor — Apartamente {n} camere în Iași, zona Păcurari, Emerald City": "Bedroom — {n}-room apartments in Iași, Păcurari area, Emerald City",
"Hol — Apartamente {n} camere în Iași, zona Păcurari, Emerald City": "Hallway — {n}-room apartments in Iași, Păcurari area, Emerald City",
"Dining — Apartamente {n} camere în Iași, zona Păcurari, Emerald City": "Dining — {n}-room apartments in Iași, Păcurari area, Emerald City",
"Apartament cu curte proprie la parter": "Ground-floor apartment with a private garden",
"Formatul cel mai echilibrat": "The most balanced format",
"Living deschis spre bucătărie și dormitor separat — raportul cel mai bun între suprafață utilă și preț din tot ansamblului.": "An open-plan living room and kitchen with a separate bedroom — the best ratio of usable area to price in the whole development.",
"Living deschis spre bucătărie și dormitor separat — raportul cel mai bun între suprafață utilă și preț din tot ansamblul.": "An open-plan living room and kitchen with a separate bedroom — the best ratio of usable area to price in the whole development.",
"Cerere constantă": "Steady demand",
"Compartimentarea cu cea mai stabilă cerere, atât la vânzare cât și la închiriere, pe piața rezidențială din Iași.": "The layout with the most stable demand, for both sale and rent, on the Iași residential market.",
"Curte proprie la parter": "Private garden on the ground floor",
"Apartamentele de la parter au curte în folosință exclusivă, o configurație rar întâlnită la această suprafață.": "Ground-floor apartments have a garden for exclusive use, a configuration rarely found at this size.",
"Două compartimentări": "Two layouts",
"Tipurile {n}A și {n}B diferă prin dimensiunea dormitorului și prin spațiul de depozitare, la aceeași zonă de zi.": "Types {n}A and {n}B differ in bedroom size and storage space, with the same living area.",
"Ce diferență este între tipurile {n}A și {n}B?": "What is the difference between types {n}A and {n}B?",
"{n}B are dormitorul mai generos și spațiu suplimentar de depozitare, la aceeași configurație a zonei de zi. Suprafețele diferă cu câțiva metri pătrați.": "{n}B has a larger bedroom and extra storage space, with the same living area configuration. Areas differ by a few square metres.",
"Ce suprafață are un apartament de {n} camere?": "How big is a {n}-room apartment?",
"Între {n} și {n} m² suprafață utilă, în funcție de compartimentare. Toate au balcon.": "Between {n} and {n} m² of usable area, depending on the layout. All have a balcony.",
"Care sunt cele cu curte proprie?": "Which ones have a private garden?",
"Cele de la parter. Curțile au între {n} și {n} m² și sunt în folosință exclusivă.": "Those on the ground floor. Gardens are between {n} and {n} m² and for exclusive use.",
"Este potrivit pentru o familie cu un copil?": "Is it suitable for a family with one child?",
"Da. Dormitorul separat și zona de zi deschisă acoperă nevoile unei familii tinere, iar ansamblul are loc de joacă și spații verzi amenajate.": "Yes. The separate bedroom and open living area meet the needs of a young family, and the development has a playground and landscaped green spaces.",
"Ce înseamnă boxă de depozitare?": "What is a storage room?",
"Un spațiu propriu în al doilea demisol, pentru bagaje, biciclete și lucrurile de sezon. Se contractează separat, în limita disponibilității din bloc.": "A private space on the second basement level, for luggage, bicycles and seasonal items. It is contracted separately, subject to availability in the building.",
"Care este avansul la antecontract?": "What is the deposit at the pre-sale agreement?",
"{n}% din preț, la semnarea antecontractului la notar. Diferența se achită la predare sau conform graficului agreat.": "{n}% of the price, when the pre-sale agreement is signed before the notary. The balance is paid on handover or according to the agreed schedule.",
"Când se predau apartamentele de {n} camere?": "When are the {n}-room apartments handed over?",
"În funcție de etapa în care se află blocul. Termenul de predare se înscrie în antecontract, pentru fiecare unitate.": "Depending on the phase the building is in. The handover date is written into the pre-sale agreement for each unit.",
"Are loc de parcare inclus?": "Is a parking space included?",
"Locul de parcare se contractează separat, subteran sau la suprafață. Ansamblul are {n} de locuri, dintre care {n} subterane.": "The parking space is contracted separately, underground or at surface level. The development has {n} spaces, {n} of them underground.",
"Spațiu pentru o familie": "Space for a family",
"Două dormitoare, două grupuri sanitare și zonă de zi generoasă — configurația care acoperă nevoile unei familii pe termen lung.": "Two bedrooms, two bathrooms and a generous living area — the configuration that meets a family's needs in the long run.",
"Două grupuri sanitare": "Two bathrooms",
"Un al doilea grup sanitar elimină punctul de blocaj de dimineață, cel mai frecvent reproș adus apartamentelor de trei camere mai vechi.": "A second bathroom removes the morning bottleneck, the most common complaint about older three-room apartments.",
"Cameră pentru birou": "Room for a study",
"Tipul {n}B include o a treia cameră care poate fi folosită ca birou, fără să reducă spațiul de locuit.": "Type {n}B includes a third room that can be used as a study, without reducing the living space.",
"Cele mai mari suprafețe": "The largest areas",
"Cele mai generoase apartamente din ansamblu, cu balcoane pe măsură și curte la parter.": "The most generous apartments in the development, with balconies to match and a garden on the ground floor.",
"{n}A are bucătărie închisă și două dormitoare. {n}B are living deschis, un dormitor și o a treia cameră care poate fi folosită ca birou. Ambele au două grupuri sanitare.": "{n}A has a closed kitchen and two bedrooms. {n}B has an open-plan living room, one bedroom and a third room that can be used as a study. Both have two bathrooms.",
"Au două grupuri sanitare?": "Do they have two bathrooms?",
"Da, ambele compartimentări de trei camere includ două grupuri sanitare complet finisate și echipate.": "Yes, both three-room layouts include two fully finished and equipped bathrooms.",
"Există apartamente de {n} camere cu curte?": "Are there {n}-room apartments with a garden?",
"Da, cele de la parter. Curțile au între {n} și {n} m², în folosință exclusivă.": "Yes, those on the ground floor. Gardens are between {n} and {n} m², for exclusive use.",
"Câte locuri de parcare pot contracta?": "How many parking spaces can I contract?",
"Numărul de locuri care pot fi contractate pentru un apartament se stabilește la biroul de vânzări, în funcție de disponibilitatea din blocul respectiv.": "The number of spaces that can be contracted per apartment is agreed at the sales office, depending on availability in that building.",
"Se pot uni sau modifica camerele?": "Can rooms be merged or changed?",
"Modificările nestructurale se analizează la biroul de vânzări, în funcție de faza de execuție a blocului. Pereții de rezistență nu se modifică.": "Non-structural changes are reviewed at the sales office, depending on the building's construction stage. Load-bearing walls are not changed.",
"Ce orientare au apartamentele de {n} camere?": "What orientation do the {n}-room apartments have?",
"Diferă de la o unitate la alta; orientarea fiecărui apartament este afișată în lista de disponibilitate și în pagina lui.": "It varies from unit to unit; each apartment's orientation is shown in the availability list and on its page.",
"Ce suprafață are balconul?": "How big is the balcony?",
"Balcoanele apartamentelor de trei camere sunt cele mai generoase din ansamblu. Suprafața exactă este afișată în pagina fiecărei unități.": "The balconies of the three-room apartments are the most generous in the development. The exact area is shown on each unit's page.",
# ---- compartimentari (tip) ------------------------------------------------
"Apartament {n} cameră tip {n}A, Iași Păcurari | Emerald City": "{n}-room apartment type {n}A, Iași Păcurari | Emerald City",
"Apartament {n} camere tip {n}A, Iași Păcurari | Emerald City": "{n}-room apartment type {n}A, Iași Păcurari | Emerald City",
"Apartament {n} camere tip {n}B, Iași Păcurari | Emerald City": "{n}-room apartment type {n}B, Iași Păcurari | Emerald City",
"Compartimentarea {n}A": "Layout {n}A",
"Compartimentarea {n}B": "Layout {n}B",
"Apartament {n} cameră tip {n}A, în Iași": "{n}-room apartment type {n}A, in Iași",
"Apartament {n} camere tip {n}A, în Iași": "{n}-room apartment type {n}A, in Iași",
"Apartament {n} camere tip {n}B, în Iași": "{n}-room apartment type {n}B, in Iași",
"Garsonieră compactă, cu zona de zi deschisă și bucătărie integrată. Între {n} și {n} m² suprafață utilă, cu {n} unități disponibile în acest moment.": "A compact studio with an open living area and integrated kitchen. Between {n} and {n} m² of usable area, with {n} units available right now.",
"Două camere, cu living deschis spre bucătărie și dormitor separat. Între {n} și {n} m² suprafață utilă, cu {n} unități disponibile în acest moment.": "Two rooms, with an open-plan living room and kitchen and a separate bedroom. Between {n} and {n} m² of usable area, with {n} units available right now.",
"Două camere, cu dormitor mai generos și spațiu suplimentar de depozitare. Între {n} și {n} m² suprafață utilă, cu {n} unități disponibile în acest moment.": "Two rooms, with a larger bedroom and extra storage space. Between {n} and {n} m² of usable area, with {n} units available right now.",
"Trei camere, cu bucătărie închisă, două dormitoare și două grupuri sanitare. Între {n} și {n} m² suprafață utilă, cu {n} unități disponibile în acest moment.": "Three rooms, with a closed kitchen, two bedrooms and two bathrooms. Between {n} and {n} m² of usable area, with {n} units available right now.",
"Trei camere, cu living deschis, dormitor și o a treia cameră pentru birou. Între {n} și {n} m² suprafață utilă, cu {n} unități disponibile în acest moment.": "Three rooms, with an open-plan living room, a bedroom and a third room for a study. Between {n} and {n} m² of usable area, with {n} units available right now.",
"Cele {n} unități disponibile": "The {n} available units",
"Planul compartimentării": "The layout plan",
"{n} — Planul": "{n} — The plan",
"Compartimentare apartament": "Apartment layout,",
"{n} cameră tip {n}A": "{n} room, type {n}A",
"{n} camere tip {n}A": "{n} rooms, type {n}A",
"{n} camere tip {n}B": "{n} rooms, type {n}B",
"Planul compartimentării, cu suprafețele pe cameră. Cotele exacte diferă de la o unitate la alta și se confirmă în anexa contractului.": "The layout plan, with the area of each room. Exact dimensions vary from unit to unit and are confirmed in the contract annex.",
"Suprafața fiecărei camere apare la trecerea cursorului peste numere. Cotele definitive se predau la semnarea antecontractului.": "Each room's area appears when hovering over the numbers. Final dimensions are provided when the pre-sale agreement is signed.",
"Suprafață totală": "Total area",
"Finisaje incluse în preț": "Finishes included in the price",
"în toate camerele": "in every room",
"economie până la {n}% la gaz": "up to {n}% gas savings",
"Tâmplărie PVC, {n} camere": "PVC windows, {n} chambers",
"geam tripan, sticlă Low-E": "triple glazing, Low-E glass",
"Parchet laminat {n} mm": "{n} mm laminate flooring",
"clasă de trafic intens": "heavy-traffic grade",
"Grup sanitar echipat": "Equipped bathroom",
"gresie, faianță, obiecte sanitare": "floor and wall tiles, sanitary ware",
"acces controlat în bloc și parcare": "controlled access to the building and car park",
"Randări din apartamentul-model de tip {n}A, cu finisajele incluse în preț.": "Renders of the type {n}A show apartment, with the finishes included in the price.",
"Randări din apartamentul-model de tip {n}B, cu finisajele incluse în preț.": "Renders of the type {n}B show apartment, with the finishes included in the price.",
"Apartament {n} cameră tip {n}A": "{n}-room apartment type {n}A",
"Apartament {n} camere tip {n}A": "{n}-room apartment type {n}A",
"Apartament {n} camere tip {n}B": "{n}-room apartment type {n}B",
"Fiecare rând deschide lista filtrată pe compartimentarea {n}A.": "Each row opens the list filtered by layout {n}A.",
"Fiecare rând deschide lista filtrată pe compartimentarea {n}B.": "Each row opens the list filtered by layout {n}B.",
"Apartamentele": "The apartments",
"de tip {n}A": "of type {n}A",
"de tip {n}B": "of type {n}B",
"{n} unități în ansamblu, ordonate după preț. Lista completă, cu filtre, este în secțiunea de disponibilitate.": "{n} units in the development, sorted by price. The full list, with filters, is in the availability section.",
"Apartamente de tip {n}A": "Type {n}A apartments",
"Apartamente de tip {n}B": "Type {n}B apartments",
"Ce recomandă": "What recommends",
"compartimentarea {n}A": "layout {n}A",
"compartimentarea {n}B": "layout {n}B",
"Patru criterii pentru care acest plan este cel potrivit.": "Four reasons this plan is the right one.",
"Spațiu de depozitare": "Storage space",
"Debaraua separată preia lucrurile de sezon, fără să ocupe din zona de zi.": "The separate storage closet takes seasonal items without eating into the living area.",
"Formatul cu cel mai scurt timp de ocupare pe piața de închirieri din Iași.": "The format with the shortest time to let on the Iași rental market.",
"Cel mai mic preț de achiziție din ansamblu, cu aceleași finisaje incluse.": "The lowest purchase price in the development, with the same finishes included.",
"Garsonieră compactă, cu zona de zi deschisă și bucătărie integrată. {n} m², {n} unități disponibile, de la {n} €. Iași, zona Păcurari.": "A compact studio with an open living area and integrated kitchen. {n} m², {n} units available, from €{n}. Iași, Păcurari area.",
"Două camere, cu living deschis spre bucătărie și dormitor separat. {n} m², {n} unități disponibile, de la {n} €. Iași, zona Păcurari.": "Two rooms, with an open-plan living room and kitchen and a separate bedroom. {n} m², {n} units available, from €{n}. Iași, Păcurari area.",
"Două camere, cu dormitor mai generos și spațiu suplimentar de depozitare. {n} m², {n} unități disponibile, de la {n} €. Iași, zona Păcurari.": "Two rooms, with a larger bedroom and extra storage space. {n} m², {n} units available, from €{n}. Iași, Păcurari area.",
"Trei camere, cu bucătărie închisă, două dormitoare și două grupuri sanitare. {n} m², {n} unități disponibile, de la {n} €. Iași, zona Păcurari.": "Three rooms, with a closed kitchen, two bedrooms and two bathrooms. {n} m², {n} units available, from €{n}. Iași, Păcurari area.",
"Trei camere, cu living deschis, dormitor și o a treia cameră pentru birou. {n} m², {n} unități disponibile, de la {n} €. Iași, zona Păcurari.": "Three rooms, with an open-plan living room, a bedroom and a third room for a study. {n} m², {n} units available, from €{n}. Iași, Păcurari area.",
"Living — Apartament {n} cameră tip {n}A, Emerald City Iași": "Living room — {n}-room apartment type {n}A, Emerald City Iași",
"Bucătărie — Apartament {n} cameră tip {n}A, Emerald City Iași": "Kitchen — {n}-room apartment type {n}A, Emerald City Iași",
"Grup sanitar — Apartament {n} cameră tip {n}A, Emerald City Iași": "Bathroom — {n}-room apartment type {n}A, Emerald City Iași",
"Living — Apartament {n} camere tip {n}A, Emerald City Iași": "Living room — {n}-room apartment type {n}A, Emerald City Iași",
"Dormitor — Apartament {n} camere tip {n}A, Emerald City Iași": "Bedroom — {n}-room apartment type {n}A, Emerald City Iași",
"Hol — Apartament {n} camere tip {n}A, Emerald City Iași": "Hallway — {n}-room apartment type {n}A, Emerald City Iași",
"Dining — Apartament {n} camere tip {n}A, Emerald City Iași": "Dining — {n}-room apartment type {n}A, Emerald City Iași",
"Living — Apartament {n} camere tip {n}B, Emerald City Iași": "Living room — {n}-room apartment type {n}B, Emerald City Iași",
"Dining — Apartament {n} camere tip {n}B, Emerald City Iași": "Dining — {n}-room apartment type {n}B, Emerald City Iași",
"Grup sanitar — Apartament {n} camere tip {n}B, Emerald City Iași": "Bathroom — {n}-room apartment type {n}B, Emerald City Iași",
"Bucătărie — Apartament {n} camere tip {n}B, Emerald City Iași": "Kitchen — {n}-room apartment type {n}B, Emerald City Iași",
"Hol — Apartament {n} camere tip {n}B, Emerald City Iași": "Hallway — {n}-room apartment type {n}B, Emerald City Iași",
"Dormitor separat": "Separate bedroom",
"Zona de noapte este despărțită complet de zona de zi, fără uși de trecere.": "The sleeping area is fully separated from the living area, with no through doors.",
"Living deschis spre bucătărie": "Open-plan living room and kitchen",
"O singură zonă continuă pentru gătit, masă și relaxare.": "A single continuous space for cooking, dining and relaxing.",
"Raport echilibrat": "Balanced ratio",
"Cel mai bun raport între suprafață utilă și preț din tot ansamblul.": "The best ratio of usable area to price in the whole development.",
"Compartimentarea cu cea mai stabilă cerere pe piața din Iași.": "The layout with the most stable demand on the Iași market.",
"{n} — Alternative": "{n} — Alternatives",
"Cealaltă compartimentare": "The other layout",
"Aceeași categorie, alt plan. Diferă suprafețele și organizarea camerelor.": "Same category, different plan. Areas and room arrangement differ.",
"Vezi compartimentarea {n}B": "See layout {n}B",
"Vezi compartimentarea {n}A": "See layout {n}A",
"Plan apartament tip {n}A": "Type {n}A apartment floor plan",
"Plan apartament tip {n}B": "Type {n}B apartment floor plan",
"Living și bucătărie &middot; {n} m²": "Living room and kitchen &middot; {n} m²",
"Birou &middot; {n} m²": "Study &middot; {n} m²",
"Baie &middot; {n} m²": "Bathroom &middot; {n} m²",
"Hol de intrare &middot; {n} m²": "Entrance hall &middot; {n} m²",
"Living &middot; {n} m²": "Living room &middot; {n} m²",
"Dormitor {n} &middot; {n} m²": "Bedroom {n} &middot; {n} m²",
"Bucătărie &middot; {n} m²": "Kitchen &middot; {n} m²",
"Vestibul &middot; {n} m²": "Vestibule &middot; {n} m²",
"Dormitor &middot; {n} m²": "Bedroom &middot; {n} m²",
"Balcon &middot; {n} m²": "Balcony &middot; {n} m²",
"Hol &middot; {n} m²": "Hallway &middot; {n} m²",
"Debara &middot; {n} m²": "Storage &middot; {n} m²",
"Dormitor mai generos": "Larger bedroom",
"Câțiva metri pătrați în plus față de {n}A, suficienți pentru un pat dublu și un dulap pe toată lățimea peretelui.": "A few square metres more than {n}A, enough for a double bed and a wardrobe across the full width of the wall.",
"Depozitare suplimentară": "Extra storage",
"Spațiu de depozitare peste cel standard, util pentru familii.": "More storage space than standard, useful for families.",
"Zonă de zi amplă": "Ample living area",
"Living deschis spre bucătărie, cu loc pentru masă de patru persoane.": "An open-plan living room and kitchen, with room for a table for four.",
"Cea mai mare suprafață de {n} camere": "The largest {n}-room area",
"Până la {n} m² utili, la un preț pe metru pătrat comparabil.": "Up to {n} m² of usable area, at a comparable price per square metre.",
"Al doilea grup sanitar elimină punctul de blocaj de dimineață.": "The second bathroom removes the morning bottleneck.",
"Bucătărie închisă": "Closed kitchen",
"Zonă de gătit separată, fără mirosuri și zgomot în living.": "A separate cooking area, with no smells or noise in the living room.",
"Două dormitoare": "Two bedrooms",
"Configurația clasică pentru o familie cu unul sau doi copii.": "The classic configuration for a family with one or two children.",
"Suprafețe generoase": "Generous areas",
"Între {n} și {n} m² utili, cu balcon pe măsură.": "Between {n} and {n} m² of usable area, with a balcony to match.",
"A treia cameră poate fi folosită ca birou, fără să reducă spațiul de locuit.": "The third room can be used as a study, without reducing the living space.",
"Ambele complet finisate și echipate, incluse în preț.": "Both fully finished and equipped, included in the price.",
"Living deschis": "Open-plan living room",
"Zona de zi continuă, cu bucătăria integrată, pentru o senzație de amplitudine.": "A continuous living area with an integrated kitchen, for a sense of space.",
"Până la {n} m² utili, cele mai spațioase apartamente din ansamblu.": "Up to {n} m² of usable area, the most spacious apartments in the development.",
# ---- disponibilitate ------------------------------------------------------
"Disponibilitate și prețuri — apartamente Iași | Emerald City": "Availability and prices — apartments in Iași | Emerald City",
"Toate apartamentele, cu prețuri afișate": "All apartments, with listed prices",
"{n} de apartamente cu {n} {n} și {n} camere, actualizate din tabelul de vânzări. Filtrele se aplică instant, fără reîncărcarea paginii, iar fiecare unitate are pagina ei, cu plan și preț.":
    "{n} apartments with {n}, {n} and {n} rooms, updated from the sales ledger. Filters apply instantly, without reloading the page, and every unit has its own page, with plan and price.",
"Filtrare și listă": "Filters and list",
"{n} — Filtre": "{n} — Filters",
"după criterii": "by criteria",
"Camere, etaj, etapă, compartimentare, buget, dotări, orientare și bloc. Criteriile active se pot elimina individual.": "Rooms, floor, phase, layout, budget, features, orientation and building. Active criteria can be removed individually.",
"Filtre": "Filters",
"Resetare": "Reset",
"Etapa de construcție": "Construction phase",
"Preț maxim": "Maximum price",
"Suprafață utilă minimă": "Minimum usable area",
"{n} — Rezultate": "{n} — Results",
"Lista": "The list",
"apartamentelor": "of apartments",
"Fiecare rând deschide pagina unității, cu planul, galeria și simularea de rată.": "Each row opens the unit's page, with the plan, the gallery and the mortgage simulation.",
"Sortare": "Sort",
"Preț crescător": "Price, low to high",
"Preț descrescător": "Price, high to low",
"Preț/m² crescător": "Price/m², low to high",
"Suprafață descrescătoare": "Area, large to small",
"Suprafață crescătoare": "Area, small to large",
"Etaj crescător": "Floor, low to high",
"Tabel": "Table",
"Carduri": "Cards",
"Încă {n} de apartamente": "{n} more apartments",
"Toate cele {n} de apartamente din Emerald City, Iași zona Păcurari, cu prețuri afișate. Filtre după camere, etaj, buget, dotări și bloc.": "All {n} apartments at Emerald City, Iași Păcurari area, with listed prices. Filters by rooms, floor, budget, features and building.",
"Cod, bloc, etaj sau „{n} camere etaj {n}”": "Code, building, floor or “{n} rooms floor {n}”",
"Căutare în listă": "Search the list",
"Mod de afișare": "Display mode",
"Etapa": "Phase",
}
