# -*- coding: utf-8 -*-
# Investitie, Comparator, Contact, Programare vizionare.
T = {
# ---- investitie -----------------------------------------------------------
"Investiție în apartamente noi în Iași — randament | Emerald City": "Investing in new apartments in Iași — yield | Emerald City",
"Investiție în apartamente noi, în Iași": "Investing in new apartments in Iași",
"{n} de garsoniere și {n} de apartamente cu {n} și {n} camere disponibile, la prețuri afișate. Calculator de randament, selecția celor mai bune unități și costurile care trebuie luate în calcul înainte de achiziție.":
    "{n} studios and {n} apartments with {n} and {n} rooms available, at listed prices. A yield calculator, a selection of the best units and the costs to take into account before buying.",
"Cele mai bune randamente": "Best yields",
"Apartamente disponibile": "Apartments available",
"până la {n}%": "up to {n}%",
"Randament brut estimat": "Estimated gross yield",
"Chirie lunară estimată": "Estimated monthly rent",
"{n} — Calculator": "{n} — Calculator",
"Randamentul": "The yield",
"unei achiziții": "of a purchase",
"Prețul, chiria și gradul de neocupare se ajustează liber. Rezultatele se recalculează instant și sunt orientative.": "Price, rent and vacancy rate can be adjusted freely. Results are recalculated instantly and are indicative.",
"Estimare orientativă pentru o achiziție destinată închirierii.": "An indicative estimate for a buy-to-let purchase.",
"Preț de achiziție": "Purchase price",
"Perioade neînchiriat": "Vacancy",
"Randament brut": "Gross yield",
"Randament net": "Net yield",
"Amortizare": "Payback",
"Randamentul net scade din chiria anuală perioadele neînchiriate și aproximativ {n}% cheltuieli de administrare, impozit și reparații. Chiriile sunt estimări de piață pentru zona Păcurari, nu valori garantate.":
    "The net yield deducts vacancy periods and about {n}% for management, tax and repairs from the annual rent. Rents are market estimates for the Păcurari area, not guaranteed values.",
"Metoda de calcul": "Calculation method",
"{n} ipoteze": "{n} assumptions",
"Chirie estimată la circa {n} €/m² util pe lună": "Rent estimated at about €{n}/m² of usable area per month",
"Grad de neocupare configurabil, implicit {n}% pe an": "Configurable vacancy rate, {n}% per year by default",
"Cheltuieli de administrare, impozit și reparații: circa {n}%": "Management, tax and repairs: about {n}%",
"Randament brut = chirie anuală / preț de achiziție": "Gross yield = annual rent / purchase price",
"Amortizare = preț de achiziție / venit net anual": "Payback = purchase price / annual net income",
"Taxe notariale, mobilare și TVA nu sunt incluse": "Notary fees, furnishing and VAT are not included",
"{n} — Scenarii": "{n} — Scenarios",
"Trei profiluri": "Three rental",
"de închiriere": "profiles",
"Pentru fiecare număr de camere, cea mai accesibilă unitate disponibilă și cifrele ei orientative.": "For each number of rooms, the most affordable available unit and its indicative figures.",
"Garsonieră": "Studio",
"Student sau tânăr angajat": "Student or young professional",
"randament brut estimat": "estimated gross yield",
"Unitate de referință": "Reference unit",
"C{n}-P-{n} · {n} m²": "C{n}-P-{n} · {n} m²",
"C{n}-E{n} · {n} m²": "C{n}-E{n} · {n} m²",
"Randament net orientativ": "Indicative net yield",
"Amortizare orientativă": "Indicative payback",
"Disponibile în această categorie": "Available in this category",
"Simulare cu aceste valori": "Simulate with these values",
"Cuplu tânăr sau doi colegi": "Young couple or two flatmates",
"Familie sau relocare corporate": "Family or corporate relocation",
"{n} — Selecție": "{n} — Selection",
"Top {n}": "Top {n}",
"randamente estimate": "estimated yields",
"Ordonate după randamentul brut. Fiecare cod deschide pagina unității, cu plan, galerie și simulare de rată.": "Sorted by gross yield. Each code opens the unit's page, with plan, gallery and mortgage simulation.",
"Apartamente ordonate după randamentul brut estimat": "Apartments sorted by estimated gross yield",
"Poziție": "Position",
"Chirie estimată": "Estimated rent",
"{n} camere · tip {n}A": "{n} rooms · type {n}A",
"{n} camere · tip {n}B": "{n} rooms · type {n}B",
"{n} cameră · tip {n}A": "{n} room · type {n}A",
"Parter, bloc {n}": "Ground floor, building {n}",
"Etaj {n} bloc {n}": "Floor {n}, building {n}",
"Chirii estimate la aproximativ {n} €/m² util pentru zona Păcurari. Valorile nu sunt garantate și nu constituie consultanță de investiții.": "Rents estimated at about €{n}/m² of usable area for the Păcurari area. Values are not guaranteed and do not constitute investment advice.",
"Toate garsonierele disponibile": "All available studios",
"{n} — Argumente": "{n} — Arguments",
"De ce Iași": "Why Iași",
"și de ce Păcurari": "and why Păcurari",
"Patru factori care susțin cererea de închiriere pe termen lung.": "Four factors supporting long-term rental demand.",
"Cerere constantă de chirii": "Steady rental demand",
"Al doilea centru universitar din țară și un pol IT în creștere. Cererea pentru garsoniere și apartamente cu {n} camere nu depinde de un singur angajator.": "The country's second-largest university city and a growing IT hub. Demand for studios and {n}-room apartments does not depend on a single employer.",
"{n} km de centru, {n} km de Copou": "{n} km from the centre, {n} km from Copou",
"Transport public direct spre universități și spre centrul orașului. Zona Păcurari este printre primele căutate de chiriașii care lucrează sau studiază în nord-vestul Iașului.": "Direct public transport to the universities and the city centre. Păcurari is among the first choices of tenants who work or study in north-western Iași.",
"Clădire nouă, costuri de exploatare mici": "New building, low running costs",
"Anvelopă termică conform normelor actuale, centrală proprie și contorizare individuală: cheltuieli lunare previzibile și reparații rare în primii ani.": "A thermal envelope to current standards, an own boiler and individual metering: predictable monthly costs and rare repairs in the first years.",
"Fără comision de intermediere la achiziție și cu preț afișat pentru fiecare unitate. Economia se regăsește direct în randament.": "No agency commission on purchase and a listed price for every unit. The saving goes straight into the yield.",
"{n} — Parcurs": "{n} — Process",
"De la selecție": "From selection",
"la primul chiriaș": "to the first tenant",
"Trei etape, cu documente clare și termene cunoscute de la început.": "Three stages, with clear documents and deadlines known from the start.",
"Selecție și rezervare": "Selection and reservation",
"Alegerea unității din lista de disponibilitate, vizionarea apartamentului-model și rezervarea, cu blocarea prețului afișat.": "Choosing the unit from the availability list, viewing the show apartment and reserving, with the listed price locked in.",
"Antecontract și plată": "Pre-sale agreement and payment",
"Avans la antecontract, apoi tranșe legate de stadiul lucrărilor. Plata se poate face din fonduri proprii sau prin credit ipotecar.": "A deposit at the pre-sale agreement, then instalments linked to construction progress. Payment can be made from own funds or through a mortgage.",
"Predare la cheie și închiriere": "Turnkey handover and letting",
"Recepția apartamentului finisat, intabularea și, la cerere, recomandarea unui partener de administrare pentru închiriere.": "Acceptance of the finished apartment, land registration and, on request, a recommended property management partner for letting.",
"{n} — Informare": "{n} — Information",
"Ce trebuie": "What to",
"luat în calcul": "take into account",
"Elementele care diferențiază o estimare de rezultatul real.": "The elements that separate an estimate from the actual result.",
"Randament brut și randament net": "Gross yield and net yield",
"Randamentul brut împarte chiria anuală la prețul de achiziție. Cel net scade perioadele neînchiriate, impozitul pe venit, cheltuielile de administrare și reparațiile. Diferența dintre cele două este, de regulă, de cel puțin un punct procentual.":
    "Gross yield divides the annual rent by the purchase price. Net yield deducts vacancy periods, income tax, management costs and repairs. The difference between the two is usually at least one percentage point.",
"Costuri care nu apar în calculator": "Costs not in the calculator",
"Taxele notariale, intabularea, TVA-ul aferent, mobilarea și echiparea inițială și eventualul comision de administrare nu sunt incluse. Pentru o garsonieră, mobilarea completă pornește în general de la câteva mii de euro.":
    "Notary fees, land registration, the applicable VAT, initial furnishing and equipment and any management fee are not included. For a studio, full furnishing generally starts at a few thousand euros.",
"Caracterul informativ al cifrelor": "The informative nature of the figures",
"Valorile de pe această pagină sunt estimări bazate pe prețuri de listare și pe chirii observate în zonă. Nu reprezintă consultanță financiară sau fiscală; decizia de achiziție aparține cumpărătorului, care poate consulta un specialist independent.":
    "The values on this page are estimates based on listing prices and rents observed in the area. They are not financial or tax advice; the purchase decision belongs to the buyer, who may consult an independent specialist.",
"Avantajele unei locuințe noi": "The advantages of a new home",
"{n} elemente": "{n} items",
"Garanție de structură și de finisaje, conform legii": "Structural and finishing warranties, as required by law",
"Centrală proprie și contorizare individuală": "Own boiler and individual metering",
"Consum redus: anvelopă termică și geam tripan": "Low consumption: thermal envelope and triple glazing",
"Predare la cheie: chiriașul se poate muta după mobilare": "Turnkey handover: the tenant can move in after furnishing",
"Parcare subterană și boxă, la cerere": "Underground parking and storage room, on request",
"Documentație completă: autorizații și intabulare": "Complete documentation: permits and land registration",
"investiție și randament": "investment and yield",
"{n} întrebări despre chirii, costuri, cerere și metodă de calcul.": "{n} questions about rents, costs, demand and calculation method.",
"Ce randament brut au apartamentele din Emerald City?": "What gross yield do Emerald City apartments have?",
"La prețurile de listare și la chiriile observate în zona Păcurari, randamentul brut estimat se situează între aproximativ {n}% și {n}% pe an, cel mai ridicat fiind la garsoniere. Cifrele sunt estimări, nu valori garantate.":
    "At listing prices and the rents observed in the Păcurari area, the estimated gross yield is between about {n}% and {n}% per year, highest for studios. The figures are estimates, not guaranteed values.",
"Cum este estimată chiria lunară?": "How is the monthly rent estimated?",
"Chiria este calculată la aproximativ {n} €/m² util pe lună, o medie observată pentru locuințe noi, finisate la cheie, în zona Păcurari. Valoarea reală depinde de mobilare, etaj, orientare și de momentul închirierii.":
    "Rent is calculated at about €{n}/m² of usable area per month, an average observed for new, turnkey-finished homes in the Păcurari area. The actual value depends on furnishing, floor, orientation and the time of letting.",
"Care este diferența dintre randamentul brut și cel net?": "What is the difference between gross and net yield?",
"Randamentul brut împarte chiria anuală la prețul de achiziție. Cel net scade perioadele neînchiriate, impozitul pe venit, cheltuielile de administrare și reparațiile. Calculatorul aplică un cost de aproximativ {n}% și un grad de neocupare configurabil.":
    "Gross yield divides the annual rent by the purchase price. Net yield deducts vacancy periods, income tax, management costs and repairs. The calculator applies a cost of about {n}% and a configurable vacancy rate.",
"Ce costuri nu apar în calculator?": "Which costs are not in the calculator?",
"Taxele notariale, intabularea, TVA-ul aferent, mobilarea și echiparea inițială, precum și eventualul comision al unei firme de administrare. Pentru o garsonieră, mobilarea completă pornește în general de la câteva mii de euro.":
    "Notary fees, land registration, the applicable VAT, initial furnishing and equipment, and any property management fee. For a studio, full furnishing generally starts at a few thousand euros.",
"Apartamentele se predau finisate, gata de închiriat?": "Are the apartments handed over finished, ready to let?",
"Da. Predarea se face la cheie: parchet, gresie, faianță, obiecte sanitare, centrală proprie, încălzire în pardoseală, uși interioare și tâmplărie cu geam tripan. Rămân de adăugat mobilierul și electrocasnicele.":
    "Yes. Handover is turnkey: flooring, tiles, sanitary ware, own boiler, underfloor heating, interior doors and triple-glazed windows. Only furniture and appliances remain to be added.",
"Pot fi achiziționate mai multe unități în același bloc?": "Can several units be bought in the same building?",
"Da. Pentru achiziții multiple, echipa de vânzări poate pregăti o selecție de unități pe același palier sau în același bloc, cu o propunere comercială dedicată, în showroom.": "Yes. For multiple purchases, the sales team can prepare a selection of units on the same landing or in the same building, with a dedicated commercial proposal, at the showroom.",
"Ce cerere de închiriere există în zona Păcurari?": "What rental demand is there in the Păcurari area?",
"Iașul este al doilea centru universitar din țară, cu peste {n} de studenți, la care se adaugă angajații din IT și servicii. Păcurari se află la {n} km de centru și la circa {n} km de Copou, pe un culoar de transport public direct.":
    "Iași is the country's second-largest university city, with over {n} students, plus employees in IT and services. Păcurari is {n} km from the centre and about {n} km from Copou, on a direct public transport corridor.",
"Informațiile de pe această pagină reprezintă consultanță de investiții?": "Is the information on this page investment advice?",
"Nu. Cifrele sunt estimări bazate pe prețuri de listare și pe chirii observate în zonă și au rol informativ. Decizia de achiziție aparține cumpărătorului, care poate consulta un specialist financiar sau fiscal independent.":
    "No. The figures are estimates based on listing prices and rents observed in the area and are for information only. The purchase decision belongs to the buyer, who may consult an independent financial or tax specialist.",
"Calculator de randament pentru apartamente noi în Iași, zona Păcurari. {n} de garsoniere disponibile, cu estimări de chirie și amortizare.": "Yield calculator for new apartments in Iași, Păcurari area. {n} studios available, with rent and payback estimates.",
# ---- comparator -----------------------------------------------------------
"Comparator de apartamente — Emerald City Iași": "Apartment comparison — Emerald City Iași",
"Comparator": "Comparison",
"Comparator de apartamentele salvate": "Compare the saved apartments",
"Adaugă apartamente cu butonul „Salvează” de pe paginile de unitate, apoi trimite linkul acestei pagini cui vrei. Lista se păstrează și în adresă, deci funcționează și pe alt dispozitiv.": "Add apartments with the “Save” button on the unit pages, then share this page's link with anyone. The list is also kept in the address, so it works on another device too.",
"Alte apartamente": "Other apartments",
"Compară până la șase apartamente din Emerald City, Iași zona Păcurari.": "Compare up to six apartments from Emerald City, Iași Păcurari area.",
# ---- contact --------------------------------------------------------------
"Contact — Emerald City Iași": "Contact — Emerald City Iași",
"Echipa de vânzări, la un mesaj distanță": "The sales team, one message away",
"Telefon, WhatsApp, e-mail sau o întâlnire în showroom. Solicitările primesc răspuns în aceeași zi lucrătoare, direct de la dezvoltator, fără intermediari.": "Phone, WhatsApp, e-mail or a meeting at the showroom. Requests are answered on the same working day, directly by the developer, with no intermediaries.",
"{n} — Canale": "{n} — Channels",
"Patru moduri": "Four ways",
"de a lua legătura": "to get in touch",
"Fiecare canal ajunge la aceeași echipă. Alegerea ține doar de preferință.": "Every channel reaches the same team. The choice is purely a matter of preference.",
"Luni–vineri {n} sâmbătă {n}": "Mon–Fri {n}, Sat {n}",
"Mesaje, planuri și liste de prețuri": "Messages, plans and price lists",
"Răspuns în aceeași zi lucrătoare": "Reply on the same working day",
"Showroom": "Showroom",
"Str. Dealul Zorilor {n}": "Str. Dealul Zorilor {n}",
"Zona Păcurari, Iași · cu programare": "Păcurari area, Iași · by appointment",
"Harta, datele de contact și formularul. Pentru o vizionare, pagina dedicată permite alegerea zilei și a intervalului orar.": "The map, the contact details and the form. For a viewing, the dedicated page lets you choose the day and time slot.",
"{n} — Dezvoltator": "{n} — Developer",
"Date de": "Company",
"identificare": "details",
"Vânzarea se face direct de către societatea care dezvoltă ansamblul.": "Sales are made directly by the company developing the project.",
"Dezvoltatorul ansamblului": "The project's developer",
"Parte a Green Stone Group, dezvoltator activ din {n}": "Part of Green Stone Group, a developer active since {n}",
"Sediu social: Str. Ion Nistor, Iași": "Registered office: Str. Ion Nistor, Iași",
"Birou de vânzări: Str. Dealul Zorilor {n} zona Păcurari, Iași": "Sales office: Str. Dealul Zorilor {n}, Păcurari area, Iași",
"vanzari@emerald-city.ro · protecția datelor: dpo@emerald-city.ro": "vanzari@emerald-city.ro · data protection: dpo@emerald-city.ro",
"Contractele se semnează la notar, cu documentația completă a proiectului": "Contracts are signed before a notary, with the project's complete documentation",
"Proiecte anterioare finalizate în Iași: Lapis Residence, Onyx Residence": "Previous projects completed in Iași: Lapis Residence, Onyx Residence",
"Ce se poate solicita": "What you can request",
"{n} documente și servicii": "{n} documents and services",
"Lista completă de disponibilitate, cu prețuri actualizate": "The full availability list, with up-to-date prices",
"Planurile detaliate ale fiecărei compartimentări": "The detailed plans of each layout",
"Condițiile de plată și eșalonarea pe stadii de execuție": "Payment terms and the schedule by construction stage",
"Recomandări de bănci partenere pentru credit ipotecar": "Recommended partner banks for a mortgage",
"Vizită pe șantier, însoțită, cu echipament de protecție": "An accompanied site visit, with protective equipment",
"Raportul lunar de stadiu al lucrărilor, pe e-mail": "The monthly construction progress report, by e-mail",
"contact și program": "contact and opening hours",
"{n} întrebări despre program, timp de răspuns și vizionări.": "{n} questions about opening hours, response time and viewings.",
"Care este programul biroului de vânzări?": "What are the sales office's opening hours?",
"Luni–vineri între {n}:{n} și {n}:{n} și sâmbătă între {n}:{n} și {n}:{n} la showroom-ul din Str. Dealul Zorilor {n} zona Păcurari, Iași. În afara programului, solicitările primite pe e-mail sau WhatsApp sunt preluate în prima zi lucrătoare.":
    "Monday to Friday from {n}:{n} to {n}:{n} and Saturday from {n}:{n} to {n}:{n}, at the showroom on Str. Dealul Zorilor {n}, Păcurari area, Iași. Outside these hours, requests received by e-mail or WhatsApp are picked up on the next working day.",
"În cât timp se primește un răspuns?": "How quickly will I get a reply?",
"Solicitările transmise prin formular sau e-mail primesc răspuns în aceeași zi lucrătoare, dacă sunt trimise până la ora {n}:{n} Apelurile telefonice sunt preluate direct în program.": "Requests sent through the form or by e-mail are answered on the same working day if sent before {n}:{n}. Phone calls are answered directly during opening hours.",
"Vizionarea se face doar cu programare?": "Are viewings by appointment only?",
"Da. Apartamentul-model și șantierul se vizitează cu programare, pentru ca un consultant să fie disponibil exclusiv pentru întâlnire. Programarea se face online, telefonic sau pe WhatsApp.": "Yes. The show apartment and the site are visited by appointment, so that a consultant is available exclusively for the meeting. Appointments can be made online, by phone or on WhatsApp.",
"Se pot solicita planuri și liste de prețuri pe e-mail?": "Can plans and price lists be requested by e-mail?",
"Da. Lista completă de disponibilitate, planurile fiecărei compartimentări și condițiile de plată se transmit pe e-mail sau pe WhatsApp, la cerere.": "Yes. The full availability list, the plans of each layout and the payment terms are sent by e-mail or WhatsApp, on request.",
"Există parcare la showroom?": "Is there parking at the showroom?",
"Da, locuri de parcare gratuite în fața biroului de vânzări, pe Str. Dealul Zorilor. Zona este deservită și de transportul public, cu stație la circa {n} m.": "Yes, free parking in front of the sales office on Str. Dealul Zorilor. The area is also served by public transport, with a stop about {n} m away.",
"Cine răspunde la solicitări?": "Who answers the requests?",
"Echipa de vânzări a dezvoltatorului, Tala Sapphire S.R.L., parte a Green Stone Group. Nu se lucrează prin intermediari și nu se percep comisioane de agenție.": "The developer's sales team, Tala Sapphire S.R.L., part of Green Stone Group. No intermediaries are involved and no agency commissions are charged.",
"Contact Emerald City, ansamblu rezidențial în Iași, zona Păcurari: telefon {n} {n} {n} {n} WhatsApp, e-mail și showroom pe Str. Dealul Zorilor {n}": "Contact Emerald City, a residential development in Iași, Păcurari area: phone {n} {n} {n} {n}, WhatsApp, e-mail and showroom on Str. Dealul Zorilor {n}.",
# ---- programare vizionare -------------------------------------------------
"Programare vizionare — Emerald City Iași": "Book a viewing — Emerald City Iași",
"Vizionarea apartamentului-model, la ora dorită": "View the show apartment at a time that suits you",
"O întâlnire de aproximativ {n} de minute în showroom-ul din Păcurari: apartamentul-model finisat, planurile pe masă și lista de disponibilitate, cu {n} de apartamente cu prețuri afișate.": "A meeting of about {n} minutes at the Păcurari showroom: the finished show apartment, the floor plans on the table and the availability list, with {n} apartments at listed prices.",
"Alegeți ziua și ora": "Choose the day and time",
"Programare pe WhatsApp": "Book on WhatsApp",
"Durata întâlnirii": "Meeting length",
"Luni–sâmbătă": "Monday to Saturday",
"Gratuit": "Free",
"Fără nicio obligație": "No obligation",
"{n} — Programare": "{n} — Booking",
"Alegeți": "Choose",
"ziua și intervalul": "the day and time slot",
"Confirmarea se face telefonic, în aceeași zi lucrătoare. Programarea se poate modifica oricând.": "Confirmation is by phone, on the same working day. The appointment can be changed at any time.",
"Formular de programare": "Booking form",
"Câmpurile marcate cu * sunt necesare pentru confirmare.": "Fields marked with * are required for confirmation.",
"Nume și prenume *": "Full name *",
"Telefon *": "Phone *",
"Apartament de interes": "Apartment of interest",
"Nehotărât": "Undecided",
"Ziua preferată *": "Preferred day *",
"Număr de persoane": "Number of people",
"{n} sau mai multe": "{n} or more",
"Interval orar *": "Time slot *",
"Sâmbătă: {n}:{n}:{n} Pentru alt interval, menționați în mesaj.": "Saturday: {n}:{n}:{n}. For another slot, mention it in the message.",
"Sunt de acord cu prelucrarea datelor conform": "I agree to the processing of my data in accordance with the",
"Politicii de confidențialitate": "Privacy policy",
", în scopul programării vizionării. *": ", for the purpose of booking the viewing. *",
"Trimite programarea": "Send booking",
"Ce include vizionarea": "What the viewing includes",
"Apartamentul-model, complet finisat și mobilat": "The show apartment, fully finished and furnished",
"Mostrele de finisaje: parchet, gresie, faianță, uși": "Finish samples: flooring, tiles, doors",
"Planul de situație: blocuri, etape, parcări, spații verzi": "The site plan: buildings, phases, parking, green spaces",
"Lista de disponibilitate, cu prețul fiecărei unități": "The availability list, with the price of every unit",
"Condițiile de plată și simularea unei rate": "Payment terms and a mortgage simulation",
"La cerere, vizită pe șantier cu echipament de protecție": "On request, a site visit with protective equipment",
"Cum se ajunge": "How to get there",
"Str. Dealul Zorilor {n} zona Păcurari, Iași. Parcare gratuită în fața biroului. Transport public: stație la circa {n} m, pe Șoseaua Păcurari.": "Str. Dealul Zorilor {n}, Păcurari area, Iași. Free parking in front of the office. Public transport: a stop about {n} m away, on Șoseaua Păcurari.",
"Cum decurge": "How the",
"întâlnirea": "meeting goes",
"Trei pași, de la confirmare la propunerea personalizată.": "Three steps, from confirmation to a personalised proposal.",
"Confirmare telefonică": "Phone confirmation",
"Un consultant confirmă ziua și ora în aceeași zi lucrătoare și notează preferințele: număr de camere, etaj, buget orientativ.": "A consultant confirms the day and time on the same working day and notes your preferences: number of rooms, floor, indicative budget.",
"Vizionare și prezentare": "Viewing and presentation",
"Apartamentul-model, mostrele de finisaje, planurile și lista de disponibilitate. La cerere, vizită însoțită pe șantier.": "The show apartment, the finish samples, the plans and the availability list. On request, an accompanied site visit.",
"Propunere personalizată": "Personalised proposal",
"O selecție de {n} unități potrivite, cu preț, plan și eșalonarea plăților, transmisă pe e-mail după întâlnire.": "A selection of {n} suitable units, with price, plan and payment schedule, sent by e-mail after the meeting.",
"vizionare": "viewings",
"{n} întrebări despre durată, program și ce se poate vedea.": "{n} questions about length, hours and what can be seen.",
"Cât durează o vizionare?": "How long does a viewing take?",
"Aproximativ {n} de minute: prezentarea apartamentului-model, a planurilor și a listei de disponibilitate, urmată de întrebări. La cerere, întâlnirea continuă cu o vizită pe șantier.": "About {n} minutes: a presentation of the show apartment, the plans and the availability list, followed by questions. On request, the meeting continues with a site visit.",
"Ce se poate vedea la fața locului?": "What can be seen on site?",
"Apartamentul-model complet finisat, mostrele de finisaje, planul de situație al ansamblului și, cu echipament de protecție, blocurile aflate în execuție.": "The fully finished show apartment, the finish samples, the development's site plan and, with protective equipment, the buildings under construction.",
"Se poate programa o vizionare sâmbăta?": "Can a viewing be booked on a Saturday?",
"Da, sâmbătă între {n}:{n} și {n}:{n} Intervalele de sâmbătă se ocupă mai repede, de aceea recomandăm programarea cu câteva zile înainte.": "Yes, on Saturdays between {n}:{n} and {n}:{n}. Saturday slots fill up faster, so we recommend booking a few days ahead.",
"Programarea se confirmă?": "Is the appointment confirmed?",
"Da. După trimiterea formularului, un consultant confirmă telefonic ziua și ora, în aceeași zi lucrătoare. Programarea se poate modifica sau anula oricând, telefonic sau pe WhatsApp.": "Yes. After the form is sent, a consultant confirms the day and time by phone on the same working day. The appointment can be changed or cancelled at any time, by phone or WhatsApp.",
"Este necesar un document sau o pregătire prealabilă?": "Is any document or preparation needed?",
"Nu. Este utilă doar o idee despre buget și despre numărul de camere dorit, pentru ca prezentarea să fie orientată către unitățile potrivite.": "No. It only helps to have an idea of your budget and the number of rooms you want, so the presentation can focus on the right units.",
"Pot participa mai multe persoane?": "Can several people attend?",
"Da. Familia, un consilier financiar sau un arhitect sunt bineveniți. Menționați numărul de persoane în formular, pentru organizarea întâlnirii.": "Yes. Family, a financial adviser or an architect are welcome. Mention the number of people in the form so the meeting can be organised.",
"Se poate rezerva un apartament în ziua vizionării?": "Can an apartment be reserved on the day of the viewing?",
"Da. Rezervarea blochează prețul afișat pentru unitatea aleasă, până la semnarea antecontractului, în condițiile comunicate la întâlnire.": "Yes. A reservation locks in the listed price for the chosen unit until the pre-sale agreement is signed, under the terms communicated at the meeting.",
"Vizionarea implică vreo obligație?": "Does a viewing involve any obligation?",
"Nu. Vizionarea este gratuită și nu presupune nicio obligație de cumpărare.": "No. The viewing is free and involves no obligation to buy.",
"Programați o vizionare a apartamentului-model Emerald City, Iași zona Păcurari: alegeți ziua și intervalul orar, confirmarea se face telefonic în aceeași zi.": "Book a viewing of the Emerald City show apartment, Iași Păcurari area: choose the day and time slot; confirmation is by phone on the same day.",
"Buget orientativ, etaj preferat, întrebări": "Indicative budget, preferred floor, questions",
}
