# -*- coding: utf-8 -*-
# Date structurate (nume), etichete din SVG, resturi.
T = {
"Birou": "Study",
"Apariții în presă — Emerald City": "Press coverage — Emerald City",
"Schemă de compartimentare, tipologia {n}A": "Layout diagram, type {n}A",
"Schemă de compartimentare, tipologia {n}B": "Layout diagram, type {n}B",
"Dorm. {n}": "Bed. {n}",
"Str. Ion Nistor": "Str. Ion Nistor",
"Apartamente {n} cameră tip {n}A — Emerald City Iași": "{n}-room apartments type {n}A — Emerald City Iași",
"Apartamente {n} camere tip {n}A — Emerald City Iași": "{n}-room apartments type {n}A — Emerald City Iași",
"Apartamente {n} camere tip {n}B — Emerald City Iași": "{n}-room apartments type {n}B — Emerald City Iași",
"Contact Emerald City Iași": "Contact Emerald City Iași",
"Emerald City — birou de vânzări": "Emerald City — sales office",
"Grup de firme dedicat dezvoltării de proiecte imobiliare și regenerării urbane, cu proiecte în Marea Britanie, Israel și România.": "A group of companies dedicated to real estate development and urban regeneration, with projects in the United Kingdom, Israel and Romania.",
"România": "Romania",
"Despre Emerald City": "About Emerald City",
"Finisaje incluse — Emerald City": "Finishes included — Emerald City",
"Emerald City — apartamente noi în Iași, zona Păcurari": "Emerald City — new apartments in Iași, Păcurari area",
"Ansamblu rezidențial premium cu {n} de apartamente cu {n} {n} și {n} camere, în zona Păcurari din Iași. Finisaje premium, {n}% spațiu verde, parcare subterană.": "A premium residential development with {n} apartments of {n}, {n} and {n} rooms, in the Păcurari area of Iași. Premium finishes, {n}% green space, underground parking.",
"Strada Ion Nistor": "Strada Ion Nistor",
"Investiție în apartamente noi în Iași": "Investing in new apartments in Iași",
"Proiectul Emerald City": "The Emerald City project",
"Secțiune verticală printr-un bloc: două demisoluri, parter și trei etaje, atic la {n} metri": "Vertical section through a building: two basement levels, ground floor and three storeys, parapet at {n} metres",
"COTA TERENULUI": "GROUND LEVEL",
"Demisol {n}": "Basement {n}",
"Stadiul lucrărilor — Emerald City": "Construction progress — Emerald City",
"Programare vizionare — Emerald City Iași": "Book a viewing — Emerald City Iași",
"Comparator de apartamente — Emerald City": "Apartment comparison — Emerald City",
"Apartamente noi în Iași, zona Păcurari — Emerald City": "New apartments in Iași, Păcurari area — Emerald City",
}
