# -*- coding: utf-8 -*-
# Noutati: listarea si cele 6 articole.
T = {
"Deschideți harta în Google Maps": "Open the map in Google Maps",
"Noutăți": "News",
"Noutăți Emerald City": "Emerald City news",
"Noutăți — șantier, ghiduri și analize | Emerald City Iași": "News — site updates, guides and analysis | Emerald City Iași",
"Noutăți de la Emerald City, Iași zona Păcurari: stadiul lucrărilor, ghiduri de achiziție, explicații despre finisaje, cifre despre zonă și randamentul chiriilor.": "News from Emerald City, Iași Păcurari area: construction progress, buying guides, explanations of the finishes, figures on the area and rental yields.",
"Noutăți din șantier, ghiduri și analize": "Site updates, guides and analysis",
"Stadiul lucrărilor, explicații tehnice despre finisaje, ghiduri de achiziție și cifre despre zonă și piața de închirieri. Articole semnate de echipa Emerald City, actualizate lunar.": "Construction progress, technical explanations of the finishes, buying guides and figures on the area and the rental market. Articles by the Emerald City team, updated monthly.",
"Cele {n} articole": "The {n} articles",
"{n} — Articole": "{n} — Articles",
"Cele mai recente": "Most recently",
"publicate": "published",
"Șantier, ghid de achiziție, finisaje, zonă, investiție și proiect — câte un articol pe temă.": "Site, buying guide, finishes, area, investment and project — one article per topic.",
"{n} min de citit": "{n} min read",
"Citește articolul": "Read the article",
"Jurnal de șantier": "Site diary",
"Ghid de achiziție": "Buying guide",
"Finisaje și tehnic": "Finishes and technical",
"Zona": "The area",
"Investiție": "Investment",
"Proiect": "Project",
"Primiți articolele noi pe e-mail": "Get new articles by e-mail",
"Un e-mail pe lună, cu stadiul lucrărilor și articolele publicate. Se poate opri oricând.": "One e-mail per month, with the construction progress and the articles published. Unsubscribe at any time.",
"Emerald City — echipa de vânzări": "Emerald City — sales team",
"Echipa Emerald City": "The Emerald City team",
"Notă": "Note",
"Informațiile reflectă situația la data publicării. Cifrele contractuale — suprafețe, prețuri, termene — sunt cele din documentele semnate între părți.": "The information reflects the situation at the date of publication. Contractual figures — areas, prices, deadlines — are those in the documents signed between the parties.",
"Distribuiți:": "Share:",
"Cifre-cheie": "Key figures",
"Legături utile": "Useful links",
"Vizionare în showroom": "Viewing at the showroom",
"Apartamentul-model, planurile și lista de disponibilitate, într-o întâlnire de {n} de minute.": "The show apartment, the plans and the availability list, in a {n}-minute meeting.",
"Alte articole": "More articles",
"Continuați": "Continue",
"lectura": "reading",
"Trei articole pe teme apropiate.": "Three articles on related topics.",
# --- articolul 1: santier ---------------------------------------------------
"Etapa I: structura a ajuns la etajul {n} în blocurile {n}": "Phase I: the structure has reached floor {n} in buildings {n}",
"Etapa I: structura a ajuns la etajul {n} în blocurile {n} | Emerald City": "Phase I: the structure has reached floor {n} in buildings {n} | Emerald City",
"Planșeul peste etajul {n} este turnat la primele patru blocuri, iar la blocurile {n} și {n} se montează cofrajele. Ce urmează până la finalul anului și ce înseamnă pentru termenele de predare.": "The slab over floor {n} has been poured at the first four buildings, and formwork is going up at buildings {n} and {n}. What comes next by the end of the year and what it means for handover dates.",
"Unde s-a ajuns în septembrie": "Where things stand in September",
"Raportul de șantier din septembrie consemnează turnarea planșeului peste etajul {n} la blocurile {n} {n} {n} și {n} cu procesele-verbale de fază determinantă semnate de dirigintele de șantier și de proiectant. La blocurile {n} și {n} cofrajele pentru stâlpii etajului {n} sunt montate, iar armarea este în curs.":
    "The September site report records the pouring of the slab over floor {n} at buildings {n} {n} {n} and {n} with the key-stage inspection reports signed by the site supervisor and the designer. At buildings {n} and {n} the formwork for the floor {n} columns is in place and reinforcement is under way.",
"În paralel, la blocurile {n} și {n} — primele din Etapa II — a început săpătura pentru cele două demisoluri. Platforma de organizare a fost extinsă către latura de vest a terenului, astfel încât circulația utilajelor să nu intersecteze zona blocurilor aflate deja în structură.":
    "In parallel, at buildings {n} and {n} — the first in Phase II — excavation for the two basement levels has begun. The site compound has been extended towards the western side of the plot, so that machinery traffic does not cross the area of the buildings already in structure.",
"Ce înseamnă „fază determinantă”": "What a “key stage” means",
"Fazele determinante sunt punctele de control impuse de lege în care execuția nu poate continua fără verificarea și semnătura dirigintelui de șantier, a proiectantului și, după caz, a Inspectoratului de Stat în Construcții. Fundațiile, fiecare planșeu și structura completă sunt astfel de puncte.":
    "Key stages are the control points required by law at which work cannot continue without inspection and sign-off by the site supervisor, the designer and, where applicable, the State Inspectorate for Construction. The foundations, each slab and the completed structure are such points.",
"Pentru cumpărător, existența acestor procese-verbale înseamnă că structura a fost verificată independent la fiecare etapă, nu doar la recepția finală. Documentele intră în cartea tehnică a construcției, predată odată cu apartamentul.":
    "For the buyer, these inspection reports mean the structure has been checked independently at every stage, not only at final acceptance. The documents go into the building's technical book, handed over with the apartment.",
"Calendarul până la finalul anului": "The schedule to the end of the year",
"Până în decembrie, la blocurile {n} se estimează finalizarea structurii la nivelul etajului {n} și începerea închiderilor exterioare la nivelurile inferioare. La blocurile {n} și {n} structura ar urma să ajungă la etajul {n} Săpăturile și fundațiile pentru blocurile {n} și {n} sunt planificate pentru trimestrul IV.":
    "By December, buildings {n} are expected to have the structure completed up to floor {n} and the external envelope started on the lower levels. At buildings {n} and {n} the structure should reach floor {n} Excavation and foundations for buildings {n} and {n} are planned for the fourth quarter.",
"Termenele afișate sunt estimări la data raportului. Termenul contractual pentru fiecare unitate este cel înscris în antecontract și nu se modifică prin actualizările din jurnal.": "The dates shown are estimates as of the report date. The contractual deadline for each unit is the one written into the pre-sale agreement and is not changed by diary updates.",
"Cum se poate verifica stadiul": "How to check progress",
"Pagina de stadiu al lucrărilor se actualizează lunar, cu fotografii datate din teren. Vizitele pe șantier se organizează cu programare, însoțite de un reprezentant, cu echipament de protecție pus la dispoziție. Raportul lunar poate fi primit și pe e-mail, la cerere.":
    "The construction progress page is updated monthly, with dated site photos. Site visits are organised by appointment, accompanied by a representative, with protective equipment provided. The monthly report can also be received by e-mail, on request.",
"Blocuri cu planșeul peste etajul {n}": "Buildings with the slab over floor {n}",
"Blocuri în cofrare": "Buildings in formwork",
"Etapa II — săpături începute": "Phase II — excavation started",
"blocurile {n} și {n}": "buildings {n} and {n}",
"Următoarea actualizare": "Next update",
"octombrie {n}": "October {n}",
"Stadiul lucrărilor, faza cu faza": "Construction progress, stage by stage",
"Apartamentele disponibile în Etapa I": "Apartments available in Phase I",
# --- articolul 2: ghid ------------------------------------------------------
"Cum se cumpără un apartament nou în Iași: cei {n} pași, cu documentele fiecăruia": "How to buy a new apartment in Iași: the {n} steps, with the documents for each",
"Cum se cumpără un apartament nou în Iași: cei {n} pași, cu documentele fiecăruia | Emerald City": "How to buy a new apartment in Iași: the {n} steps, with the documents for each | Emerald City",
"De la vizionare la intabulare, ce se semnează, ce se plătește și ce se verifică la fiecare pas. Un ghid practic pentru prima achiziție de la dezvoltator.": "From viewing to land registration: what is signed, what is paid and what to check at every step. A practical guide to a first purchase from a developer.",
"{n} Vizionarea și lista de disponibilitate": "{n} The viewing and the availability list",
"Primul pas este întâlnirea în showroom: apartamentul-model, planurile fiecărei compartimentări și lista de disponibilitate cu prețul fiecărei unități. Este momentul în care se clarifică bugetul, etajul, orientarea și dotările suplimentare — loc de parcare, boxă, curte.":
    "The first step is the meeting at the showroom: the show apartment, the plans of each layout and the availability list with the price of every unit. This is when the budget, floor, orientation and extras — parking space, storage room, garden — are clarified.",
"Documente de cerut: autorizația de construire (număr și dată), certificatul de urbanism cu indicatorii aprobați, extrasul de carte funciară al terenului și anexa tehnică de finisaje. Un dezvoltator serios le pune la dispoziție fără rezerve.":
    "Documents to ask for: the building permit (number and date), the urban planning certificate with the approved indicators, the land book extract for the plot and the technical annex of finishes. A serious developer provides them without hesitation.",
"{n} Rezervarea": "{n} The reservation",
"Rezervarea blochează unitatea aleasă pe numele cumpărătorului și menține prețul afișat pentru o perioadă stabilită, de regulă până la semnarea antecontractului. Se semnează un document scurt, în care se menționează unitatea, prețul și termenul de valabilitate.":
    "The reservation holds the chosen unit in the buyer's name and maintains the listed price for a set period, usually until the pre-sale agreement is signed. A short document is signed, stating the unit, the price and the validity period.",
"În această perioadă cumpărătorul poate obține pre-aprobarea creditului, dacă finanțează prin bancă. Documentația necesară băncii — planuri, autorizație, extras CF — se pune la dispoziție de dezvoltator.":
    "During this period the buyer can obtain mortgage pre-approval, if financing through a bank. The documentation the bank needs — plans, permit, land book extract — is provided by the developer.",
"{n} Antecontractul, la notar": "{n} The pre-sale agreement, at the notary",
"Antecontractul de vânzare-cumpărare se semnează în formă autentică, la notar. Fixează unitatea, suprafețele, prețul, eșalonarea plăților, termenul de predare și consecințele întârzierii. La semnare se achită avansul — la Emerald City, {n}% din preț.":
    "The pre-sale agreement is signed in authenticated form before a notary. It fixes the unit, the areas, the price, the payment schedule, the handover date and the consequences of delay. The deposit is paid at signing — at Emerald City, {n}% of the price.",
"De verificat înainte de semnare: concordanța dintre planul anexat și unitatea vizitată, lista de finisaje poziție cu poziție, termenul de predare exprimat ca dată, nu ca „trimestru estimat”, și clauzele de penalitate în ambele sensuri.":
    "To check before signing: that the attached plan matches the unit visited, the list of finishes item by item, the handover deadline expressed as a date rather than an “estimated quarter”, and the penalty clauses in both directions.",
"{n} Construcția și plățile intermediare": "{n} Construction and interim payments",
"Pe durata execuției, cumpărătorul poate urmări progresul în jurnalul de șantier și poate vizita șantierul cu programare. Plățile intermediare, dacă există, sunt legate de stadii fizice verificabile — structură finalizată, închideri, instalații — nu de date calendaristice.":
    "During construction, the buyer can follow progress in the site diary and visit the site by appointment. Interim payments, if any, are tied to verifiable physical stages — structure completed, envelope, building services — not to calendar dates.",
"Creditul ipotecar se trage de regulă la semnarea contractului final, după recepție. Până atunci, banca lucrează cu antecontractul și cu documentația proiectului.": "The mortgage is usually drawn down when the final contract is signed, after acceptance. Until then, the bank works with the pre-sale agreement and the project documentation.",
"{n} Recepția, contractul final și intabularea": "{n} Acceptance, the final contract and land registration",
"La finalizare, apartamentul se verifică împreună cu un reprezentant al dezvoltatorului, pe baza unei liste de verificare: finisaje, instalații, tâmplărie, echipamente. Observațiile se consemnează în procesul-verbal și se remediază înainte de predare.":
    "On completion, the apartment is inspected together with a representative of the developer, using a checklist: finishes, installations, windows and doors, equipment. Observations are recorded in the acceptance report and remedied before handover.",
"Urmează contractul de vânzare-cumpărare la notar, plata diferenței și intabularea pe numele cumpărătorului. Odată cu cheile se predau cartea tehnică, certificatul energetic, documentația cadastrală și garanțiile echipamentelor.":
    "Then come the sale contract at the notary, payment of the balance and land registration in the buyer's name. Along with the keys, the technical book, the energy certificate, the cadastral documentation and the equipment warranties are handed over.",
"Comision de intermediere": "Agency commission",
"Garanție structură": "Structural warranty",
"durata clădirii": "life of the building",
"Vicii ascunse": "Hidden defects",
"Procesul complet, pas cu pas": "The full process, step by step",
"Ce include predarea la cheie": "What turnkey handover includes",
# --- articolul 3: incalzire -------------------------------------------------
"Încălzire în pardoseală sau calorifere: ce se schimbă la confort și la factură": "Underfloor heating or radiators: what changes in comfort and on the bill",
"Încălzire în pardoseală sau calorifere: ce se schimbă la confort și la factură | Emerald City": "Underfloor heating or radiators: what changes in comfort and on the bill | Emerald City",
"Toate cele {n} de apartamente au încălzire în pardoseală, cu centrală proprie în condensație. Explicăm cum funcționează sistemul, ce economie aduce și ce trebuie știut la mobilare.": "All {n} apartments have underfloor heating with their own condensing boiler. We explain how the system works, what it saves and what to know when furnishing.",
"Cum funcționează": "How it works",
"Încălzirea în pardoseală distribuie apa caldă prin serpentine montate în șapă, sub parchet sau gresie. Suprafața întregii pardoseli devine element de încălzire, la o temperatură a apei de {n} °C, față de {n} °C la calorifere.":
    "Underfloor heating circulates hot water through coils laid in the screed, under the flooring or tiles. The whole floor surface becomes the heating element, at a water temperature of {n} °C, compared with {n} °C for radiators.",
"Fiecare cameră are circuit propriu, cu reglaj individual de la distribuitor și termostat. Temperatura se poate seta diferit în dormitor față de living, iar camerele nefolosite pot fi menținute la un nivel minim.":
    "Each room has its own circuit, with individual control at the manifold and a thermostat. The temperature can be set differently in the bedroom and the living room, and unused rooms can be kept at a minimum level.",
"De ce consumă mai puțin": "Why it uses less energy",
"Centrala în condensație are randamentul cel mai ridicat exact la temperaturi joase ale apei, pentru că recuperează căldura din gazele de ardere în loc să o evacueze pe horn. Combinația cu încălzirea în pardoseală o menține în regimul optim aproape tot sezonul.":
    "A condensing boiler is at its most efficient precisely at low water temperatures, because it recovers heat from the flue gases instead of venting it through the chimney. Combined with underfloor heating, it stays in its optimal range for almost the whole season.",
"Rezultatul, la același confort, este un consum de gaz cu până la {n}% mai mic decât la o centrală clasică cu calorifere. La o garsonieră de {n} m² cu anvelopă termică nouă, diferența se simte direct în factura de iarnă.":
    "The result, for the same comfort, is up to {n}% less gas than a conventional boiler with radiators. In a {n} m² studio with a new thermal envelope, the difference shows directly on the winter bill.",
"Confortul: căldura de jos în sus": "Comfort: heat from the floor up",
"Distribuția uniformă a căldurii de la sol elimină zonele reci de lângă ferestre și curenții de aer produși de calorifere. Temperatura resimțită este cu {n} °C mai mare decât cea măsurată, ceea ce permite o setare mai joasă a termostatului.":
    "Even heat distribution from the floor removes the cold spots by the windows and the draughts created by radiators. The perceived temperature is {n} °C higher than the measured one, which allows a lower thermostat setting.",
"Pereții rămân liberi: fără calorifere sub ferestre, mobilierul se poate așeza oriunde, iar tâmplăria până în pardoseală devine posibilă.": "Walls stay free: with no radiators under the windows, furniture can go anywhere, and floor-to-ceiling glazing becomes possible.",
"Ce trebuie știut la mobilare": "What to know when furnishing",
"Parchetul laminat de {n} mm livrat în apartamente este compatibil cu încălzirea în pardoseală. La mobilare se recomandă evitarea covoarelor groase pe suprafețe mari și a mobilierului fără picioare, care reduc transferul de căldură.":
    "The {n} mm laminate flooring supplied in the apartments is compatible with underfloor heating. When furnishing, avoid thick rugs over large areas and furniture without legs, which reduce heat transfer.",
"Sistemul are inerție: se încălzește și se răcește lent. Programarea termostatului pe intervale, nu pornirea și oprirea repetată, este modul eficient de utilizare.": "The system has inertia: it heats up and cools down slowly. Programming the thermostat by time bands, rather than switching it on and off repeatedly, is the efficient way to use it.",
"Temperatura apei în circuit": "Water temperature in the circuit",
"{n} °C": "{n} °C",
"Economie față de centrala clasică": "Saving versus a conventional boiler",
"Reglaj": "Control",
"pe fiecare cameră": "room by room",
"Inclus în preț": "Included in the price",
"toate apartamentele": "all apartments",
"Lista completă a finisajelor": "The full list of finishes",
"Garanțiile instalațiilor": "Installation warranties",
"Apartamentele disponibile": "Available apartments",
# --- articolul 4: zona ------------------------------------------------------
"Păcurari, în cifre: distanțe reale până la școală, universitate și centru": "Păcurari in numbers: real distances to school, university and the centre",
"Păcurari, în cifre: distanțe reale până la școală, universitate și centru | Emerald City": "Păcurari in numbers: real distances to school, university and the centre | Emerald City",
"Am măsurat pe traseu rutier drumurile care contează zilnic — Copou, Universitate, Kaufland, Paradis International College. Ce înseamnă poziția ansamblului pentru o familie, un student sau un investitor.": "We measured, along the road route, the journeys that matter every day — Copou, the University, Kaufland, Paradis International College. What the development's position means for a family, a student or an investor.",
"Poziția pe hartă": "Position on the map",
"Emerald City se află la limita de nord-vest a Iașului, cu acces din Strada Ion Nistor, în spatele ansamblului Contemporan Homes de pe Strada Dealul Zorilor. Este una dintre puținele zone ale orașului care mai dispune de teren pentru ansambluri cu densitate redusă, la distanță mică de centrul universitar.":
    "Emerald City lies on the north-western edge of Iași, with access from Strada Ion Nistor, behind the Contemporan Homes development on Strada Dealul Zorilor. It is one of the few areas of the city that still has land for low-density developments, a short distance from the university district.",
"Distanțele de mai jos sunt calculate pe traseu rutier real, fără trafic, de la amplasament, cu date OpenStreetMap. Singura excepție este Paradis International College, pentru care distanța pietonală este cea indicată de dezvoltator.":
    "The distances below are calculated along the actual road route from the site, without traffic, using OpenStreetMap data. The only exception is Paradis International College, for which the walking distance is the one stated by the developer.",
"Școală, cumpărături, universitate": "School, shopping, university",
"Paradis International College se află la aproximativ {n} de metri, {n} minute de mers pe jos. Kaufland Păcurari este la {n} km, iar magazinele de proximitate de pe artera Păcurari la câteva minute. Universitatea „Alexandru Ioan Cuza” este la {n} km, în Copou, aproximativ {n} minute cu mașina.":
    "Paradis International College is about {n} metres away, a {n}-minute walk. Kaufland Păcurari is {n} km away, and the local shops along the Păcurari road a few minutes. “Alexandru Ioan Cuza” University is {n} km away, in Copou, about {n} minutes by car.",
"Centrul orașului — Piața Unirii — este la {n} km, iar Palas Mall la {n} km. Aeroportul Iași se află la {n} km, aproximativ {n} de minute fără trafic.": "The city centre — Piața Unirii — is {n} km away, and Palas Mall {n} km. Iași Airport is {n} km away, about {n} minutes without traffic.",
"Transport public și ieșirea din oraș": "Public transport and getting out of town",
"Artera Păcurari are linii constante spre centru și spre Copou, cu stație pe drumul de acces în ansamblu. Ieșirea spre Botoșani, pe DN{n} este la câteva minute — utilă pentru drumurile în afara orașului fără traversarea centrului.":
    "The Păcurari road has regular lines towards the centre and Copou, with a stop on the access road to the development. The exit towards Botoșani, on the DN{n} is a few minutes away — convenient for trips out of town without crossing the centre.",
"Pentru cei care lucrează în nord-vestul Iașului, accesul direct la artera Păcurari evită aglomerația din zona centrală la orele de vârf.": "For those working in north-western Iași, direct access to the Păcurari road avoids the congestion of the central area at peak hours.",
"Cui i se potrivește zona": "Who the area suits",
"Familiilor tinere: școală la {n} minute pe jos, loc de joacă și parc în incintă, curte proprie la apartamentele de la parter. Studenților și tinerilor angajați: Copou și centrul universitar la {n} km, transport direct. Investitorilor: cerere de chirii susținută de cei peste {n} de studenți ai orașului.":
    "Young families: a school {n} minutes' walk away, a playground and park on site, a private garden for ground-floor apartments. Students and young professionals: Copou and the university district {n} km away, with direct transport. Investors: rental demand supported by the city's more than {n} students.",
"Harta interactivă de pe pagina zonei permite selectarea fiecărui reper și afișarea traseului rutier.": "The interactive map on the area page lets you select each landmark and display the road route.",
"{n} m, pe jos": "{n} m, on foot",
"Aeroport": "Airport",
"Ghidul complet al zonei, cu hartă": "The full area guide, with map",
"Randament pentru investitori": "Yield for investors",
# --- articolul 5: randament ------------------------------------------------
"Randamentul chiriilor în Iași, {n}: ce arată cifrele pentru un apartament nou": "Rental yields in Iași, {n}: what the numbers show for a new apartment",
"Randamentul chiriilor în Iași, {n}: ce arată cifrele pentru un apartament nou | Emerald City": "Rental yields in Iași, {n}: what the numbers show for a new apartment | Emerald City",
"Între {n}% și {n}% brut, cu garsonierele în frunte. Cum am calculat, ce costuri lipsesc din estimare și de ce un apartament nou, finisat la cheie, se închiriază mai repede.": "Between {n}% and {n}% gross, with studios in the lead. How we calculated, which costs are missing from the estimate and why a new, turnkey-finished apartment lets faster.",
"Randamentul brut împarte chiria anuală la prețul de achiziție. Pentru estimare am folosit o chirie de aproximativ {n} €/m² util pe lună — o medie observată pentru locuințe noi, finisate, în zona Păcurari — și prețurile de listare ale unităților disponibile.":
    "Gross yield divides the annual rent by the purchase price. For the estimate we used a rent of about €{n}/m² of usable area per month — an average observed for new, finished homes in the Păcurari area — and the listing prices of the available units.",
"Randamentul net scade perioadele neînchiriate (implicit {n}% pe an) și aproximativ {n}% cheltuieli de administrare, impozit și reparații. Diferența dintre brut și net este, de regulă, de cel puțin un punct procentual.":
    "Net yield deducts vacancy periods ({n}% per year by default) and about {n}% for management, tax and repairs. The difference between gross and net is usually at least one percentage point.",
"Ce rezultă pe categorii": "What the results are by category",
"Garsonierele, de la {n} €, au randamentul brut cel mai ridicat — în jur de {n}% — și cel mai scurt timp de ocupare pe piața de închirieri din Iași. Apartamentele cu {n} camere, de la {n} €, se situează la un nivel apropiat, cu o cerere mai stabilă din partea cuplurilor și a tinerilor profesioniști.":
    "Studios, from €{n}, have the highest gross yield — around {n}% — and the shortest time to let on the Iași rental market. {n}-room apartments, from €{n}, are at a similar level, with steadier demand from couples and young professionals.",
"Apartamentele cu {n} camere au randamente brute ușor mai mici, în jur de {n}%, dar se adresează unui segment distinct: familii și relocări corporate, cu contracte pe termen mai lung.": "{n}-room apartments have slightly lower gross yields, around {n}%, but address a distinct segment: families and corporate relocations, with longer-term contracts.",
"De ce contează că este nou și finisat": "Why new and finished matters",
"Un apartament predat la cheie — parchet, gresie, faianță, obiecte sanitare, uși, centrală proprie, încălzire în pardoseală — se poate închiria după mobilare, fără luni de lucrări. Costurile de exploatare mici și contorizarea individuală sunt argumente în plus pentru chiriaș.":
    "A turnkey apartment — flooring, tiles, sanitary ware, doors, own boiler, underfloor heating — can be let after furnishing, without months of works. Low running costs and individual metering are further arguments for the tenant.",
"Garanțiile legale — structura pe toată durata clădirii, viciile ascunse {n} ani — reduc riscul de reparații neprevăzute în primii ani, exact perioada în care se recuperează costurile inițiale.": "The legal warranties — the structure for the life of the building, hidden defects for {n} years — reduce the risk of unexpected repairs in the first years, exactly the period in which the initial costs are recovered.",
"Taxele notariale, intabularea, TVA-ul aferent, mobilarea și echiparea inițială și eventualul comision al unei firme de administrare nu sunt incluse. Pentru o garsonieră, mobilarea completă pornește în general de la câteva mii de euro.":
    "Notary fees, land registration, the applicable VAT, initial furnishing and equipment and any property management fee are not included. For a studio, full furnishing generally starts at a few thousand euros.",
"Cifrele sunt estimări bazate pe prețuri de listare și pe chirii observate în zonă, cu rol informativ. Nu reprezintă consultanță de investiții; decizia aparține cumpărătorului, care poate consulta un specialist independent.": "The figures are estimates based on listing prices and rents observed in the area, for information only. They are not investment advice; the decision belongs to the buyer, who may consult an independent specialist.",
"≈ {n} €/m²/lună": "≈ €{n}/m²/month",
"Garsonieră, de la": "Studio, from",
"Studenți în Iași": "Students in Iași",
"peste {n}": "over {n}",
"Calculatorul de randament": "The yield calculator",
"Garsonierele disponibile": "Available studios",
"Toate prețurile": "All prices",
# --- articolul 6: etapa II --------------------------------------------------
"Etapa II intră în vânzare: {n} de apartamente în {n} blocuri, în jurul parcului central": "Phase II goes on sale: {n} apartments in {n} buildings, around the central park",
"Etapa II intră în vânzare: {n} de apartamente în {n} blocuri, în jurul parcului central | Emerald City": "Phase II goes on sale: {n} apartments in {n} buildings, around the central park | Emerald City",
"Cea mai mare etapă a ansamblului, cu blocurile {n} și acces direct la parcul dendrologic. Ce compartimentări sunt disponibile, la ce prețuri și cum se rezervă.": "The development's largest phase, with buildings {n} and direct access to the arboretum park. Which layouts are available, at what prices and how to reserve.",
"Ce cuprinde Etapa II": "What Phase II includes",
"Etapa II include blocurile {n} cu {n} de apartamente — aproape jumătate din ansamblu. Blocurile sunt dispuse în jurul parcului central, astfel încât majoritatea apartamentelor au vedere spre spațiul verde, nu spre parcări.":
    "Phase II includes buildings {n} with {n} apartments — almost half the development. The buildings are arranged around the central park, so most apartments look onto green space, not car parks.",
"Regimul de înălțime rămâne același ca în toate cele {n} blocuri: două demisoluri, parter și trei etaje, cu înălțimea maximă de {n} metri. Parcarea subterană și boxele sunt în demisoluri, cu lift direct din parcaj în scară.":
    "The height stays the same as in all {n} buildings: two basement levels, ground floor and three storeys, with a maximum height of {n} metres. Underground parking and storage rooms are in the basements, with a lift straight from the car park to the staircase.",
"Compartimentări și prețuri": "Layouts and prices",
"Sunt disponibile toate cele cinci compartimentări: garsoniere de tip {n}A, apartamente cu {n} camere de tip {n}A și {n}B și apartamente cu {n} camere de tip {n}A și {n}B, cu suprafețe utile între {n} și {n} m². Apartamentele de la parter au curte proprie, între {n} și {n} m².":
    "All five layouts are available: type {n}A studios, {n}-room apartments of types {n}A and {n}B and {n}-room apartments of types {n}A and {n}B, with usable areas between {n} and {n} m². Ground-floor apartments have a private garden, between {n} and {n} m².",
"Prețurile de pornire sunt aceleași ca în Etapa I, cu TVA inclus și cu toate finisajele. Lista completă, cu prețul fiecărei unități, este publicată în secțiunea de disponibilitate și se filtrează după etapă.": "Starting prices are the same as in Phase I, VAT and all finishes included. The full list, with the price of every unit, is published in the availability section and can be filtered by phase.",
"Calendar și condiții": "Schedule and terms",
"Săpăturile pentru blocurile {n} și {n} au început în septembrie; structura celorlalte blocuri urmează progresiv. Termenul de predare al fiecărei unități se înscrie în antecontract. Condițiile de plată sunt cele standard: {n}% avans la antecontract, diferența la predare, plăți intermediare opționale.":
    "Excavation for buildings {n} and {n} began in September; the structure of the other buildings follows progressively. Each unit's handover date is written into the pre-sale agreement. Payment terms are the standard ones: {n}% deposit at the pre-sale agreement, the balance on handover, optional interim payments.",
"Rezervarea se face la biroul de vânzări, cu blocarea prețului afișat până la semnarea antecontractului.": "Reservations are made at the sales office, with the listed price locked in until the pre-sale agreement is signed.",
"Apartamente în Etapa II": "Apartments in Phase II",
"Suprafețe utile": "Usable areas",
"Apartamentele din Etapa II": "Apartments in Phase II",
"Etapele ansamblului": "The development's phases",

# --- remedieri audit -------------------------------------------------------
"Living finisat într-un apartament Emerald City, Iași": "Finished living room in an Emerald City apartment, Iași",
"Living cu bucătărie deschisă, apartament Emerald City Iași": "Living room with open kitchen, Emerald City apartment, Iași",
"Zonă de zi cu măslin și perete de marmură, Emerald City Iași": "Living area with an olive tree and a marble wall, Emerald City Iași",
"Zonă de dining cu vedere spre grădină, Emerald City Iași": "Dining area overlooking the garden, Emerald City Iași",
"Dormitor finisat, apartament Emerald City Iași": "Finished bedroom, Emerald City apartment, Iași",
"Dormitor cu dressing, apartament Emerald City Iași": "Bedroom with walk-in wardrobe, Emerald City apartment, Iași",
"Hol de intrare finisat, apartament Emerald City Iași": "Finished entrance hall, Emerald City apartment, Iași",
"Hol de intrare finisat, Emerald City Iași": "Finished entrance hall, Emerald City Iași",
"Living cu bucătărie deschisă, Emerald City Iași": "Living room with open kitchen, Emerald City Iași",
"Baie finisată cu marmură și alamă, Emerald City Iași": "Bathroom finished in marble and brass, Emerald City Iași",
"Bucătărie cu blat din marmură, Emerald City Iași": "Kitchen with a marble worktop, Emerald City Iași",
"Ansamblu rezidențial dezvoltat de Green Stone Group": "Residential development built by Green Stone Group",
"Contact — Emerald City Iași": "Contact us — Emerald City Iași",
"Disponibilitate și prețuri — Emerald City": "Availability and prices — Emerald City",
"Despre": "About",
"listă și prețuri": "the list and prices",
"{n} întrebări despre actualizare, stări și modul de citire a listei.": "{n} questions about updates, statuses and how to read the list.",
"Cât de des se actualizează lista de disponibilitate?": "How often is the availability list updated?",
"Lista se generează din tabelul de vânzări al dezvoltatorului și se actualizează la fiecare modificare de stare: rezervare, semnare de antecontract sau eliberare a unei unități.": "The list is generated from the developer's sales ledger and is updated at every change of status: reservation, signing of a pre-sale agreement or release of a unit.",
"Ce înseamnă stările Disponibil, Rezervat și Vândut?": "What do the statuses Available, Reserved and Sold mean?",
"Disponibil: unitatea poate fi rezervată. Rezervat: este blocată pe numele unui cumpărător, până la semnarea antecontractului. Vândut: antecontractul sau contractul a fost semnat.": "Available: the unit can be reserved. Reserved: it is held in a buyer's name until the pre-sale agreement is signed. Sold: the pre-sale agreement or the contract has been signed.",
"Prețurile din listă sunt finale?": "Are the prices in the list final?",
"Prețurile afișate includ TVA și toate finisajele. Devin ferme la rezervare sau la semnarea antecontractului; până atunci pot fi actualizate odată cu lista.": "The listed prices include VAT and all finishes. They become firm on reservation or when the pre-sale agreement is signed; until then they may be updated together with the list.",
"Ce reprezintă prețul pe metru pătrat?": "What does the price per square metre represent?",
"Prețul unității împărțit la suprafața utilă. Balconul, curtea, boxa și locul de parcare nu intră în suprafața utilă, de aceea unitățile cu curte au un preț pe metru pătrat aparent mai mare.": "The unit's price divided by its usable area. The balcony, garden, storage room and parking space are not part of the usable area, which is why units with a garden show an apparently higher price per square metre.",
"Cum se filtrează după etapă sau după compartimentare?": "How do I filter by phase or by layout?",
"Butoanele Etapa I–III și Tip 1A–3B se combină cu celelalte filtre. Fiecare selecție se reflectă în adresa paginii, care poate fi trimisă mai departe sau salvată.": "The Phase I–III and Type 1A–3B buttons combine with the other filters. Every selection is reflected in the page address, which can be shared or saved.",
"Se poate primi lista completă pe e-mail?": "Can the full list be received by e-mail?",
"Da. Lista de disponibilitate, cu suprafețe, etaje, orientări și prețuri, se transmite pe e-mail în aceeași zi lucrătoare, la cerere.": "Yes. The availability list, with areas, floors, orientations and prices, is sent by e-mail on the same working day, on request.",
"Stadiul se corelează cu etapele din proiect și cu lista de disponibilitate pe etape.": "Progress ties in with the project phases and the availability list by phase.",
"Etapele proiectului": "The project phases",
"Apartamentele din Etapa I": "Apartments in Phase I",
"Noutăți din șantier": "News from the site",
"Etapa I: structura la etajul {n} în blocurile {n}": "Phase I: the structure at floor {n} in buildings {n}",
"Stadiul din septembrie {n} la Emerald City Iași: planșee turnate la blocurile {n} cofraje la {n} și săpături pentru Etapa II.": "September {n} progress at Emerald City Iași: slabs poured at buildings {n} formwork at {n} and excavation for Phase II.",
"Cum se cumpără un apartament nou în Iași: {n} pași": "How to buy a new apartment in Iași: {n} steps",
"Ghid practic: vizionare, rezervare, antecontract la notar, construcție și recepție — ce se semnează și ce se verifică la fiecare pas.": "A practical guide: viewing, reservation, pre-sale agreement at the notary, construction and acceptance — what is signed and checked at every step.",
"Încălzire în pardoseală vs. calorifere: confort și factură": "Underfloor heating vs. radiators: comfort and bills",
"Cum funcționează încălzirea în pardoseală cu centrală în condensație, ce economie aduce (până la {n}%) și ce trebuie știut la mobilare.": "How underfloor heating with a condensing boiler works, what it saves (up to {n}%) and what to know when furnishing.",
"Păcurari, în cifre: distanțe reale până la ce contează": "Păcurari in numbers: real distances to what matters",
"Distanțe măsurate de la Emerald City: școală la {n} m, Universitate la {n} km, centru la {n} km, aeroport la {n} km. Cui i se potrivește zona.": "Distances measured from Emerald City: school {n} m, University {n} km, centre {n} km, airport {n} km. Who the area suits.",
"Randamentul chiriilor în Iași {n} apartament nou": "Rental yields in Iași {n} new apartment",
"Randament brut estimat {n}%, cu garsonierele în frunte. Metoda de calcul, costurile neincluse și de ce un apartament nou se închiriază mai repede.": "Estimated gross yield {n}%, with studios in the lead. The calculation method, the costs not included and why a new apartment lets faster.",
"Etapa II intră în vânzare: {n} de apartamente, {n} blocuri": "Phase II goes on sale: {n} apartments, {n} buildings",
"Blocurile {n} din Emerald City Iași, în jurul parcului central: compartimentări {n}A–{n}B, prețuri de pornire neschimbate, rezervare la showroom.": "Buildings {n} at Emerald City Iași, around the central park: layouts {n}A–{n}B, unchanged starting prices, reservation at the showroom.",

"Etapa I: structura la etajul {n} în blocurile {n} | Emerald City": "Phase I: structure at floor {n}, buildings {n} | Emerald City",
"Etapa II în vânzare: {n} de apartamente în {n} blocuri": "Phase II on sale: {n} apartments in {n} buildings",
"Etapa II în vânzare: {n} de apartamente în {n} blocuri | Emerald City": "Phase II on sale: {n} apartments in {n} buildings | Emerald City",
"Cum se cumpără un apartament nou în Iași: {n} pași | Emerald City": "How to buy a new apartment in Iași: {n} steps | Emerald City",
"Încălzire în pardoseală vs. calorifere: confort și factură | Emerald City": "Underfloor heating vs. radiators | Emerald City",
"Păcurari, în cifre: distanțe reale până la ce contează | Emerald City": "Păcurari in numbers: real distances | Emerald City",
"Randamentul chiriilor în Iași {n} apartament nou | Emerald City": "Rental yields in Iași {n} new apartment | Emerald City",
"Butoanele Etapa I–III și Tip {n}A–{n}B se combină cu celelalte filtre. Fiecare selecție se reflectă în adresa paginii, care poate fi trimisă mai departe sau salvată.": "The Phase I–III and Type {n}A–{n}B buttons combine with the other filters. Every selection is reflected in the page address, which can be shared or saved.",
}
